### ISSUE TITLE
Composited escape keys problematic (added in v0.0.41)

### ISSUE THREAD

**Issue by Farwaykorse** [asvetliakov/vscode-neovim#102]
In Dutch, my native language, "jk" is quite common.

While I really like the ability to "jj" (added with "jk" in eb2c07c1e7f76907fbb03523386a3f079a659d97 and v0.0.41), hardcoding it into the plugin is problematic.

Is it possible to expose the choice of keys to the user, or supply a switch to enable each of these?

**Comment by asvetliakov** [comment]
put into your keybinding.json should do the trick:
```json
			{
				"command": "-vscode-neovim.compositeEscape1",
				"key": "j"
			}
```

but you're right it shouldn't be enabled by default

**Comment by Farwaykorse** [comment]
Thanks for your extremely fast response and fix!
