### ISSUE TITLE
2byte character edit problem

### ISSUE THREAD

**Issue by luzluna** [asvetliakov/vscode-neovim#104]
In insert mode no problem on editing 2 byte width character(CJK).
but normal mode problem on cursor move.

sample text (japanese, korean, chinese)
> こんにちは嬉しいです
> 안녕하세요 반갑습니다
> 你好，很高兴认识你

**Comment by DrakeXiang** [comment]
What exactly the problem is? 0.0.40 has fixed this issue I think, now seems works fine at least with Chinese.

**Comment by luzluna** [comment]
if i move on 2byte character, not moving just one character. 
i'll try to record situation and then attach video.

**Comment by luzluna** [comment]
https://www.youtube.com/watch?v=yAlICGOldD4

**Comment by DrakeXiang** [comment]
> https://www.youtube.com/watch?v=yAlICGOldD4

That's weird, I tested with Japanese/Korean/Chinese all works fine, this issue seems exactly like https://github.com/asvetliakov/vscode-neovim/issues/91, and it's fixed after update.

**Comment by asvetliakov** [comment]
@luzluna Works for me in your example. make sure you're using latest version

**Comment by luzluna** [comment]
oh now works well.. maybe i've updated plugin version.(i didn't recognize it, sorry)
i'm using 0.0.42 version. and using utf8 encoding.
just tested #91's '当节点连接异常时，您可以尝试节点切换' works well. 
and my test sample works well to.


but i found another problem.
https://youtu.be/bbw05W_wOHI

if i press esc for normal mode, cursor jump to strange position.
(i think it is minor problem...)

**Comment by asvetliakov** [comment]
I created #106 for your new problem
