### ISSUE TITLE
[minor]Visual selection not showing correct in some situations

### ISSUE THREAD

**Issue by DrakeXiang** [asvetliakov/vscode-neovim#105]
Given a text: `something`

vim action: `viw`

If cursor postion is at the last character(e.g. `g` in this case), nothing seems to be selected, but if continue vim action like `y` the whole `something` is copied as expected. When cursor at other position works fine.

**Comment by asvetliakov** [comment]
Looks like not easy to fix. Changing selection this case doesn't trigger cursor move event so vscode is unaware that the start of selection was changed. possible but very clunky workaround is to rebind ```v``` to notify vscode after operator has completed.

**Comment by asvetliakov** [comment]
Fixed in 0.0.43 (will be released soon)
