### ISSUE TITLE
bind K and gO to vscode actions

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#108]

**Comment by aminroosta** [comment]
@asvetliakov This plugin is awesome 🚀 

I found out that i could call any vscode command from my vimrc.
Even with arguments!
I think the above should be mentioned in the readme.

```vim
nnoremap K  :<C-u>call VSCodeCall('editor.action.showHover')<CR>
nnoremap ? :<C-u>call VSCodeCall('workbench.action.findInFiles', { 'query': expand('<cword>')})<CR>
```

**Comment by asvetliakov** [comment]
@aminroosta 
From readme 😄 

>It's possible to call vscode commands from neovim. See VSCodeCall/VSCodeNotify vim functions in vscode-neovim.vim file. VSCodeCall is blocking request, while VSCodeNotify is not

Probably need to move it to own section for better visibility.

Also there are also `VSCodeCallRange`/`VSCodeNotifyRange` in case if you need to specify some visual range for vscode command

Generally use `VSCodeNotify` unless you're really need blocking call
