### ISSUE TITLE
Don't automatically select '<,'> (visual selection range) in the command line prompt

### ISSUE THREAD

**Issue by hagabaka** [asvetliakov/vscode-neovim#111]
When opening the command line while there is a visual selection, `'<,'>` is inserted at the beginning of the command as expected. However this text is automatically selected, so in order to append the command after it, one has to deselect it first (maybe using the right arrow key). It would be nice if it doesn't come pre-selected.

If this is impossible to do with VSCode's API, maybe as an option the `'<,'>` can be just displayed in a label, and be inserted before the command when sending to neovim. I'm no vim expert so I don't know if being unable to edit that is too inflexible though.

**Comment by asvetliakov** [comment]
i agree that would be nice, but actually it's vscode limitation. I'll look what could be done here
