### ISSUE TITLE
Add "modeline" in Status Bar and/or Add Options for Cursor-style-per-mode

### ISSUE THREAD

**Issue by macintacos** [asvetliakov/vscode-neovim#113]
Currently, it's kind-of hard to determine whether or not you're in insert/normal/etc. mode. VSCodeVim solves this by putting `--INSERT--`, `--NORMAL--`, `--VISUAL--`, etc. in the status bar, but they also allow you to change the cursor style depending on which mode you're in. Either option (or both) would be great, as right now it's kind-of hard to figure out which mode you're in without just arbitrarily typing something.

Examples of preferences offered by the VSCodeVim extension:

```
  "vim.cursorStylePerMode.insert": "line",
  "vim.cursorStylePerMode.normal": "block",
  "vim.cursorStylePerMode.replace": "block-outline",
  "vim.cursorStylePerMode.visual": "block-outline",
  "vim.cursorStylePerMode.visualblock": "block-outline",
  "vim.cursorStylePerMode.visualline": "block-outline",
```

If this is possible now, I can't get it to work, so it'd probably be worth documenting how to do so.

**Comment by asvetliakov** [comment]
It displays the mode in status bar already:

![image](https://user-images.githubusercontent.com/8881674/71294654-6de59980-2379-11ea-92e1-df6976c00656.png)
![image](https://user-images.githubusercontent.com/8881674/71294659-70e08a00-2379-11ea-9251-4e4ef7662ca1.png)

as for configuring cursor style see `:help guicursor`

**Comment by macintacos** [comment]
Interesting, not sure why I can't see that:

![image](https://user-images.githubusercontent.com/8128941/71302260-4f7e9e80-2377-11ea-855f-8c5808cdfc2a.png)

I've made sure that it's actually enabled in the status bar... so I guess I should start turning off extensions one by one to figure out what's the culprit.

**Comment by asvetliakov** [comment]
@macintacos just in case, normal mode is not printed in modeline by default (may be controlled by some vim setting, i don't remember). You don't have it for the insert/visual modes too yeah?

since i see there is undo message from neovim, at least neovim statusbar works. Worth to try to check with empty init.vim if you have custom one, i doubt that other vscode extensions cause this.

**Comment by macintacos** [comment]
That's the thing... I use SpaceVim for my neovim config, so figuring that out might be kind-of frustrating 😅 will let you know if I resolve anything though!

**Comment by macintacos** [comment]
Managed to get around this a while ago my just conditional loading stuff specifically for VSCode using `if exists('g:vscode')` like suggested in the README instead of trying to figure out what in my SpaceVim config was messing up the modeline output. Closing this out.
