### ISSUE TITLE
vim-matchup seems to be broken

### ISSUE THREAD

**Issue by wbthomason** [asvetliakov/vscode-neovim#114]
[vim-matchup](https://github.com/andymass/vim-matchup) does not seem to work when running Neovim through vscode-neovim. In particular, `%` does not move between matching pairs (matchup binds this and prevents the default matchit plugin from loading). Without vim-matchup installed/enabled, `%` works as expected.

**Comment by asvetliakov** [comment]
Just quick test - does it work if you do ```set syntax=on``` and ```set filetype=<yourfiletype>``` ?

**Comment by wbthomason** [comment]
Ah, indeed it does (only after `set filetype`; `set syntax` alone doesn't do it)

**Comment by asvetliakov** [comment]
another test - disable syntax (`syntax off`) and try to set only filetype.

**Comment by wbthomason** [comment]
Yup, that also works (only after setting the filetype, again)

**Comment by asvetliakov** [comment]
great, thank you. i'm not sure yet should i enable filetype detection by default. In meantime you can put into your init.vim ```filetype on``` or ```filetype plugin on``` (the latter also enables corresponding ftplugin - see ```:help filetype```). Also you don't need filetype indent stuff so leave it off

**Comment by wbthomason** [comment]
Set these explicitly even though Neovim's default is to set `filetype plugin indent on`?

**Comment by asvetliakov** [comment]
yes, you're right, by default it's on. Looks like filetype detection doesn't work

**Comment by asvetliakov** [comment]
i logged #115 to fix filetype detection. thank you for the report

**Comment by wbthomason** [comment]
Yup! Thanks for the best-in-class extension and quick response!
