### ISSUE TITLE
HJKL (+arrows) completely stuck

### ISSUE THREAD

**Issue by digg33** [asvetliakov/vscode-neovim#119]
Hey man, awesome project! I seem to have hit a brick wall however. Everytime I start VS Code, the cursor is completely immobilised (HJKL and Arrows). Sometimes when I spam gt and gT after restarting VS Code several times it fixes itself. This does not always seem to work. It may not be a communication problem with NVim because commands such as :help do work and because it does not fix itself over time. I am able to switch into Insert Mode (using any of i, r, s, a) from wherever I place the cursor using the mouse. However x and dd do not work (maybe Normal Mode problem?) and once, when I pressed dd, I had gotten a 'No lines in buffer' in the status bar.
My VIMRC is quite vanilla with no keymappings or plug-ins. I am on Windows.
___
Please let me know if I can do anything to help and thanks for the amazing plug-in!

**Comment by asvetliakov** [comment]
@digg33 What neovim version do you use?

**Comment by digg33** [comment]
running :version in Nvim gives 0.5

**Comment by asvetliakov** [comment]
well, this is curious. After starting vscode the extension needs a few seconds to establish connection to neovim, but none of your problems should appear. Can you try to run:
1) with empty init.vim file
2) with latest stable nvim version (0.4.3)
3) wait few seconds after vscode loaded and hit enter few times (if you have errors in your vim file - then nvim may block UI and output error message, but it's not handled currently thus not visible)

**Comment by digg33** [comment]
If it's of any use, for some reason VS Code never shows any messages (like when I press :version) and the current mode is also not shown. Running :ls however shows some messages in a wrong way.
![Capture](https://user-images.githubusercontent.com/58906128/71328645-876e1900-2512-11ea-97aa-aa85a4669301.PNG)

**Comment by asvetliakov** [comment]
also init.vim/vimrc should have `LF` fileendings - vim may complete stuck when encounter `CRLF`

**Comment by digg33** [comment]
Good ideas, trying them right now.

**Comment by digg33** [comment]
My init.vim sourced my vimrc and both were CRLF. I am going to make a new init with LF and check now.

**Comment by digg33** [comment]
Okay, I am very sorry I should have tried with a fresh init. Its working fine now, no problems at all. 

On that note, there were some very good tips here. Do you think you could somehow quickly mark commits where you imparted these useful fixing/checking hints? I could go through these marks later and write them in a FAQ or Troubleshooting guide for the project perhaps.

**Comment by asvetliakov** [comment]
not sure i fully understand about mark commits, but FAQ or Troubleshooting guide is very good idea

**Comment by digg33** [comment]
Sorry, I meant issues not commits.
