### ISSUE TITLE
Double call to the command prompt doesn't work

### ISSUE THREAD

**Issue by pomdtr** [asvetliakov/vscode-neovim#120]
The plugin vim-sandwich provide a special type of surrounding which requires to input to value in the command prompt ([instant surrounding](https://github.com/machakann/vim-sandwich/wiki/Magic-characters)).

For example, `saiwi[command_prompt]foo<CR>[command_prompt]bar<CR>` makes a word surrounded by foo and bar. 

However, in VSCode, the second command promp does not appear.

**Comment by asvetliakov** [comment]
neovim sends `cmdline_hide` event following by `cmdline_show`. Hiding on first event triggers `onHide` which sends `Esc` to neovim
