### ISSUE TITLE
cmd + / commenting broken when multiple lines were selected

### ISSUE THREAD

**Issue by DrakeXiang** [asvetliakov/vscode-neovim#121]
As the title says, after last update when multiple line were selected using `V`, only the line with cursor will be commented using `cmd + /`, although `gc` doesn't have this issue, I can't set my vim-commentary to work correctly on jsx/tsx files.

v0.0.44

**Comment by asvetliakov** [comment]
visual mode don't produce visual selections from 0.0.43,see changelog.

>although gc doesn't have this issue

My recommendation is to use gc, or use [own binding and convert visual mode to selection before calling the command](https://github.com/asvetliakov/vscode-neovim/blob/ca633465286d7a7f89ab922aaf9aa65fbe639d8f/vim/vscode-code-actions.vim#L43-L53)

>I can't set my vim-commentary to work correctly on jsx/tsx files.

If you're trying to set local binding through `autocmd FileType` this doesn't work, but fixed in latest master ( #115 )

**Comment by asvetliakov** [comment]
Also setting ```
nmap <C-/> <Plug>VSCodeCommentaryLine
xmap <C-/> <Plug>VSCodeCommentary
``` 
should bring you the correct behavior too

**Comment by iansinnott** [comment]
The above solution didn't work for me unfortunately didn't work for me, but I was able to get CMD+/ working for multiline commenting doing the following. Maybe it will help anyone else who comes across this issue.

Pass through CMD+/ key to neovim:

```
// keybindings.json
  {
    "command": "vscode-neovim.send",
    "key": "cmd+/",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<D-/>"
  },
```

Use the `gc` mappings as mentioned elsewhere. Then map the command keys to the `gc` mappings (recursively!).

```vim
" init.vim
xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine

nmap <D-/> gcc
xmap <D-/> gc
```

**Comment by theol0403** [comment]
> Is it possible to do this where it keeps the current selected lines still highlighted and stay in visual mode after commenting?

You can add `gv` at the end of your binding.

**Comment by jackblackCH** [comment]
> The above solution didn't work for me unfortunately didn't work for me, but I was able to get CMD+/ working for multiline commenting doing the following. Maybe it will help anyone else who comes across this issue.
> 
> Pass through CMD+/ key to neovim:
> 
> ```
> // keybindings.json
>   {
>     "command": "vscode-neovim.send",
>     "key": "cmd+/",
>     "when": "editorTextFocus && neovim.mode != insert",
>     "args": "<D-/>"
>   },
> ```
> 
> Use the `gc` mappings as mentioned elsewhere. Then map the command keys to the `gc` mappings (recursively!).
> 
> ```viml
> " init.vim
> xmap gc  <Plug>VSCodeCommentary
> nmap gc  <Plug>VSCodeCommentary
> omap gc  <Plug>VSCodeCommentary
> nmap gcc <Plug>VSCodeCommentaryLine
> 
> nmap <D-/> gcc
> xmap <D-/> gc
> ```

For those looking for the lua version:
```
vim.api.nvim_set_keymap('x', 'gc', '<Plug>VSCodeCommentary', {})
vim.api.nvim_set_keymap('n', 'gc', '<Plug>VSCodeCommentary', {})
vim.api.nvim_set_keymap('o', 'gc', '<Plug>VSCodeCommentary', {})
vim.api.nvim_set_keymap('n', 'gcc', '<Plug>VSCodeCommentaryLine', {})
vim.api.nvim_set_keymap('n', '<D-/>', 'gcc', {})
vim.api.nvim_set_keymap('x', '<D-/>', 'gc', {})
```
