### ISSUE TITLE
Remapping Quick Open Not Working

### ISSUE THREAD

**Issue by macintacos** [asvetliakov/vscode-neovim#123]
I'm trying to set up the following remap in my `init.vim`:

```
nnoremap <Space>pf :<C-u>call VSCodeCall('workbench.action.quickOpen')<CR>
```

When I hit `<Space>` `p` `f` in VSCode, the Quick Open panel quickly appears and disappears. I tried removing the `<CR>` at the end to just make sure the command was being passed in correctly, and it was:  [screenshot](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/Jru71QQk/Image+2019-12-26+at+13.48.19.png?v=c8f473b83162b7d9f04b00669b284af8). Hitting "Enter" after that would correctly bring up the Quick Open sheet and leave it open, as expected. Not entirely sure why the remap is closing the sheet prematurely.

**Comment by asvetliakov** [comment]
Try `VSCodeNotify` instead of `VSCodeCall`

**Comment by macintacos** [comment]
Ah-ha, that works; didn't realize the bit saying to use `Notify` always unless you really need `Call`. Perhaps that should be placed a little earlier in the doc?

Regardless, I'll close this out. Thanks!
