### ISSUE TITLE
Remapped escape not working

### ISSUE THREAD

**Issue by erlais** [asvetliakov/vscode-neovim#124]
I use linux and have remapped my escape key to caps lock with `setxkbmap -option caps:escape`. It works everywhere in my OS as well as in vscode when I want to close the menu for example.

However, it does not exit insert or visual mode with this plugin for some reason. I have checked with `showkey` program that when I press escape or caps lock they output identical codes. Any ideas what could be causing this?

EDIT: Wanted to add that this is also the case with no other plugins installed and all default vscode settings. Oh, and normal escape key works just fine.

**Comment by asvetliakov** [comment]
Try to set in vscode settings:
`
"keyboard.dispatch": "keyCode"
`

See https://github.com/microsoft/vscode/issues/23991 for the background:

**Comment by erlais** [comment]
That fixed it! Should have assumed it's vscode issue.

Anyway, thanks for quick reply and your work on this extension. It's making me try vscode again after a long hiatus.

**Comment by asvetliakov** [comment]
You're welcome!
