### ISSUE TITLE
desync between neovim and vscode

### ISSUE THREAD

**Issue by 3nuc** [asvetliakov/vscode-neovim#125]
I'm running into a problem where the cursor desyncs and I find it difficult to provide a reproducible case for the issue.  @asvetliakov is there a group of files one can provide so you can get an idea of what could be going wrong in neovim or vscode itself when an issue appears?

eg. some kind of neovim input log or vscode log file?

Anyways, here's the issue
![cursor desync](https://user-images.githubusercontent.com/5359825/71534743-2b840580-2901-11ea-89e6-f90f3fdbc031.gif)

As you can see, the cursor doesn't want to select text that is actually there. But then, also when I do 'dd', it deletes the line below (`}`) instead of the `this.$router.push` line 

vscode-neovim 0.0.45
nvim 0.4.3 with empty init.vim and no plugins
vscode 1.41.1
ubuntu 19.04

**Comment by 3nuc** [comment]
Also posting another issue I've had. The cursor can become stuck in the middle of the file also.
![vscode stuck at bottom](https://user-images.githubusercontent.com/5359825/71534836-c7157600-2901-11ea-95b0-5775f9d86988.gif)

**Comment by asvetliakov** [comment]
Curious. I noticed you're using the mouse. Do you have `mouse start visual selection` toggle on in settings?

**Comment by asvetliakov** [comment]
>In the gif below the cursor was stuck immediately after starting vscode (the editor groups were saved from a previous session)

Create a separate issue. It was a known problem and i believed i fixed it, but looks like still no.

**Comment by 3nuc** [comment]
No I didn't have it enabled when creating the gifs above. I just wanted to show that there's no way to move the cursor at all.

Ok I'll do it

**Comment by asvetliakov** [comment]
For original issue it looks nvim buffer was shifted line down. There is one known problem regarding buffer desync - #116 . Any chance you run into it *before* the gif was made by pasting while in visual mode ?

**Comment by 3nuc** [comment]
I'm 99% sure I was using visual line, delete and paste (eg. V -> jjjj -> d -> kkkkkk -> p) pretty extensively before creating the gif.

**Comment by asvetliakov** [comment]
assuming it's some kind of #116 then. If you can provide full repro steps it'd help very much.

**Comment by 3nuc** [comment]
Hm, I think I've found something regarding the "cursor blocking and not wanting to go past a certain character" issue

Try creating a new untitled file inside vscode and paste this in:
```
ż",
ź",
ń",
ś",
ó",
ć",
ł",
ą",
a", //this works
```

When you're on the `"` character, and you press `l` (letter L, go right), you can't move the cursor to the `,` character. However when you go the last line of the pasted code snippet (`a",`), you can move the cursor to a",

**Comment by asvetliakov** [comment]
line number is not related, seems something with multi-byte chars 😞

**Comment by 3nuc** [comment]
Yep line number is not related, I just happened to add the working case at the bottom. `a",` could've been in the middle. I'll keep looking regarding 116, recently it started happening after changing editor groups but I couldn't repro twice.

**Comment by dsuess** [comment]
I think I've hit a similar issue with C++ files:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5870291/74621320-adb9d900-5190-11ea-9c54-38f5f0267dad.gif)

I have disabled all other plug-ins and have an empty `init.vim`. Here's the text:
```
auto test() {
  using namespace xtplaceholders;
  return xt::view(output, xt::all(), xt::keep(sorted_anchor_idx));
}
```

**Comment by 3nuc** [comment]
Closing because it's stale. Feel free to comment/reopen if you run into it.
