### ISSUE TITLE
Unable to use vim autocomplete plugins

### ISSUE THREAD

**Issue by LucasD11** [asvetliakov/vscode-neovim#130]
How can I keep use the autocomplete plugins if I switched from nvim to VSCode?

E.g. I'm using Ultisnips together with deoplete and jedi. And these doesn't work on neovim plugin of VSCode. The pop up suggestions are still VSCode origin suggestions.

**Comment by justinmk** [comment]
That's by design. The compromise of this plugin is that it lets vscode take over during insert-mode. That's a reasonable compromise that avoids a lot of problems.

**Comment by asvetliakov** [comment]
I think it's possible to write completion provider which pulls neovim completions and merge them with vscode completions, but no plans to do it currently

**Comment by PfisterFactor** [comment]
This would be an incredibly useful feature to have, as there are some snippets that can't be transferred over one to one from Ultisnips.

**Comment by Shatur95** [comment]
There is [vim-vsnip](https://github.com/hrsh7th/vim-vsnip) that have the same snippets format as in VSCode.
