### ISSUE TITLE
Add system specific vscode-neovim.neovimPath settings entries

### ISSUE THREAD

**Issue by 3nuc** [asvetliakov/vscode-neovim#137]
I use VSCode 'Settings Sync' extension and I have a personal laptop with Linux and a work laptop with Windows. I use vscode-neovim on both. 

Lately I uploaded my settings to Settings Sync from the Linux laptop with the `vscode-neovim.neovimPath` set to `/usr/bin/nvim`. Then I moved to my Windows work laptop - my neovim path was `C:\tools\nvim\bin\nvim.exe` and vscode-neovim was working ok. But then I downloaded the fresh settings and the `neovimPath` on Windows changed to the Linux one - `/usr/bin/nvim` and vscode-neovim stopped working.

Perhaps it would be cool to split the neovimPath into three separate settings:
`neovimPath.windows`,
`neovimPath.linux`,
`neovimPath.osx`,

VSCode already uses the convention I proposed with their `terminal.external.[linux/windows/osx]Exec` setting
![obraz](https://user-images.githubusercontent.com/5359825/71789313-a4364080-302a-11ea-995f-1ba4d840573e.png)

**Comment by asvetliakov** [comment]
It will be good also to look up for neovim executable automatically if not set
+ need to migrate old setting

**Comment by kwonoj** [comment]
for immediate workaround, you can use settings sync pragma : https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#per-os

**Comment by 3nuc** [comment]
I've created #157 and it does work (not sure if I should write tests for this even). But later I found that you can change setting scope. I'm not sure how to go about `useWsl` though - if `vscode-neovim.neovimPath` is deprecated then so is `useWsl`, as it relies on the value of `neovimPath`.

My PR adds 3 settings: path for linux, path for windows and path for osx. Maybe I should add another like `vscode-neovim.systemSpecificPath.wsl` that will be used only when the setting `useWsl === true`?

That will deprecate neovimPath AND will break things for wsl users, but will have consistency

**Comment by 3nuc** [comment]
Or useWSL could just use the values of the windows path

**Comment by asvetliakov** [comment]
[quote]
I'm not sure how to go about useWsl though - if vscode-neovim.neovimPath is deprecated then so is useWsl, as it relies on the value of neovimPath.
[/quote]

It can take either path from windows or linux setting... i'm not sure what will be right, but i think the linux path setting is the right choice in this case.

**Comment by genesy** [comment]
> for immediate workaround, you can use settings sync pragma : https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#per-os

@3nuc have you tried this for your settings json file? it should solve your issue BUT i agree having separate ones would be better and I think your PR is 👍

**Comment by 3nuc** [comment]
@genesy Nope, I didn't try it. I switched to a Windows only setup recently so it's not so annoying to me. I'm working on the PR now though cause it's laying around collecting dust.

The VS Code team is supposedly working on a built-in settings sync extensions and I wonder how they're gonna solve this of "different setting value on different system".
