### ISSUE TITLE
Your vim-easymotion has trouble with some chars

### ISSUE THREAD

**Issue by DanielFabian** [asvetliakov/vscode-neovim#144]
Consider this text file:

```
Level 3 — Madeye the Dead
Level 4 — Blacklash the Burning
Level 5 — Shadowcrow
Level 7 — Blighthorn Steelmace
Level 7 — Nightwing the Cold
Level 9 — Brokenstorm
Level 12 — Viletouch
Level 14 — Graywar the layer
```

Notice that the `-` is not a usual `-` but it's some kind of unicode char, presumably. And it completely screws up the decorations. What I did was `\\w` to reproduce it.

**Comment by asvetliakov** [comment]
Looks like for multi-byte chars (`—` is 3byte) are causing decoration to be shifted by byte offset. Should be easy to fix
