### ISSUE TITLE
Tab insertion on command line text generation

### ISSUE THREAD

**Issue by pomdtr** [asvetliakov/vscode-neovim#146]
Extension: vim-surround

Input: test
command: Try surrounding the word by a function (ysiwfprint)
Expected output: print(test)
Output: print (test)

**Comment by asvetliakov** [comment]
looks like it desyncs the buffer too

**Comment by asvetliakov** [comment]
tab character is inserted by extension while in command line mode

**Comment by asvetliakov** [comment]
Release v0.0.49 with the fix

**Comment by pomdtr** [comment]
Wow, thanks for the quickfix
