### ISSUE TITLE
Launching in WSL

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#147]
Ok, I know what's the problem. The command for launching in `nvim` is *bash-specific* and therefore it fails to create a process. Or, more precisely, the process dies almost immediately after being created, because it doesn't actually spawn `nvim`.

https://github.com/asvetliakov/vscode-neovim/blob/21ba0eb0ac483f45d73fb1333e46ae3178e4448d/src/controller.ts#L267

This line does a `$(wslpath 'c:\blabla')`. But that code doesn't work in *fish*, which is my default shell. So we should probably either start `nvim` inside of a *bash*, or somehow make the path resolution shell-agnostic.

Sorry to cause trouble.

_Originally posted by @DanielFabian in https://github.com/asvetliakov/vscode-neovim/issues/145#issuecomment-573396921_

**Comment by asvetliakov** [comment]
> path resolution shell-agnostic.

Probably we can execute wslpath through wsl.exe first, then capture the output

**Comment by DanielFabian** [comment]
Ya, that sounds more robust than writing an actual shell script.

**Comment by carsondwilber** [comment]
@asvetliakov Hey there. Is this issue resolved? Neovim isn't working for me because I am using WSL ("useWSL": true) and have the path set ("neovimPath": "/usr/bin/nvim") but it seems to freeze up the editor. Can't type anything, change modes, etc. Really unfortunate because I'm trying to integrate VSCodeVim and neovim to use custom commands but can't get neovim working at all.

**Comment by RichardMM** [comment]
Still with this problem when using WSL. Any fix?

**Comment by asvetliakov** [comment]
https://github.com/asvetliakov/vscode-neovim/commit/b7f850127564141e3a0b5dff05a6ac0ef4a89f97#commitcomment-42060588

**Comment by asvetliakov** [comment]
Seems the PR doesn't work at all and break bash shells as well. I don't have Win/WSL installed right now, so PRs are welcome here
