### ISSUE TITLE
synID() always returns 0.

### ISSUE THREAD

**Issue by southp** [asvetliakov/vscode-neovim#148]
## Summary
The nvim native function `synID({lnum}, {col}, {trans})` always returns 0, instead of the expected syntax ID.

I'd love to work on a patch if you could kindly give me some clues :)

## Expected result

1. Open a source code file with legit content.
1. Run `echo synID(line('.'), col('.'), 1 )` shows the syntax ID for where the cursor is hovering. e.g. for a PHP function signature, it will be 532.

## What happens instead
1. It always returns 0.

**Comment by asvetliakov** [comment]
syntax is disabled explicitly (by setting `set syntax=off`) since it's not useful for this extension... for what do you need it ?

**Comment by southp** [comment]
Thanks for clarifying! Actually I just happened to notice that when I tried to see if [tcomment](https://github.com/tomtom/tcomment_vim) would work, and it didn't because of this. Since it's intentional and makes a lot of sense, I'm closing this.
