### ISSUE TITLE
VSCode "toggle line comment" commend isn't aware of the visual mode selection.

### ISSUE THREAD

**Issue by southp** [asvetliakov/vscode-neovim#150]
## Summary
Selecting multiple lines by the visual mode selection and then toggling line commenting by either cmd-/ or executing "Toggle Line Comment" command from the command panel doesn't comment all the selected lines, but only the line hovered by the cursor.

## Expected result
All the selected lines are commented or uncommented.

## What happens instead
Only the cursor hovered line will be commented. Here is a screencast:
![demo-commenting](https://user-images.githubusercontent.com/1842898/72231689-d41bb000-35f7-11ea-865a-90aac5089939.gif)

**Comment by asvetliakov** [comment]
See readme:

>Visual modes are not producing real vscode selections (few versions had this feature previously, but it was implemented through ugly & hacky workarounds). Any vscode commands expecting selection won't work. To round the corners, invoking VSCode command picker through the default hotkeys (f1/ctrl/cmd+shift+p) from visual mode converts vim selection to real vscode selection. Also commenting/indenting/formatting works out of the box too. If you're using some custom mapping for calling vscode commands and depends on real vscode selection, you can use VSCodeNotifyRange/VSCodeNotifyRangePos (the first one linewise, the latter characterwise) functions which will convert visual mode selection to vscode selection before calling the command. See this for example and mapping

if you're using custom mapping for toggling comment line you need to pass it to neovim then call `VSCodeNotifyRange` with editor command. Or just use `nnoremap gc <Plug>VSCodeCommentary`
