### ISSUE TITLE
[Feature] Support inccommand

### ISSUE THREAD

**Issue by quark-zju** [asvetliakov/vscode-neovim#154]
Neovim has a neat feature that shows subsituation results in real time. It's similar to `hlsearch` but applies to subsituation.

It can be enabled by `set inccommand=nosplit`. Then `:s/foo/bar` will show preivews as typing.

Not sure how hard it is to implement, though. If there are some pointers, I might have a look when I got some time.

**Comment by asvetliakov** [comment]
Unfortunately this can'be supported right now:
1) neovim doesn't send buffer change events for this
2) even if it will have sent them, it will result into clunky behavior similar to non patched vim-easymotion (replacing text will result into linting/language errors)

Ideally there should be a vim plugin which calls extension method to putt decorations instead, similar [to this one](https://github.com/asvetliakov/vim-easymotion/blob/34fb922c3cf5e88cff3f0824005e219dce83ea6f/autoload/EasyMotion.vim#L1049)
