### ISSUE TITLE
Cursor frozen if you switch tab while in visual mode

### ISSUE THREAD

**Issue by 3nuc** [asvetliakov/vscode-neovim#156]
![cursor freeze after switching tab in visual](https://user-images.githubusercontent.com/5359825/72668695-d59b0d00-3a29-11ea-8538-741a0f92aebe.gif)

1. Create two untitled files
2. Write some lines in the first one, go into visual mode and select several lines
3. Go to the other untitled and try to go into insert mode and write something. Nothing will happen

Actually the cursor unfreezes if you press `s` (substitute) after moving to the new tab

vscode-neovim 0.50
vscode 1.41.1

**Comment by 3nuc** [comment]
Actually you don't have to select any lines - you just need to be in visual mode.

**Comment by asvetliakov** [comment]
It's not frozen actually - visual mode is not canceled when switching tabs by using mouse

**Comment by 3nuc** [comment]
Still occurs in 0.072

1. Create 2 untitled files, each in a separate tab, add 10 lines of content in each
2. Go to tab 1
2. Enter visual line mode (shift+v)
3. press j a few times so some lines are selected
4. use mouse to click on tab 2
5. pressing i doesn't enter insert mode

You can replace step 4 with "press ctrl+tab to switch to tab 2", but this is kinda a custom scenario since I have CTRL+TAB mapped to `workbench.action.nextEditorInGroup`

Actually the same thing happens with editor groups
