### ISSUE TITLE
Quick scope suddenly isn't working

### ISSUE THREAD

**Issue by exoticus** [asvetliakov/vscode-neovim#158]
So i am pretty happy with how this extension feels/works, everything was working perfectly including [quick scope](https://github.com/unblevable/quick-scope) vim plugin, it was highlighting characters in vscode normally but suddenly it doesn't work anymore, now i am pretty sure i haven't changed any settings or even updated anything. Been trying to find the source of the issue but unfortunately hit a dead end

**Comment by asvetliakov** [comment]
The problem with this plugin it uses default vim syntax HL groups (debuging reveals it's using `Identifier` HL group) which are ignored and i don't want to enable them since they may mess vscode syntax highlighting.

Hopefully, the plugin issue can be easily fixed by adding lines as stated in plugin's readme:
```
" Your .vimrc
highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
```

![image](https://user-images.githubusercontent.com/8881674/72857556-44909400-3cbe-11ea-9f4d-3c9c4d147e0a.png)

**Comment by exoticus** [comment]
@asvetliakov one thing that is driving me crazy is that it was working perfectly fine as is without adding anything in config and then suddenly it's gone. I just want to know why would it do that

**Comment by asvetliakov** [comment]
@exoticus Probably extension had a bug previously and didn't ignore default vim HL, so the plugin had been working due to that. Once it started to properly ignore HL the plugin was broken.

**Comment by exoticus** [comment]
@asvetliakov i finally figured out the cause, so it's not extension update which i suspected at first.. in my vim config i was setting `colorscheme` to `gruvbox-material` however i noticed that setting the color scheme causes vscode to blink upon file opening, so i moved the `colorsceme` call to an if statement, that's where i lost the highlight. turns out gruvbox colorscheme is setting `highlight QuickScopePrimary`, anyways so glad for your help and the absolutely awesome extension!

**Comment by artvinn** [comment]
Does this fix still work? Can't get it to work in VSCode :( I don't set any colorscheme either when running in VSCode. Any way to debug it?

**Comment by asvetliakov** [comment]
@artvinn set this into your init.vim:
```
highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
```

Revert/remove any extension HL related settings from your vscode's settings.json
Reload editor and it must work

**Comment by artvinn** [comment]
@asvetliakov Yep, I have that in init.vim

Tried disabling all the extensions and setting clean user config(only neovim executable is defined). But doesn't work still.

**Comment by artvinn** [comment]
@asvetliakov Sorry, totally my bad 🤦 I wasn't loading the plugins in my config when running in VSCode. All works. Thanks for qucik reply!

**Comment by asvetliakov** [comment]
@artvinn No prob, glad it's working 👍🏻
