### ISSUE TITLE
Highlight occurrences doesn't work in normal mode

### ISSUE THREAD

**Issue by exoticus** [asvetliakov/vscode-neovim#159]
So the highlight occurrences feature in vs code doesn't work while vim is in normal mode, I understand that this might be an implication of vscode not knowing where the cursor is located while vim is in normal mode but is there a way to get around that?
I am taking about this 
![image](https://user-images.githubusercontent.com/56480961/72911047-1a80b580-3d42-11ea-983c-f4286bfc9ba2.png)
Notice how instance of `anchor_start` are highlighted, but that's only in insert mode because vim isn't engaged.

I also wonder if the extension might report to vscode the current cursor location which i think it does because other things like bracket highlighting seems to work, then why doesn't it work with word occurrences?

**Comment by asvetliakov** [comment]
This seems vscode problem... it works if you put cursor by mouse, but not on `hjkl` movement. It may be because the extension sets vscode cursor directly

**Comment by exoticus** [comment]
@asvetliakov makes sense, yeah it works with brackets etc which further confirms to me that this might be a vscode bug, i'll file an issue there, however i don't want them to point fingers to the extension and blame it so i'll try to find a way to repro without the extension if possible

**Comment by asvetliakov** [comment]
I think it can be validated by creating simple vscode extension which listens for `type` event and does something like this:
```ts
const cursor = vscode.window.activeTextEditor!.selection.active;
// for "l" - like vim movement
vscode.window.activeTextEditor!.selections = [new vscode.Selection(cursor.line, cursor.pos + 1, cursor.line, cursor.pos + 1)];
```
then test on some line with repeated words. If it doesn't work then that is.

**Comment by exoticus** [comment]
@asvetliakov i'll test that and report back

**Comment by huejim** [comment]
The highlighting can be triggered by "editor.action.wordHighlight.trigger".
As a workaround I mapped it to the keys I use for jumping through these highlights. Not ideal but works.

**Comment by Shatur95** [comment]
Thank you! It would be nice to rigger it automatically on all cursor movements on the plugin side.
