### ISSUE TITLE
jj or jk as escape key doesn't work in integrated terminal

### ISSUE THREAD

**Issue by JodyStats** [asvetliakov/vscode-neovim#162]
Thank you for making this great extension. It is such a great improvement from VSCodeVim. My insert mode instantly get huge performance boost! I have some issues trying to remap escape key for integrated terminal. Following the instructions from `README.md`, I put this into my keybindings.json

```
{
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "when": "neovim.mode == insert",
        "args": "j"
 },
{
        "command": "vscode-neovim.compositeEscape2",
        "key": "k",
        "when": "neovim.mode == insert",
        "args": "k"
 }
```

It works in editor but not in integrated terminal. In integrated terminal, it simply inserts two `j`. I play around with `when` values but it doesn't work either.

```
{
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "args": "j"
 }
```

or 
```
{
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "when": "neovim.mode == insert || neovim.mode == cmdline_insert",
        "args": "j"
 }
```
Is there any way to remap escape key for `jj` and `jk` in integrated terminal?

**Comment by asvetliakov** [comment]
The extension doesn't work in integrated terminal - vscode simply doesn't send any events here, so no, there is no way to do it

**Comment by JodyStats** [comment]
Get it. Do you know any dirty workaround such as invoking VSCode commands to send escape key with double key press? I tried `workbench.action.terminal.sendSequence` but for multiple key press, it only works for modifier key, e.g., Ctrl/Shift/Alt, plus any alphanumeric keys like `Ctrl + j` but it doesn't work for `j + j` or `j + k`

```
{
        "key": ...,
        "command": "workbench.action.terminal.sendSequence",
        "when": "terminalFocus",
        "args": {
            "text": "\u001b"
        }
}
```
