### ISSUE TITLE
Ctrl+c Ctrl+v don't work

### ISSUE THREAD

**Issue by ShadyAlfred** [asvetliakov/vscode-neovim#170]
I can't copy text using Ctrl+c, although I disabled using ctrl keys in both normal and insert modes. I even tried to escape the keys using
```json
    {
        "command": "-vscode-neovim.send",
        "key": "ctrl+c"
    }
```

**Comment by asvetliakov** [comment]
Escape keys are not being sent to neovim
the correct keybinding is
```json
    {
        "command": "-vscode-neovim.escape",
        "key": "ctrl+c"
    }
```

But you're right `<C-c>` should be disabled if when you turn off insert control keys

**Comment by ShadyAlfred** [comment]
Oh, my bad. After fixing my keybinding it works well now, thanks.
I love Vim but copying and pasting from different files gets painful, many **"*y "*p**
