### ISSUE TITLE
`word` behaving like `WORD` for .fs files

### ISSUE THREAD

**Issue by reinux** [asvetliakov/vscode-neovim#171]
Not too sure under what conditions this happens, but it only seems to happen for .fs files.

Turning off ionide (the F# language server) doesn't seem to make a difference, but renaming from .fs to anything else fixes it.

My appdata/local/nvim and nvim-data folders are empty.

**Comment by justinmk** [comment]
Does it happen in `nvim` (i.e. outside of vscode)? If you remove your init.vim?

What steps exactly did you perform? `ciw` ?

**Comment by reinux** [comment]
I've deleted my nvim and nvim-data user folders, so no init.vim

Seems to happen with any command, whether it's `dw`, `ciw`, `cw`, `vw` or just navigating with `w`, as long as it's an .fs file.

I tried holding down `shift` to see if it would invert with `W`, but no effect.

**Comment by justinmk** [comment]
Again, does it happen with `nvim` (outside of vscode)?

Compare `:set iskeyword?`

**Comment by reinux** [comment]
Ah, just discovered `:verbose set iskeyword` and found that it was coming from Forth. I moved that out, and now it's fine.

Sorry for the false alarm.
