### ISSUE TITLE
Default to insert mode in split editors

### ISSUE THREAD

**Issue by pomdtr** [asvetliakov/vscode-neovim#174]
For Scm Views, Search Editor and Settings split Editor, Neovim should default to insert mode since normal mode is unusable.

**Comment by asvetliakov** [comment]
i think i'll actually fix these modes, except settings editor may be. Btw what is the "search editor" ? Peek view?
Related #53

**Comment by pomdtr** [comment]
It's a new feature introduced in January Release : https://code.visualstudio.com/updates/v1_42#_search-editor

There is also a custom editor feature in the roadmap : https://github.com/microsoft/vscode/issues/77131

**Comment by asvetliakov** [comment]
oh i somehow missed it from changelog😄 I think it's similar to other complex editors - once the plugin will handle undefined viewcolumn they all should work.
