### ISSUE TITLE
Cursor hover to show hints.

### ISSUE THREAD

**Issue by LHY-iS-Learning** [asvetliakov/vscode-neovim#176]
I am only able to mouse hover on the keyword to display hints.
Is it possible to use cursor to hover on keyword to display hints when in normal mode?

**Comment by justinmk** [comment]
All vscode commands can be mapped.

    nnoremap <silent> K <Cmd>call VSCodeCall('editor.action.showHover')<CR>

**Comment by asvetliakov** [comment]
Also default configured key - `gh`, `gd` for go-to-definition, `<C-w> gd` to open definition aside
