### ISSUE TITLE
Custom key bindings for window actions can conflict / overwrite vim rebinds

### ISSUE THREAD

**Issue by Lknechtli** [asvetliakov/vscode-neovim#179]
I'm trying to get this vim plugin to play nice: https://github.com/jooize/vim-colemak
It seems that this extension treats certain keybinds as special cases, which messes things up a bit.
For example: z is rebound to undo using this plugin, but in the extension, pressing z causes the editor to wait for a second keystroke instead of passing it onto vim directly.
It would be nice if there was a way to re-assign these special actions to different keys (in this case, tell the extension that I want to use "j" instead of "z")

**Comment by asvetliakov** [comment]
The extension rebinds some keys in neovim to perform vscode actions/communicate with extension from neovim, few things are not possible without it, mainly scrolling/HML stuff. For `z` and friends these are defined here [https://github.com/asvetliakov/vscode-neovim/blob/87314441e3aba082577d811b229c3ffaa97d2150/vim/vscode-scrolling.vim#L8-L19] (Check also other *.vim files)

Try to unbind these mappings before you load colemak plugin and check if it works.

**Comment by Lknechtli** [comment]
ah, so I can conditionally rebind those vscode commands using `if exists('g:vscode')` on the vim config side? neat! Guess this can be closed then.

**Comment by asvetliakov** [comment]
Sure. Feel free to reopen in case if you'll have any problems

**Comment by Lknechtli** [comment]
confirmed that this works as described:
```
if exists('g:vscode')
  " unbind vscode extension stuff
  unmap z<CR>
  unmap zt
  unmap z.
  unmap zz
  unmap z-
  unmap zb
endif

exe 'source' "$HOME/git/vim-colemak/plugin/colemak.vim"

if exists ('g:vscode')
  " rebind vscode extension commands to overwrite vim stuff
  
  function s:reveal(direction, resetCursor, restoreVisual)
      if a:restoreVisual
          normal! gv
      endif
      call VSCodeExtensionNotify('reveal', a:direction, a:resetCursor)
  endfunction
  nnoremap <silent> j<CR> :<C-u>call <SID>reveal('top', 1, 0)<CR>
  xnoremap <silent> j<CR> :<C-u>call <SID>reveal('top', 1, 1)<CR>
  nnoremap <silent> jt :<C-u>call <SID>reveal('top', 0, 0)<CR>
  xnoremap <silent> jt :<C-u>call <SID>reveal('top', 0, 1)<CR>
  nnoremap <silent> j. :<C-u>call <SID>reveal('center', 1, 0)<CR>
  xnoremap <silent> j. :<C-u>call <SID>reveal('center', 1, 1)<CR>
  nnoremap <silent> jj :<C-u>call <SID>reveal('center', 0, 0)<CR>
  xnoremap <silent> jj :<C-u>call <SID>reveal('center', 0, 1)<CR>
  nnoremap <silent> j- :<C-u>call <SID>reveal('bottom', 1, 0)<CR>
  xnoremap <silent> j- :<C-u>call <SID>reveal('bottom', 1, 1)<CR>
  nnoremap <silent> jb :<C-u>call <SID>reveal('bottom', 0, 0)<CR>
  xnoremap <silent> jb :<C-u>call <SID>reveal('bottom', 0, 1)<CR>
endif
```
