### ISSUE TITLE
Temporarily enter command mode from insert mode with ctrl+o

### ISSUE THREAD

**Issue by trkoch** [asvetliakov/vscode-neovim#181]
As I gather, this plugin „unbinds self from the type event“. Which I like in general… except: What would it take to allow `ctrl+o` to temporarily enter command mode from insert mode? It seems to work in principle with other mappings such as `ctrl+r`.

**Comment by asvetliakov** [comment]
This may work by just enabling `<C-o>` in `package.json` while being in insert mode (will route the request to neovim and it will trigger command line mode event which will be handled by extension). Not sure about consequences though

**Comment by trkoch** [comment]
For now, I added this to my `keybindings.json`. Seems to work so far.

    {
        "key": "ctrl+o",
        "command": "vscode-neovim.send",
        "args": "<c-o>",
        "when": "editorTextFocus && neovim.mode == insert"
    }

Great stuff! 👍

**Comment by wrvsrx** [comment]
It doesn't work as expected.

## Reproduce

1. open test.txt
2. press "i" and input "test"
3. press "ctrl+o" and "2h"
4. the cursor stays on the position behind "test".

The cursor should lie between "t" and "e".

**Comment by trkoch** [comment]
@wrvsrx I suggest you open a separate bug with a more detailed title. `ctrl+o` works fine in most cases by my observation.

**Comment by asvetliakov** [comment]
@trkoch i believe it still won't see insert mode changes, so use at your own risk

**Comment by trkoch** [comment]
@asvetliakov I'd like to take a look at this issue. Can you perhaps give us some hints how this could be tackled? I'm thinking of syncing with vim after each change in insert mode (but only when in insert mode triggered by `ctrl-o`).

**Comment by QAston** [comment]
@trkoch I've made a PR to fix this

**Comment by trkoch** [comment]
@QAston 😎 I'll give it a try. Hope @asvetliakov finds time to review.
