### ISSUE TITLE
feature request: a command to reinitialize neovim and vscode synchronization

### ISSUE THREAD

**Issue by davidovich** [asvetliakov/vscode-neovim#183]
First, let me say that I really like this extension, and think that it is how a vim-extension should be implemented for high vim compatibility. Kudos.

I sometimes observe that vscode-neovim gets de-synchronized from the neovim server and have not yet pinned point the culprit (seems to be when vscode editor enters text for me like replacements, or when editing go files with tabs). It gets hard to come back from this state, and am forced to restart my editing session.

Would it be possible to add a command to reload, or re-initialize the state as seen on a fresh editing session ?

**Comment by asvetliakov** [comment]
closing/reopening a tab should help - it destroys a buffer completely in neovim then opens the new one instead. But actually it would be great if you'll catch some repro steps (i know it's hard and not obvious sometimes)

**Comment by davidovich** [comment]
I will definitely try to reproduce, and open an issue if I can. 

In the meantime, I have observed that closing opening the tab won't help (and this in fact may be the path to investigation) as if the connection context is re-initialized on tab opening and the problems persists, that would mean that something in the file is causing the problem.

**Comment by asvetliakov** [comment]
Does it happen in any editor column (pane) or only for second+ ?

**Comment by newhook** [comment]
This happened to me a few days ago. I needed to restart vscode to fix the problem.

**Comment by asvetliakov** [comment]
closing in favor of #250
