### ISSUE TITLE
Previous position missing from jumplist when navigating by symbol

### ISSUE THREAD

**Issue by trkoch** [asvetliakov/vscode-neovim#185]
Steps
* Open a file type known by VSCode with symbols such as methods (e.g. `.ts`)
* `G`
* `gg`
* "Go To Symbol in File" (e.g. selecting a method a couple of lines down)
* `ctrl+o`

Actual
* Cursor is at end of file

Expected
* Cursor is at beginning of file (where it was before jump with "Go To Symbol in File")

Workaround
* Use VSCode provided `ctrl--`

I guess the issue here is that `vscode-neovim` needs to be notified that a jump was initiated by other means. As a counter example, `gd` and `ctrl-o` works fine.

**Comment by asvetliakov** [comment]
Easy workaround - execute go to symbol command from neovim, prepending by manual mark creation (`normal! m'`)

**Comment by trkoch** [comment]
Clever idea! For reference, how exactly would I accomplish this? Though I assume it won't catch other jumps e.g. from breadcrumbs, outline ,or by mouse. I vaguely remember folks at vscode-vim discussing this and hoping for an event emitted by VSCode.

**Comment by trkoch** [comment]
keybindings.json

```json
// Delegate <cmd+r> to vim
{
  "key": "cmd+r",
  "command": "vscode-neovim.send",
  "args": "<d-r>",
  "when": "editorTextFocus"
}
```

.vimrc
```
# Handle cmd+r (received as <d-r>), create a mark manually then jump to symbol
nnoremap <silent> <d-r> m':<c-u>call VSCodeNotify('workbench.action.gotoSymbol')<cr>
```

**Comment by asvetliakov** [comment]
Using vscode jumplist now
