### ISSUE TITLE
Can't move  beyond the 500th character of a line

### ISSUE THREAD

**Issue by gaoqiangks** [asvetliakov/vscode-neovim#187]
I don't why I can't move the cursor beyond  the 500th character by using j or w.  It works fine by clicking the mouse.

**Comment by asvetliakov** [comment]
The extension sets neovim width by 500 columns. Larger values will degrade neovim performance (it just not designed to handle big viewport area).
When you navigate to 501 column neovim viewport should scroll but currently neovim API doesn't send horizontal scroll events so the extension doesn't know about that the scrolling has happened.

[This neovim PR](https://github.com/neovim/neovim/pull/11748) may fix that and other navigation problems.

**Comment by gaoqiangks** [comment]
> The extension sets neovim width by 500 columns. Larger values will degrade neovim performance (it just not designed to handle big viewport area).
> When you navigate to 501 column neovim viewport should scroll but currently neovim API doesn't send horizontal scroll events so the extension doesn't know about that the scrolling has happened.
> 
> [This neovim PR](https://github.com/neovim/neovim/pull/11748) may fix that and other navigation problems.
> 
> BTW, what is your use case here? Are you often editing long lines? I can make width configurable if you really need this.

I edit Latex source file with your extension.  It would be very helpful if I can customize the width.  Thank you very very much!

**Comment by chibicode** [comment]
Saw that https://github.com/neovim/neovim/pull/11748 is merged for the upcoming 0.5.0 release 🎉
