### ISSUE TITLE
Visual mode mapping not working

### ISSUE THREAD

**Issue by ppwwyyxx** [asvetliakov/vscode-neovim#188]
I have the following lines in my `init.vim`:
```
	xnoremap <c-c> "+y
```
which makes "Ctrl-C" in visual mode copy the selected text.

This works in neovim. I added the following to vscode keybindings.json:
```
    { "key": "ctrl+c", "command": "vscode-neovim.send", "when": "neovim.mode == visual" },
```
hoping it would send Ctrl-C to neovim and do the copy. However, pressing "Ctrl-C" in visual mode inside vscode has no effect.

**Comment by asvetliakov** [comment]
you need to unbind `<C-c>` from escape key first - escape keys are treated a kind specially:

```json
                        {
				"command": "-vscode-neovim.escape",
				"key": "ctrl+c",
			},
```

**Comment by ppwwyyxx** [comment]
I do have this already. In fact I also tried <C-a> and got the same outcome.

**Comment by asvetliakov** [comment]
Ah, you forgot ```"args": "<C-c>"``` in your `vscode-neovim.send` keybinding

**Comment by ppwwyyxx** [comment]
Thanks a lot! That addresses the issue.

Btw, I got my original settings by clicking "copy" here:
![0217-15:37:59](https://user-images.githubusercontent.com/1381301/74692314-946a5a00-519b-11ea-8ea3-87386d38d1eb.png)

Copying this shortcut does not give me the "args" part so I didn't realize this.

Thanks again for your time
