### ISSUE TITLE
Repeat characters N times not working ?

### ISSUE THREAD

**Issue by 0xEval** [asvetliakov/vscode-neovim#190]
Hi @asvetliakov , first off thank you for writing this plugin.

I can't seem to have the following vim sequence to work:

`<NUM>a<Char><ESC> to input <NUM> repeated <Chars>.`

The key will not be repeated at all. Any idea why ?
PS: this works in the `vscodevim` plugin

**Comment by asvetliakov** [comment]
Fixed with #173 PR
