### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by 3nuc** [asvetliakov/vscode-neovim#197]
`NVIMPluginController.init()` sometimes takes ~5s to finish execution on my computer (1.8 Ghz but still)
So I went along and measured how long each `await` in `NVIMPluginController.init()` takes in a very stupid way
```ts
export const logTime = (label: string) => {
        console.log(label + " ");
        console.timeLog("label");
};
```
```ts
public async init(): Promise<void> {
        logTime("init");
        let resolveInitPromise: () => void = () => {
            /* ignore */
        };
        this.nvimInitPromise = new Promise(res => {
            resolveInitPromise = res;
        });
        await this.client.setClientInfo("vscode-neovim", { major: 0, minor: 1, patch: 0 }, "embedder", {}, {});
        logTime("setClientInfo");
        const channel = await this.client.channelId;
        logTime("channelId");
```
[Output console of running vscode-neovim with the above logTime() calls](https://gist.github.com/3nuc/dee209f3c65a93f9ba36cae02e001b95) - timings etc.
(There's lots of unnecessary output there, the format for the logTime() is:
```
functionName or whatever
label: [time in ms since start of activate() in extension.ts and end of execution of above function in line above]
```
but sometimes it outputs only the `label: timeInMs` for some reason

So if you round up the above data, here are the timings of the init() awaits chronologically (I omitted some functions that were very fast):
- `await this.client.setClientInfo("vscode-neovim", { major: 0, minor: 1, patch: 0 }, "embedder", {}, {});` - 174ms
- `const channel = await this.client.channelId` - 1301 ms **Δ1100ms** - this is from the node neovim client. [Link to code in neovim node-client code snippet](https://github.com/neovim/node-client/blob/03cce0abafe56a0742db6c20aced8533a1900be4/packages/neovim/src/api/client.ts#L50)
- `await this.client.setVar("vscode_channel", channel);` - 1601ms Δ300ms
- `await this.client.uiAttach(...)` 2503ms **Δ900ms** [Link to neovim node-client](https://github.com/neovim/node-client/blob/03cce0abafe56a0742db6c20aced8533a1900be4/packages/neovim/src/api/Neovim.ts#L708)
- `const firstWin = await this.client.window;` - 2865ms Δ350ms
- `await this.client.callAtomic(winOptionsRequests)` - 3747ms **Δ900ms**
- `(counts all calls in for loop cumulatively) await.thisBuffer(e)` - 4200ms Δ450ms
- `await this.onChangedActiveEditor(vscode.window.activeTextEditor` - 5200ms **Δ1000ms**

The above was performed on commit `68f056b4c9cb6b2559baa917f8c02166abd86f11` (vscode-neovim v0.5)

**Comment by 3nuc** [comment]
I was wondering if all those awaits need to come after eachother.
Instead of

```
await a;
await b
await c;
```
perhaps some operations could done concurrently doing
```
Promise.all([a,b,c])
```

**Comment by justinmk** [comment]
startup is instant for me, so even if perf were improved by some clever concurrent approach, which reduced your time to 1s, there is still something suspicious...

**Comment by asvetliakov** [comment]
don't think there could be much wins here. Perhaps we can drop `vscode_channel` here (i think we can broadcast from neovim side to all channels instead, if it's possible), remove `const firstWin = await this.client.window;` since we need only id and it's always `1000`. May be remove awaiting  for `setContext` command. 

`Promise.all` won't help much here, except may be combining `initBuffer`

Also the extension host is shared in vscode so others heavy extensions may kick in here and block execution of init for some time

**Comment by 3nuc** [comment]
![image](https://user-images.githubusercontent.com/5359825/75136224-45b14880-56e4-11ea-920b-62a3193b3e48.png)
The startup time for me is also 1s with all extensions disabled and if I don't open a workspace when starting VSCode. This all changes if I open a large-ish project which can be seen above (9472ms).

**Comment by asvetliakov** [comment]
@3nuc Are you using multi-root workspaces ? At work i have a big ts monorepo (but not using multi-root) and the startup time fine is fine for me.

Try to disable `vscode-js-import`. BTW TS/JS supports autoimporting/import-fixes just fine from the box.

The activation time is not the truly measurement here. An extension may block the extension host after activation (for example scanning/reading workspace files triggered by some vscode load event)

**Comment by 3nuc** [comment]
>Are you using multi-root workspaces?
Nope, the "large-ish project" I mentioned isn't so big that it requires a multi-root workspace. It just has quite a bit of files.
>Try to disable vscode-js-import BTW TS/JS supports autoimporting/import-fixes just fine from the box.
vscode-js-import has some extra magic when it comes to importing default exports and is a bit better, but I'll try because I'd rather have vscode-neovim than vscode-js-import :P vscode-js-import actually scans the workspace on launch so that may be it.

>The activation time is not the truly measurement here. An extension may block the extension host after activation (for example scanning/reading workspace files triggered by some vscode load event)

Is there another way of (if it exists) of watching what is happening to an extension after activation? To check if ext host is hijacked?

**Comment by asvetliakov** [comment]
>Is there another way of (if it exists) of watching what is happening to an extension after activation? To check if ext host is hijacked?

I think only by profiling in dev tab

**Comment by 3nuc** [comment]
Since this issue is pretty old and a lot has changed since it was filed I'm going to close it.

As of now (vscode-neovim 0.0.74) I'm getting 2128ms activation time in `Debug: Startup Performance` CTRL+SHIFT+P option

**Comment by dschuessler** [comment]
I'm still coming in at 5s startup time. Worse than the startup time itself is that the UI is already usable in the time vscode-neovim is still starting up. So once vscode-neovim is finished it forces me into normal mode in moments I might already be typing.

https://user-images.githubusercontent.com/5774545/106643437-0644da80-658a-11eb-8231-fc96788c5411.mov

I gladly help with debugging this. I vote to reopen.
