### ISSUE TITLE
The '.' operator does not work

### ISSUE THREAD

**Issue by fsoft72** [asvetliakov/vscode-neovim#198]
Hello, the '.' operator does not work.

Example:

- write   'hello world'
- go on 'h' of hello and change word with:  

> cw ciao [esc]

- now move on 'w' of world and press (dot)

> .

the 'world' word disappears (it should change to 'ciao')

**Comment by pomdtr** [comment]
Duplicate of my new #76, fixed by the #173 but not released yet
