### ISSUE TITLE
Move visually selected lines up/down

### ISSUE THREAD

**Issue by pianocomposer321** [asvetliakov/vscode-neovim#200]
see https://github.com/asvetliakov/vscode-neovim/issues/199#issuecomment-590534030

**Comment by asvetliakov** [comment]
Why so difficult and use vscode command here? In vim there is much easier way:
`
" Move up
xnoremap <Up> dkP
" Move down
xnoremap <Down> dkp
`

If you want to keep visual selection
`
xnoremap <Up> dkP`[v`]
xnoremap <Down> dkp`[v`]
`

**Comment by asvetliakov** [comment]
for single line/normal mode: `ddkP` and `ddp` respectively

**Comment by pianocomposer321** [comment]
I had used the :m[ove] command in regular vim, and it worked. But in the extension I'm getting weird results, I think because of some commands starting before others complete or something like that. Anyway, I would like to know how to do it by calling vscode's commands. They go faster anyway.

**Comment by asvetliakov** [comment]
```xnoremap <Up> dkP`[V`]``` works for me although the visual HL sometimes left on shifted line (minor visual glitch, actually it's not selected)

The problem with a few vscode commands that they're trying to manage cursor byself, e.g. the move line command shifts cursor up/down. This confuses neovim sometimes.

btw, here is the dumb vscode version:

```vim
function! s:move(up)
        let startline = line("'<")
        let endline = line("'>")
        let diff = endline - startline
       " use blocking request here since we need to wait
        call VSCodeCallRange(a:up ? 'editor.action.moveLinesUpAction' : 'editor.action.moveLinesDownAction', startline, endline, 0)
       " actually awaiting result of command doesn't mean that it was applied, so need a slight delay here
        call wait(40, 0)
        " Shift cursor up/down
        if a:up
                normal! k
        else
                normal! j
        endif
        " Reselect lines
        if abs(diff) > 0
                exe "normal! V" . abs(diff) . 'j'
        else
                normal! V
        endif
endfunction

xnoremap <Up> :<C-u>call <SID>move(1)<CR>
xnoremap <Down> :<C-u>call <SID>move(0)<CR>
```

This won't be faster than neovim dkP stuff since vscode needs to execute the command, send text change to neovim, reapply selection in neovim

**Comment by pianocomposer321** [comment]
Is there a command that converts visual selections into vscode selection, or are VSCodeNotifyRange and the like the only ways to do it? If there is a way to convert visual selection to vscode selection, it would be much easier to move the lines - I could just make a multicommand (with the multi-command extension) that would call that command, and then the command to move lines up or down. The same would apply for commenting multiple lines as in my other issue.

**Comment by asvetliakov** [comment]
`VSCodeNotifyRange`/`VSCodeNotifyRangePos` do that. As i said previously a change performed by vscode wouldl result into buffer api event change sent to neovim, which would result into resetting cursor position from neovim side, which would result into clearing vscode selections.

Just use vim keybindings for now
```
xnoremap <Up> dkP`[V`]
xnoremap <Down> dp`[V`]
```

![gif](http://g.recordit.co/uv9osnKYAb.gif)

The HL is a bit broken after moving but it's actually minor visual glitch and doesn't affect real visually selected area

**Comment by pianocomposer321** [comment]
As stated in the documentation, pressing F1 or Ctrl+Shift+P to open command pallet convert visual selection into vscode selection. What does this do under the hood, and is there a way to replicate it? The Highlight glitch is more than minor in my opinion.

**Comment by asvetliakov** [comment]
>What does this do under the hood, and is there a way to replicate it?

[It calls `VSCodeNotifyRange/VSCodeNotifyRangePos`](https://github.com/asvetliakov/vscode-neovim/blob/f9672b5cfcaef9464970c3b4824e001fc56ed8f7/vim/vscode-code-actions.vim#L42-L54) 😄 Well i'm really sorry about your frustration but looks like your task is not fully supported now

**Comment by asvetliakov** [comment]
As possible workaround you can move lines through vscode keybindings in insert mode. May be something like calling `startinsert` followed by `VSCodeNotifyRange` (or reverse) may work for you, along with additional filtering by `neovim.mode == insert` in `keybindings.json`, (e.g. while in normal mode - send to neovim, where call startinsert to trigger insert mode along with vscodenotifyrange, then in insert mode the control will be taken by vscode - it should prevent clearing of the cursor selection)

**Comment by pianocomposer321** [comment]
This sound promising, but I can't quite visualize what exactly you mean :-). Could you give me an example?

**Comment by asvetliakov** [comment]
Sure,

keybindings.json:
```json
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+shift+up",
        "when": "neovim.mode != insert",
        "args": "<Up>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+shift+down",
        "when": "neovim.mode != insert",
        "args": "<Up>"
    },
    {
        "command": "editor.action.moveLinesUpAction",
        "key": "ctrl+shift+up",
        "when": "neovim.mode == insert",
    },
    {
        "command": "editor.action.moveLinesDownAction",
        "key": "ctrl+shift+down",
        "when": "neovim.mode == insert",
    },
```

init.vim
```
function! s:startMoving()
        let startLine = line("'<")
        let endLine = line("'>")
        startinsert
        call VSCodeCallRange("editor.action.moveLinesUpAction", startLine, endLine, 1)
endfunction

xnoremap <Up> :<C-u>call <SID>startMoving()<CR>
xnoremap <Down> :<C-u>call <SID>startMoving()<CR>
```

Select something and press `Ctrl+shift+up` few times (or bind to another keys, neovim mappings correspond to that you've set in the `args` in `keybindings.json`) - just tried and it worked good. The only consequence you'll end in the insert mode.

the vimscript function supports only up moving - but it should be straightforward to add up/down argument here

**Comment by pianocomposer321** [comment]
If you added a `normal <esc>` to the end of the function, would that get rid of the selection too?

**Comment by asvetliakov** [comment]
It must. You don't need normal mode here because the extension will send a changes which will resync the cursor. But it doesn't communicate with neovim in insert mode at all (except while being in macro recording or for sending escape key). The trick here is to initially convert visual mode to selection and disable neovim communication at all

**Comment by pianocomposer321** [comment]
Ok. Thank you. I will try the workaround.

**Comment by pianocomposer321** [comment]
Thanks, it works. However the insert mode thing is worse then I had hoped, because I have to hit escape instead of jk to leave insert mode, or else it will will delete everything highlighted. I have an idea for a workaround. I'm crossing my fingers. :-)

**Comment by Shatur95** [comment]
I use [this plugin](https://github.com/matze/vim-move) for lines movement with the following shortcuts:

```json
    // Move lines
    {
        "key": "alt+j",
        "command": "editor.action.moveLinesDownAction",
        "when": "editorTextFocus && neovim.mode != 'visual'"
    },
    {
        "key": "alt+k",
        "command": "editor.action.moveLinesUpAction",
        "when": "editorTextFocus && neovim.mode != 'visual'"
    },
    {
        "key": "alt+j",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'visual'",
        "args": "<A-j>"
    },
    {
        "key": "alt+k",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'visual'",
        "args": "<A-k>"
    },
    {
        "key": "alt+h",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'visual'",
        "args": "<A-h>"
    },
    {
        "key": "alt+l",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'visual'",
        "args": "<A-l>"
    }
```

But yes. I expecting the same annoying glitch as here but only for moving line down (moving up works as expected).

**Comment by dgokcin** [comment]
@pianocomposer321 I use this mapping eith the combination of  the following helper functions  to move visual selections up and  down. It also works  on vscode(a little bit buggy)

```vim
" Move lines up and down without loosing the cursor position
vnoremap J :<C-u>call MoveVisualDown()<CR>
vnoremap K :<C-u>call MoveVisualUp()<CR>
```

```vim
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Moves lines up and down, while keeping the cursor pos
function! MoveLineUp()
    call MoveLineOrVisualUp(".", "")
endfunction

function! MoveLineDown()
    call MoveLineOrVisualDown(".", "")
endfunction

function! MoveVisualUp()
    call MoveLineOrVisualUp("'<", "'<,'>")
    normal gv
endfunction

function! MoveVisualDown()
    call MoveLineOrVisualDown("'>", "'<,'>")
    normal gv
endfunction

function! MoveLineOrVisualUp(line_getter, range)
    let l_num = line(a:line_getter)
    if l_num - v:count1 - 1 < 0
        let move_arg = "0"
    else
        let move_arg = a:line_getter." -".(v:count1 + 1)
    endif
    call MoveLineOrVisualUpOrDown(a:range."move ".move_arg)
endfunction

function! MoveLineOrVisualDown(line_getter, range)
    let l_num = line(a:line_getter)
    if l_num + v:count1 > line("$")
        let move_arg = "$"
    else
        let move_arg = a:line_getter." +".v:count1
    endif
    call MoveLineOrVisualUpOrDown(a:range."move ".move_arg)
endfunction

function! MoveLineOrVisualUpOrDown(move_arg)
    let col_num = virtcol(".")
    execute "silent! ".a:move_arg
    execute "normal! ".col_num."|"
endfunction
```

**Comment by doongjohn** [comment]
this is a modified lua version of @jonpdw's solution
it still has a bug when the selection contains trailing empty newlines 😕
but I'm happy with this

```lua
function MoveVisualSelection(direction)
  -- vim.pretty_print(vim.fn.line('.'))
  -- vim.pretty_print(vim.fn.line('v'))

  local cursorLine = vim.fn.line('v')
  local cursorStartLine = vim.fn.line('.')

  local startLine = cursorLine
  local endLine = cursorStartLine

  if direction == "Up" then
    if startLine < endLine then
      local tmp = startLine
      startLine = endLine
      endLine = tmp
    end
  else -- == "Down"
    if startLine > endLine then
      local tmp = startLine
      startLine = endLine
      endLine = tmp
    end
  end

  -- move lines
  vim.cmd("call VSCodeCallRange('editor.action.moveLines" .. direction .. "Action'," .. startLine .. "," .. endLine .. ",1)")

  -- move visual selection
  if direction == "Up" then
    if endLine > 1 then
      startLine = startLine - 1
      endLine = endLine - 1

      -- exit visual mode
      vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<esc>", true, false, true), 'x', true)

      -- select range
      vim.cmd("normal!" .. startLine .. "GV" .. endLine .. "G")
      -- vim.api.nvim_command(tostring(endLine)) -- move cursor
      -- vim.api.nvim_feedkeys("V", 'n', false) -- enter visual line mode
      -- vim.api.nvim_command(tostring(startLine)) -- move cursor
    end
  else -- == "Down"
    if endLine < vim.api.nvim_buf_line_count(0) then
      startLine = startLine + 1
      endLine = endLine + 1

      -- exit visual mode
      vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<esc>", true, false, true), 'x', true)

      -- select range
      vim.cmd("normal!" .. startLine .. "GV" .. endLine .. "G")
    end
  end
end

keymap_fun_ns('v', '<a-up>', function() MoveVisualSelection('Up') end)
keymap_fun_ns('v', '<a-down>', function() MoveVisualSelection('Down') end)
```

**Comment by jgirardet** [comment]
@jonpdw your solution is great except if you hit the top or the bottom of the file, then the Selection change.
on bottom: the selection is just turned to one line.
on top: if you keep K pressed, its going on infinitly and all is messed up.
Here is a proposal to fix it :
```vim
   function! MoveVisualSelection(direction)
     ": Summary: This calls the editor.action.moveLines and manually recalculates the new visual selection

    let markStartLine = "'<"                     " Special mark for the start line of the previous visual selection
    let markEndLine =   "'>"                     " Special mark for the end line of the previous visual selection
    let startLine = getpos(markStartLine)[1]     " Getpos(mark) => [?, lineNum, colNumber, ?]
    let endLine = getpos(markEndLine)[1]
    let removeVsCodeSelectionAfterCommand = 1    " We set the visual selection manually after this command as otherwise it will use the line numbers that correspond to the old positions
    let linecount = getbufinfo('%')[0].linecount
     



    if (a:direction == "Up" && startLine == 1) || (a:direction == "Down" && endLine == linecount) 
        let newStart = startLine
        let newEnd = endLine
    else
      call VSCodeCallRange('editor.action.moveLines'. a:direction . 'Action', startLine, endLine, removeVsCodeSelectionAfterCommand )
      if a:direction == "Up"
        let newStart = startLine - 1
        let newEnd = endLine - 1
      else 
        let newStart = startLine + 1
        let newEnd = endLine + 1
      endif
    endif
      
    let newVis = "normal!" . newStart . "GV". newEnd . "G"
    ":                  │  └──────────────────── " The dot combines the strings together
    ":                  └─────────────────────── " ! means don't respect any remaps the user has made when executing
    execute newVis
endfunction

":        ┌───────────────────────────────────── " Exit visual mode otherwise our :call will be '<,'>call
vmap J <Esc>:call MoveVisualSelection("Down")<CR>
vmap K <Esc>:call MoveVisualSelection("Up")<CR>

```
