### ISSUE TITLE
[Feature Request] Keybinding with a sequence of keys

### ISSUE THREAD

**Issue by yan42685** [asvetliakov/vscode-neovim#205]
I would like to have the ability of add many individual keys strokes in order to trigger a command in insert mode.
That may look like:
```
{"key": "k j", "command": "escapeToNormalMode"} 
```
```
{"key": "; ;", "command": "escapeToNoremalMode", "postKeys": "A ; <CR>"}
```
Because I prefer to use "kj" to escape from insert mode instead of "jk" or "jj" :blush:

**Comment by asvetliakov** [comment]
For escape key you can set compositeEscape1/compositeEscape2 . Although it's not possible to enable `kj` without `kk` right now, see #166

For other keybindings this won't be supported - vscode doesn't support key bindings with press timeout. Enabling them through `type` event will suffer same performance problems as in vscodevim.
