### ISSUE TITLE
Recording Macro does some weird stuff

### ISSUE THREAD

**Issue by ngharrison** [asvetliakov/vscode-neovim#207]
Steps to reproduce problem:

1. Start recording macro, e.g. `qq`
2. Open new line to edit below, e.g. `o`
3. Type something

The text will be put on the line above instead of the original line and the cursor will be before the character being input instead of after. If you continue moving around, going in and out of insert mode, and typing in text, it will sometimes put in copies of lines from down below. If you try to undo, it will start duplicating or deleting parts of lines randomly (I haven't found the pattern yet). Seems like another insert mode problem.

I have nothing in my init.vim file and have disabled all other vs code plugins.

**Comment by fesnavarro** [comment]
Even . isn't working, buffer comes empty
