### ISSUE TITLE
Neovim: configure the path to neovim and restart the editor

### ISSUE THREAD

**Issue by gibbok** [asvetliakov/vscode-neovim#208]
I am using on MAC NVIM v0.4.3 and I have added Neovim in my path as:

```
export PATH="/usr/local/bin/nvim:$PATH"
```
When loading VSCode with `vscode-neovim` installed I always get the following error and I cannot use your extension:

```
Neovim: configure the path to neovim and restart the editor
```
How to fix this issue?

**Comment by asvetliakov** [comment]
You need to configure neovim path in vscode settings, the extension doesn't look into path env variable for now

**Comment by lacostenycoder** [comment]
I'm having the same issue.  In terminal:
```
which nvim
/usr/local/bin/nvim
```
And I have this my settings.json

` "vim.neovimPath": "/usr/local/bin/nvim",`

so what am I doing wrong?

**Comment by iwyg** [comment]
Same here:

Neovim: configure the path to neovim and restart the editor

```json
{
    "vim": {
      "enableNeovim": true,
      "neovimPath": "/usr/local/Cellar/neovim/0.4.3/bin/nvim",
      "disableAnnoyingNeovimMessage": true,
    }
}
```

```bash
> ls -l /usr/local/Cellar/neovim/0.4.3/bin/nvim
> -r-xr-xr-x  1 malcolm  staff  3061692 xx Xxx xx:xx /usr/local/Cellar/neovim/0.4.3/bin/nvim
```

**Comment by asvetliakov** [comment]
@lacostenycoder @iwyg 

the setting id is `vscode-neovim.neovimPath` not `vim.neovimPath` which is for vscodevim

**Comment by iwyg** [comment]
ah, makes sense. Thanks!

**Comment by awongh** [comment]
can the path `vscode-neovim.neovimPath` please be added to the docs? had to search to find this info.

**Comment by storypixel** [comment]
just a heads up this setting `vscode-neovim.neovimPath` may not be deprecated? 
![image](https://user-images.githubusercontent.com/62480/106617913-a1ab6080-6534-11eb-9863-a05ceea8a845.png)

**Comment by Shatur95** [comment]
@storypixel, yes, there is the OS-specific option available (`vscode-neovim.neovimExecutablePaths.linux`, `vscode-neovim.neovimExecutablePaths.win32`, etc.).

**Comment by michaeldupuisjr** [comment]
I'm also running into the error message and am unable to use the extension on macOS 10.15.7 with Neovim installed via Homebrew.

I've tried VS Code settings.json with both:

```json
{
    "editor.tabSize": 2,
    "window.autoDetectHighContrast": false,
    "vscode-neovim.neovimExecutablePaths.linux": "/usr/local/Cellar/neovim/0.4.4_1/bin/nvim"
}
```

and:

```json
{
    "editor.tabSize": 2,
    "window.autoDetectHighContrast": false,
    "vscode-neovim.neovimExecutablePaths.linux": "/usr/local/bin/nvim"
}
```

**Comment by DrJohnWagner** [comment]
Just to be clear: the setting is "vscode-neovim.neovimExecutablePaths.darwin", vscode-neovim.neovimExecutablePaths.linux" or vscode-neovim.neovimExecutablePaths.win32", depending on OS.
