### ISSUE TITLE
Integration with VSCode settings and keybindings + leader key

### ISSUE THREAD

**Issue by tb-exto** [asvetliakov/vscode-neovim#213]
Great extension @asvetliakov. For the past two years I have used the VSCodeVim plugin and now I am trying to adapt some of the commands to VSCode-Neovim extensions.

1. This is how the Zen Mod activation command looks like in the VSCodeVim plugin, how should it be defined for VSCode-Neovim?

```
 {
      "before": [
        "<leader>",
        "t",
        "z"
      ],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.toggleZenMode",
          "args": []
        }
      ]
    }
```

2. I wonder if pressing a leader key show an indicator (text/symbol) in the VSCode status bar?

**Comment by justinmk** [comment]
Define mappings (except insert-mode) in Nvim config (`init.vim)`. https://github.com/asvetliakov/vscode-neovim#invoking-vscode-actions-from-neovim

```
if exists('g:vscode')
  nnoremap <silent> <leader>tz <Cmd>call VSCodeCall('workbench.action.toggleZenMode')<CR>
endif
```
