### ISSUE TITLE
Doesn't appear to detect current files directory

### ISSUE THREAD

**Issue by routinelyxyz** [asvetliakov/vscode-neovim#214]
Apologies if I've simply misconfigured it, I've just discovered and installed this incredible plugin a few minutes ago, bravo!

I've just tried:

:20,28 w Attributes.ts

I can see in the Vim Command Line that pops up that it's using my $HOME directory as the $PWD, is there any way to improve this behaviour? Am currently using autochdir in my init.vim but perhaps there's an alternative when using vscode?

My goal incidentally with that command was to move some lines into another file, in the process of refactoring a class, perhaps there's an alternative.

**Comment by justinmk** [comment]
you would need to use `:Write` instead of `:w`. See discussion in https://github.com/asvetliakov/vscode-neovim/issues/136

@asvetliakov did you see my comment here?: https://github.com/asvetliakov/vscode-neovim/issues/136#issuecomment-581085268

**Comment by asvetliakov** [comment]
I think this must be fixed by #429 (although don't support vscode's multi-root workspaces)
