### ISSUE TITLE
Add missing scrolling keys

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#22]
Since vscode owns scrolling need to implement H, M, L, z starting commands (help scroll-cursor)

**Comment by asvetliakov** [comment]
Switched to neovim scroll management

**Comment by timjs** [comment]
I use use these mappings in my day-to-day Neovim setup:
```
nnoremap H  ^
nnoremap L  $
nnoremap M  %
```
However, they do not seem to work in VSCode. Any idea how I should fix this?

**Comment by asvetliakov** [comment]
```
nnoremap <silent> <expr> ^ VSCodeCall('vscode-neovim.shift-h')
nnoremap <silent> <expr> % VSCodeCall('vscode-neovim.shift-m')
nnoremap <silnet> <expr> $ VSCodeCall('vscode-neovim.shift-l')
```

**Comment by asvetliakov** [comment]
Also subscribe to #41. I'd probably move mapping to neovim side so you'll need to change your bindings to something like ```nnoremap <expr> H VSCodeExtensionNotify('goToLine', 'top')``` after this is done. Sorry for inconvenience.

**Comment by asvetliakov** [comment]
Once ```0.0.25``` is landed, check [vscode-scrolling.vim](/vim/vscode-scrolling.vim) for reference if you need remapping

**Comment by timjs** [comment]
Thanks for all the info @asvetliakov! Keep up the good work :-)
