### ISSUE TITLE
Remap "r" key

### ISSUE THREAD

**Issue by notiv-nt** [asvetliakov/vscode-neovim#222]
Trying to live with dvorak layout.
Not sure if this is possible to remap "r" to "p" ?

**Comment by jensbodal** [comment]
This uses normal nvim `init.vim` file if you use one, so you would just remap keys as you normally would.

```
map r p
map R P
```

**settings.json**

```
    "vscode-neovim.neovimPath": "/usr/local/bin/nvim",
    "vscode-neovim.neovimInitPath": "/Users/username/.config/nvim/init.vim"
```

Check you `nvim` path with `which nvim`

Newer versions of nvim store the config in `$HOME/.config`.  And I think you need the newer version to use this extension.  I don't know what the paths are if you use Windows.
