### ISSUE TITLE
Can't install this plugin in vscode

### ISSUE THREAD

**Issue by zct** [asvetliakov/vscode-neovim#224]
Tips:
Unable to install 'asvetliakov.vscode-neovim' extension because it is not compatible with the current version of VS Code (version 1.37.1).

NeoVim 0.0.50

**Comment by pavkum** [comment]
@zct you can install latest version of VSCode 1.43.0. Also minimum supported version of NeoVim is 0.4.2.

**Comment by zct** [comment]
> @zct you can install latest version of VSCode 1.43.0. Also minimum supported version of NeoVim is 0.4.2.

thks~，it works
