### ISSUE TITLE
Uppercase marks not working

### ISSUE THREAD

**Issue by mthewissen** [asvetliakov/vscode-neovim#228]
_Example to reproduce:_
Set an uppercase mark, e.g. **mD**.
Open another editor.
Jump back to the mark by pressing **`D**

_What happens vs what is expected:_
Cursor jumps to the correct position (i.e. marked line number and column) but in the current file.
It should jump to that position the original file instead.

**Comment by asvetliakov** [comment]
Using uppercased marks are dangerous now, because neovim replaces buffer but doesn't notify vscode

**Comment by Shatur95** [comment]
Sure, will try to fix this evening.

**Comment by Shatur95** [comment]
Hm... By default vim accepts `{a-zA-Z}` for this motion. Should I accept all of them?

**Comment by asvetliakov** [comment]
>Hm... By default vim accepts {a-zA-Z} for this motion. Should I accept all of them?

Yup, easier to wrap everything i guess

**Comment by Shatur95** [comment]
Got it. The fix is super easy :)

@mthewissen, Could you try #356?

**Comment by asvetliakov** [comment]
Fixed

**Comment by mthewissen** [comment]
This is great, thanks!
