### ISSUE TITLE
extension doesn't pick up nvim path

### ISSUE THREAD

**Issue by biowaffeln** [asvetliakov/vscode-neovim#229]
Hi! I was trying to set up the extension on linux (elementaryOS 5.1) but it doesn't pick up the neovim path that I set. I tried multiple versions, first the one from [snap store](url) (which is v0.5.0), then I tried downloading the [nvim.appimage](https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package) (which is v0.4.3) and setting that path, both didn't work.

steps to reproduce:
1. download nvim.appimage into `~/downloads/`
2. in the vscode extension settings, set neovim path to `~/downloads/nvim.appimage`
3. restart vscode
4. extension doesn't launch

Any idea what the problem could be?

**Comment by mattolenik** [comment]
Maybe try using the absolute path? The `~` bit usually doesn't work outside of a shell

**Comment by biowaffeln** [comment]
Ahhh yep, that was actually it, thank you!
