### ISSUE TITLE
Enhancement: have separate "neovimPath" config for different OS.

### ISSUE THREAD

**Issue by yzhuang** [asvetliakov/vscode-neovim#232]
For people that sync their settings across different OS, it would be nice if we can support different neovimPath for different OS, just like the how vscode has different terminal settings: 
- `terminal.integrated.shell.windows`
- `terminal.integrated.shell.osx`
- `terminal.integrated.shell.linux`

It would be nice if we can have separate:
- `vscode-neovim.neovimPath.windows`
- `vscode-neovim.neovimPath.osx`
- `vscode-neovim.neovimPath.linux`

Same would be nice for `neovimInitPath`.
Right now, whenever I sync settings, I break vscode neovim on different OS. 

Moreover, `useWSL` should only have effects on windows.  Currently, turning it on in OSX breaks vscode-neovim.

Thank you very much!

**Comment by yzhuang** [comment]
Actually, found https://github.com/asvetliakov/vscode-neovim/pull/157

Closing this issue

**Comment by 3nuc** [comment]
I'm not sure if it's released yet though. In the meantime, you can check out the new built-in settings sync on VS Code Insiders. Make sure to set the ”sync.ignoreSettings" (or something like that) to "vscode-neovim.neovimPath" and "vscode-neovim.useWSL"
