### ISSUE TITLE
cursor is in the wrong place in tab-indent file

### ISSUE THREAD

**Issue by vzex** [asvetliakov/vscode-neovim#239]
1. 4-space-indent file,ujhk move cursor right.
2. after change all space to tab,ujhk movement is chaos,can't reach the head of line with ^ or h,can't search the right words under the cursor, etc...

**Comment by snakesgun** [comment]
This plugin is really a good plugin that implement vim using experiment on vscode.
However, I found same problem like @vzex described.

vscode version information is

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Plugin Version is 0.0.50
