### ISSUE TITLE
Must map to `:Tabnext<CR>` instead of `:tabnext<CR>`

### ISSUE THREAD

**Issue by slavistan** [asvetliakov/vscode-neovim#241]
Mapping to `:tabnext<CR>` or `:tabprev<CR>` does not work and has to be achieved by mapping explicitly to `:Tabnext<CR>` and `:Tabprev<CR>`, respectively. As suggested by the code in *vim/vscode-tab-commands.vim* the `:tab...` --> `:Tab...` mapping is supposed to work which is why I assume this to be a bug.

To switch between tabs in vscode using Tab/Shift-Tab in normal-mode the correct mapping is
```
nnoremap <Tab> :Tabnext<CR>
nnoremap <S-Tab> :Tabprev<CR>
```
while `nnoremap <Tab> :tabnext<CR>` **will not work**. Certainly nothing major but it took me some time to find out :-)

**Comment by ChristianChiarulli** [comment]
I actually had to use 

```
nmap <Tab> :Tabnext<CR>
nmap <S-Tab> :Tabprev<CR>
```

**Comment by asvetliakov** [comment]
We actually can't use vim's tab/window/buffer management, and vim doesn't allow to replace builtin lowercased commands. So that's why `:Tabnext` exists and you must bind your custom keys to it instead. But i agree there should be better statement in readme about it
