### ISSUE TITLE
Holding direction keys won't repeat movement

### ISSUE THREAD

**Issue by davidc360** [asvetliakov/vscode-neovim#242]
In regular VIM, holding h,j,k,l will move cursor until key is released. In the current port it only fires once.

**Comment by asvetliakov** [comment]
It's something with your configuration

**Comment by davidc360** [comment]
Nvm, found this in the other VIM extension (the popular one) docs and it worked:

> Mac
To enable key-repeating execute the following in your Terminal and restart VS Code:

```
$ defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code
$ defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider
$ defaults delete -g ApplePressAndHoldEnabled                                      # If necessary, reset global default

```

**Comment by dlejay** [comment]
I think all macOS users will experience the same issue. It could be a nice addition to the `Readme`.
