### ISSUE TITLE
Selection in one tab overlaps with other tabs

### ISSUE THREAD

**Issue by ShadyAlfred** [asvetliakov/vscode-neovim#244]
When I do a visual selection in one tab, then switch to another tab (without closing my visual selection) it seems that it considers it the same tab and continues to highlight stuff.

https://gfycat.com/wangoodelephant

**Comment by sdhull** [comment]
I can confirm this behavior

**Comment by asvetliakov** [comment]
it doesn't exit visual mode, so it uses original cursor pos of visual mode as start and current window cursor as end. `gt/gT` keys don't suffer this problem

**Comment by asvetliakov** [comment]
Fixed by #499
