### ISSUE TITLE
Support for Visual studio online

### ISSUE THREAD

**Issue by hholst80** [asvetliakov/vscode-neovim#246]
I just tried to install the neovim plugin on vsonline and I got the following error message:

> Cannot install 'Neo Vim' because this extension has defined that it cannot run on the remote server.

**Comment by asvetliakov** [comment]
Related #262

**Comment by hholst80** [comment]
I think they are identical issues. You could close this one as a duplicate in favor of #262 as it seems it has more comments and interactions to it than this issue.

**Comment by theol0403** [comment]
Duplicate of #262 👍
