### ISSUE TITLE
"VIM Command line" is blocking most of vscode/nvim compatibility.

### ISSUE THREAD

**Issue by yassinebridi** [asvetliakov/vscode-neovim#248]
Whenever i try to map something complex i always find a problem,
which is probably caused by the "VIM Command line" window.
for example if i wanted to map this easy operation:
```
nnoremap <leader>w :w<cr>
```
(I know that there is an equivilent for that in vscode-neovim, bu this is just a simple example)
it will work if i you support the simple command prompt `:` that nvim/vim does.
like the VsCodeVim extension does.
but i can't, since the prompted window doesn't recognize `<cr>`.

I might be wrong since i don't know if there is some limitations.

**Comment by David-Else** [comment]
I have the following in my `init.vim` which is quite complex and seems to work fine in VSCode just pressing `:` (to enter command prompt mode) and entering `TC` (toggle case):
```
"words that should not be changed to title case
let s:TC_IGN_WORDS = [ 'and', 'or', 'but', 'nor', 'yet', 'so', 'for', 'a', 'an', 'the', 'in', 'to', 'of', 'at', 'by', 'up', 'for', 'off', 'on' ]

function! Tc_Word(word)
    if index(s:TC_IGN_WORDS, a:word) >= 0
        return a:word
    else
        return toupper(a:word[0]) . a:word[1:]
    endif
endfunction

command TC g/^#/s/\<\w\+\>/\u\0/|s/\<\w\+\>/\=Tc_Word(submatch(0))/g | noh
``

**Comment by Shatur95** [comment]
@yassinebridi, as workaround you can do `nnoremap <Leader>w <Cmd>w<cr>`.

**Comment by asvetliakov** [comment]
VIM command line works just fine. `:w` doesn't work because file/buffer management is performed by vscode and you should use `:Write` instead. 

Your example use case should be:
```vim
nnoremap <leader>w :Write<cr>
```

Also see  #241
