### ISSUE TITLE
Use ctrl+w in vscode rather than vim?

### ISSUE THREAD

**Issue by rightaway** [asvetliakov/vscode-neovim#257]
I was able to add the following to the keyboard shortcuts config since I never use any of the `ctrl+w` functions in vim. This would make `ctrl+w` do the default vscode action of closing the current tab in the vscode vim extension I was using earlier. What could I add to my vscode keyboard shortcuts or vim config file to enable the same with this extension?

```
{
  "key": "ctrl+w",
  "command": "-extension.vim_ctrl+w",
  "when": "editorTextFocus && vim.active && vim.use<C-w> && !inDebugRepl"
},
```

**Comment by rightaway** [comment]
Same with `ctrl+h` for opening the find/replace dialog

```
{
  "key": "ctrl+h",
  "command": "-extension.vim_ctrl+h",
  "when": "editorTextFocus && vim.active && vim.use<C-h> && !inDebugRepl"
},
```

**Comment by maxild** [comment]
I know this is not (exactly) what you are asking, but `ctrl+w,q` [closes](https://github.com/asvetliakov/vscode-neovim/blob/master/vim/vscode-window-commands.vim#L50-L51) the active editor.

**Comment by dcervenkov** [comment]
Give the following a try. Notice the `ctrlKeysNormal` - depending on what you use, you might want to change this.
```
{
    "key": "ctrl+w",
    "command": "-vscode-neovim.ctrl-w",
    "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init"
}
```

**Comment by asvetliakov** [comment]
[Readme](https://github.com/asvetliakov/vscode-neovim#to-disable-existing-ctrl-key-sequence-for-example-ctrla-add-to-your-keybindingsjson)
