### ISSUE TITLE
Navigate softwrapped lines

### ISSUE THREAD

**Issue by lgsmith** [asvetliakov/vscode-neovim#259]
Hello,

I use vscode for editing LaTex, so I need to be able to navigate softwrapped lines. I have the noremap block in my .vimrc setup to navigate softwrapped lines using j->gj and so forth, but for some reason it doesn't seem to work when editing via the VSCode plugin. Pressing gj does work as expected. Perhaps I'm missing something obvious, but any pointers would be helpful.

Thanks.

**Comment by lgsmith** [comment]
Does the instance of neovim started to provide neovim support to vscode through this plugin look at a different init.vim than the one started from the terminal? Because my nvim terminal instances also handle softwrapping correctly.

**Comment by ArborealAnole** [comment]
Did you set `Vscode-neovim: Neovim Init Path` to `~/.config/nvim/init.vim`? See https://github.com/asvetliakov/vscode-neovim/issues/58#issuecomment-630551787.

**Comment by lgsmith** [comment]
Yes. And I've also tried to set it to read my .vimrc. Reading the init.vim in config is being done correctly by neovim when I open a .tex file with a very long softwrapped line, as far as I can tell.

**Comment by ArborealAnole** [comment]
I enabled word wrapping to viewport width and `j` and `k` access wrapped lines for me. Also they skip the folded lines. Did you use `noremap j gj` etc. rather than the `nmap j gj` etc. that take advantage of these maps? See https://stackoverflow.com/questions/3776117/what-is-the-difference-between-the-remap-noremap-nnoremap-and-vnoremap-mapping.
https://github.com/asvetliakov/vscode-neovim/blob/68f056b4c9cb6b2559baa917f8c02166abd86f11/vim/vscode-code-actions.vim#L93-L95

I am not sure if you need `noremap` for regular `nvim` so maybe use `exists('g:vscode')`.

**Comment by lgsmith** [comment]
As far as I know, I'm using nnoremap in my vimrc, and it is working OK in the terminal tool. Perhaps it'd be helpful to see the relevant files?

Here's what I've got in my `~/.vimrc` (that seems relevant to this issue):
```
" linewrapping junk
set wrap
set linebreak
set nolist 
" keeps vim from inserting newlines in freshly entered text
set textwidth=0
set wrapmargin=0
" key bindings to move along visually displayed lines as with a fancy text
" editor
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk
" end linewrapping junk
```
Here's what I've got in my `init.vim` that is in `~/.config/nvim/init.vim`:
```
et runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```
And here's what I've got in my `settings.json`
```
"vscode-neovim.neovimPath": "/usr/local/bin/nvim",
    "vscode-neovim.neovimInitPath": "/home/louis/.config/nvim/init.vim",
    "vscode-neovim.mouseSelectionStartVisualMode": true,
    "vscode-neovim.highlightGroups.ignoreHighlights": [

        "SpecialKey",
        "EndOfBuffer",
        "TermCursor",
        "TermCursorNC",
        "NonText",
        "ErrorMsg",
        "MoreMsg",
        "ModeMsg",
        "LineNr",
        "CursorLineNr",
        "Question",
        "StatusLine",
        "StatusLineNC",
        "VertSplit",
        "Title",
        "VisualNC",
        "WarningMsg",
        "WildMenu",
        "^Diff",
        "Sign",
        "SignColumn",
        "^Spell",
        "^Pmenu",
        "^Tab",
        "^Cursor",
        "ColorColumn",
        "QuickFixLine",
        "Whitespace",
        "NormalNC",
        "Normal",
        "NormalFloat",
        "MsgSeparator",
        "MsgArea",
        "^RedrawDebug",
        "Cursor",
        "lCursor",
        "MatchParen",
        "^Nvim",
        "Operator",
        "Delimiter",
        "Identifier",
        "SpecialChar",
        "Number",
        "Type",
        "String",
        "Error",
        "Comment",
        "Constant",
        "Special",
        "Statement",
        "PreProc",
        "Underlined",
        "Ignore",
        "Todo",
        "Character",
        "Boolean",
        "Float",
        "Function",
        "Conditional",
        "Repeat",
        "Label",
        "Keyword",
        "Exception",
        "Include",
        "Define",
        "Macro",
        "PreCondit",
        "StorageClass",
        "Structure",
        "Typedef",
        "Tag",
        "SpecialComment",
        "Debug",
        "Folded",
        "FoldColumn"
    ],
    "vscode-neovim.highlightGroups.unknownHighlight": {
    
    },
```

**Comment by ArborealAnole** [comment]
What I mean is, in `~/.vimrc` change
```
nnoremap j gj
nnoremap k gk
```
to
```
if exists('g:vscode')
  nmap j gj
  nmap k gk
else
  nnoremap j gj
  nnoremap k gk
endif
```
and so on for the other modes---unless you don't specifically need `nnoremap` for regular `vim`/`nvim`. This should make it work for you in vscode because you would use recursive map to call `VSCodeCall`. Make sure you reload the extension.

I assume the `source` will work with this extension but if this fix doesn't work I would recommend putting these commands directly into `init.vim` and seeing what happens.

**Comment by lgsmith** [comment]
OK that did the trick. I don't think I understood what you meant in your post above, because it looked like the vscode call lines you showed above were using nnoremap. This is resolved now. Thanks for the help.

**Comment by ArborealAnole** [comment]
Yeah, they are not recursively mapped themselves (I don't know why this matters) but you can still recursively map to them.

**Comment by sisrfeng** [comment]
>  nnoremap gk :<C-u>call VSCodeCall('cursorMove', { 'to': 'up', 'by': 'wrappedLine', 'value': v:count ? v:count : 1 })<CR> 
>  nnoremap gj :<C-u>call VSCodeCall('cursorMove', { 'to': 'down', 'by': 'wrappedLine', 'value': v:count ? v:count : 1 })<CR>

This does not work, and this works:
```
if exists('g:vscode')
  nmap j gj
  nmap k gk
else
  nnoremap j gj
  nnoremap k gk
endif
```

**Comment by aurangzaib-danial** [comment]
> What I mean is, in `~/.vimrc` change
> 
> ```
> nnoremap j gj
> nnoremap k gk
> ```
> 
> to
> 
> ```
> if exists('g:vscode')
>   nmap j gj
>   nmap k gk
> else
>   nnoremap j gj
>   nnoremap k gk
> endif
> ```
> 
> and so on for the other modes---unless you don't specifically need `nnoremap` for regular `vim`/`nvim` (in which case just change `*noremap` to `*map` etc.). This should make it work for you in vscode because you would use recursive map to call `VSCodeCall`. Make sure you reload the extension.
> 
> I assume the `source` will work with this extension but if this fix doesn't work I would recommend putting these commands directly into `init.vim` and seeing what happens.

I'm to navigate between wrapped lines in normal mode with this solution but I'm unable to do in the visual mode. Can you please tell me if there is any solution to that as well? I tried following but it didn't work.
```
if exists('g:vscode')
  nmap j gj
  nmap k gk
  vmap j gj
  vmap k gk
else
  ...
endif
```

**Comment by gaoqiangks** [comment]
```vim.keymap.set({"n"}, "j", "gj", {desc = "向下移动" })``` doesn't work, but  ```vim.api.nvim_exec2("nmap j gj", {output=false})``` works well. That's weird.

**Comment by marcelocra** [comment]
Found another solution that also works, which is to add `remap = true` to the options in Lua:

```lua
do
  local opts = { desc = "Move by display line", silent = true, remap = true }
  vim.keymap.set({ "n", "v" }, "j", "gj", opts)
  vim.keymap.set({ "n", "v" }, "k", "gk", opts)
  vim.keymap.set({ "n", "v" }, "$", "g$", opts)
  vim.keymap.set({ "n", "v" }, "0", "g0", opts)
end
```
