### ISSUE TITLE
bug: random characters like 'j','k' appear when (fast) switching modes (ESC)

### ISSUE THREAD

**Issue by alexdroste** [asvetliakov/vscode-neovim#261]
Unfortunately, 1/3 times I switch back from insert-mode nvim/vscode appear to get somehow out of sync.

e.g.:
_Expected:_
`insert-mode` -> `ESC` -> `normal-mode` -> `j` 
_Somewhat observed:_
`insert-mode` -> `ESC` -> `j` -> `normal-mode` 

I am indeed in normal mode, but the 'j' typed after hitting ESC is sometimes still inserted into the document, leaving the vscode-editor and nvim-buffer in a somewhat unsynced broken state, because the 'j' is inserted into the vscode editor but is afterwards **not** selectable by moving the cursor. And if I use a command like `x` to delete the last character, the last selected character and the 'j' get deleted.

![bug](https://user-images.githubusercontent.com/18649298/81535121-8591de80-9369-11ea-8501-0afee5f1cf59.gif)

**Comment by bheadwhite** [comment]
I also have this issue

**Comment by asvetliakov** [comment]
Dup of #324 . Fixed by #326
