### ISSUE TITLE
Live share support

### ISSUE THREAD

**Issue by lourenci** [asvetliakov/vscode-neovim#265]
Is that on the roadmap?

**Comment by asvetliakov** [comment]
What do you mean here ? Enable vim keybindings for remote party ?

**Comment by theol0403** [comment]
If this extension is installed, you should be able to use the vim bindings on your local editor, either when sharing or joining. However, anyone joining would need to install it on their own vscode instance for them to also use the bindings.

Feel free to comment if this in not the case or there is something else that is preventing this from working.
