### ISSUE TITLE
Load neovim without any plugins (`--noplugin`)

### ISSUE THREAD

**Issue by MaxGyver83** [asvetliakov/vscode-neovim#271]
How can I load neovim without plugins?

I have tried this:

```json
{
  "vscode-neovim.neovimPath": "/home/max/install/nvim.appimage --noplugin",
}
```

But then _vscode-neovim_ doesn't load at all.

And I have tried this in my `~/.config/nvim/init.vim`:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
if exists('g:vscode')
    set runtimepath-=~/.vim/pack/plugins/start/vim-vinegar
    set runtimepath-=~/.vim/pack/plugins/start/vim-buftabline
    set runtimepath-=~/.vim/pack/plugins/start/jedi-vim
...
endif
let &packpath = &runtimepath
source ~/.vimrc
```

→ The plugins still get loaded.

**Comment by MaxGyver83** [comment]
Meanwhile I have created a config file only for VS Code, `~/.config/nvim/.vscode-neovim-init.vim`, which doesn't add the whole vim directory to `runtimepath`. So I can add all plugins I need explicitly:

```vim
set runtimepath+=~/.vim/pack/plugins/start/vim-commentary,~/.vim/pack/plugins/start/vim-surround,~/.vim/pack/plugins/start/vim-sneak

set ignorecase       " make search case-insensitive by default (word\C → case sens.)
set smartcase        " make search case-sensitive if word contains uppercase letter
set incsearch        " search as characters are entered
...
```

**Comment by likern** [comment]
> Meanwhile I have created a config file only for VS Code, `~/.config/nvim/.vscode-neovim-init.vim`, which doesn't add the whole vim directory to `runtimepath`. So I can add all plugins I need explicitly:
> 
> ```viml
> set runtimepath+=~/.vim/pack/plugins/start/vim-commentary,~/.vim/pack/plugins/start/vim-surround,~/.vim/pack/plugins/start/vim-sneak
> 
> set ignorecase       " make search case-insensitive by default (word\C → case sens.)
> set smartcase        " make search case-sensitive if word contains uppercase letter
> set incsearch        " search as characters are entered
> ...
> ```

@MaxGyver83  Does `vim-sneak` worked for you? I see it in your example. This comment states `vim-sneak` is not supported https://github.com/asvetliakov/vscode-neovim/issues/204#issuecomment-592078068. Can you provide your settings related to `vim-sneak`?

**Comment by likern** [comment]
Looks like `vim-sneak` worked for me, after I delete `vim-sandwich` plugin. But I moved to `vim-easymotion` as a more superior solution.
