### ISSUE TITLE
How to use key remapping on VSCode

### ISSUE THREAD

**Issue by pedroapfilho** [asvetliakov/vscode-neovim#272]
On the extension `VSCodeVim` I could add a custom remapping, like:

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["J"],
      "after": ["5", "j"]
    },
    {
      "before": ["K"],
      "after": ["5", "k"]
    }
  ],
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["J"],
      "after": ["5", "j"]
    },
    {
      "before": ["K"],
      "after": ["5", "k"]
    }
  ],
```

How could I do it with this `VSCodeNeovim`?

**Comment by lgsmith** [comment]
In my experience with this, you would go through the process of adding these remappings to your init.vim, or your .vimrc (if you are having neovim source that). There are a few closed issues on how to do that for other key remapping questions, for example issue https://github.com/asvetliakov/vscode-neovim/issues/259 .
