### ISSUE TITLE
using ctrl+N/P for autocomplete

### ISSUE THREAD

**Issue by MaxAbrahams** [asvetliakov/vscode-neovim#273]
this works fine in nvim (obviously)
![image](https://user-images.githubusercontent.com/11665665/83040667-82efe400-a00d-11ea-87f9-6a155765ecbf.png)

but despite messing with keyboard mappings and other settings, googling, and banging my head against a wall... i can't get it to work in vscode. any pointers?

**Comment by asvetliakov** [comment]
`<C-n>/<C-p>` should be enabled by default for completions, in case if it's not these vscode keybindings should do the trick:

```json
            {
                "key": "ctrl+n",
                "command": "selectNextSuggestion",
                "when": "textInputFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
            },
            {
                "key": "ctrl+p",
                "command": "selectPrevSuggestion",
                "when": "textInputFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
            }
```

**Comment by MaxAbrahams** [comment]
sorry, i definiately was too vague. The autocomplete menu doesn't activate, ever. But i switched to a (crappier) vscode autocomplete tool and things are... fine.
