### ISSUE TITLE
How do you install the easymotion plugin on a wsl installation?

### ISSUE THREAD

**Issue by mendeljacks** [asvetliakov/vscode-neovim#282]
The instructions were "Just add my fork to your vim-plug block or by using your favorite vim plugin installer and delete original vim-easymotion. "

But I'm not sure if the vim-plug block can be accessed from the extension settings in vs code or if I have to install to the wsl vim instance somehow?

**Comment by asvetliakov** [comment]
If you're using wsl then you should have already neovim installed in WSL. Just do `:e $MYVIMRC` from wsl neovim, add plug blocks here followed by `:PlugInstall`, then reload vscode/source init.vim and you should be good to go.
