### ISSUE TITLE
[help] sth about key mapping

### ISSUE THREAD

**Issue by Cathsyron** [asvetliakov/vscode-neovim#285]
i changed the key mapping when i use ordinary neovim:**Esc/CapsLock** and **L-Ctrl/L-Alt**.

Capslock is out of order when i want to quit to normal-mode,so i must use Esc.
The Esc has been changed to CapsLock before. And when i  use it, it will have both CapsLock and Esc functions while capslock itself doesn't work.

the settings.json:
![image](https://user-images.githubusercontent.com/31385989/84511838-b616c080-acf9-11ea-8492-7e71fcadf91f.png)

Ps:If you feel bad about my grammar, you can also correct it. I'm still a novice.

**Comment by asvetliakov** [comment]
vscode doesn't allow such bindings. i guess you can remap them in system level

**Comment by doublethinkio** [comment]
#124
