### ISSUE TITLE
Feature request: Ctrl-x in insert mode

### ISSUE THREAD

**Issue by benjie** [asvetliakov/vscode-neovim#286]
In particular I'd like `<Ctrl-x><Ctrl-l>` line completion.

**Comment by asvetliakov** [comment]
Probably this can be supported due to insert mode is being handled by vscode. `<C-x><C-l>` line completion is a candidate for some another vscode extension

**Comment by theol0403** [comment]
Yeah, you could try to map insert-mode C-x bindings to native vscode commands and completion in vscode, I don't think this plugin can/should support vim completions.

**Comment by i5513** [comment]
> Probably this can't be supported due to insert mode is being handled by vscode. `<C-x><C-l>` line completion is a candidate for some another vscode extension

It should be configurable (use vim at insert mode ? yes / no)

vim standard vscode plugin works at insert mode. This issue stop me from use this plugin, switching back

Any way, thanks !

PD: command line should appear at the bottom (like vim standard vscode plugin)

**Comment by sisrfeng** [comment]
I think auto complete does not need a shortcut, because vscode provide good completion whenever we type.
