### ISSUE TITLE
Unable to get it to work. Stuck in limbo, cursor won't move, can't switch to insert, no nvim statusbar, etc

### ISSUE THREAD

**Issue by sangeet** [asvetliakov/vscode-neovim#287]
So, I tried this out on an Ubuntu computer earlier and worked well. Then I swtiched to my main computer and tried installing this plugin on a completely new install of VSCode (using vscode for the first time) and it just wouldn't work.

Note that this is a clean install with nothing added to it except this extension. The one working on Ubuntu server is the same but works.

Here's extensions `settings.json` : 

```json
{
    "vscode-neovim.neovimPath": "/bin/nvim/",
    "vscode-neovim.mouseSelectionStartVisualMode": true,
    "vscode-neovim.highlightGroups.unknownHighlight": {
    
    }
}
```

Neovim version : 

```
 I  ~/.c/nvim  /bin/nvim --version | head -n 1                                                                   ✔
NVIM v0.4.3
```

VSCode version : 

```
 I  ~  code -v                                                                                                   ✔
1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64
```

I'm completely new to vscode, so am unsure what's wrong (if anything). Let me know how can I proceed fixing the same.

Thanks

**Comment by theol0403** [comment]
It might have something to do with your `init.vim` on your main computer. Try commenting everything out to see if it is interfering with vscode neovim.

**Comment by sangeet** [comment]
Hi,

I actually tried that as well. Ensured that `init.vim` is empty but that doesn't seem to help. It's an empty file currently as we speak.
Is there any way to debug it? There are no error messages in VSCode and hence it's hard to get a sense of where is the point of failure.

**Comment by David-Else** [comment]
It seems ` "vscode-neovim......"` has no error checking, so I would confirm it is actually loading first. On my Linux system this works:

```json
  "vscode-neovim.neovimInitPath": "/home/USERNAME/.config/nvim/init.vim",
  "vscode-neovim.neovimPath": "/home/USERNAME/bin/nvim",
```

`init.vim`
```
if exists('g:vscode')
    "for use in vs code extension

    "call VSCodeCommentary on the visual selection, and then re-select that visual selection with gv
    xmap <C-/> <Plug>VSCodeCommentarygv
    nmap <C-/> <Plug>VSCodeCommentaryLine

    "disable recording
    nnoremap q <Nop>

    "stop cursor keys in normal mode
    "noremap <Up> <Nop>
    "noremap <Down> <Nop>
    "noremap <Left> <Nop>
    "noremap <Right> <Nop>

else
   
   "neovim settings when vs code extension not running

endif
```

**Comment by sangeet** [comment]
I'm really not sure what changed, but I disabled the extension again, threw in my older `init.vim` file back at it and it just worked.
So, while I have no idea what was wrong and what changed now. it's not a problem anymore. I'm closing this for now. Will re-open in case it failed again.

Thanks much for helping. :)
