### ISSUE TITLE
In navigate mode, random cursor motion 

### ISSUE THREAD

**Issue by lgsmith** [asvetliakov/vscode-neovim#289]
Hello,

I've been having issues with navigation mode, especially for softwrapped paragraphs. I've made changes to my .vimrc (which I source) per #259 so that I can do that. Nav-mode (especially gk/gj) seems to randomly displace my cursor, and gets it caught in weird cycles; for example trying to go down a softwrapped line can result in going down several lines, then cycling back to the top of the paragraph before getting to the softwrapped line to-be-edited. Clicking will insert the cursor in a random spot somewhere in the document, often selecting a large swath of random text in the process. Interestingly, none of this happens in insert mode. It seems to go away sometimes if I close then reopen the entire program. It somehow seems related to whether I've clicked onto a tab in the editor view panel, clicked away (to some other tab) then clicked back to that tab. If I do that, it often makes these issues go away.

Obviously I really want to get this sorted, but I'm not sure what other info would be helpful for troubleshooting. I'm happy to provide whatever information is deemed necessary.

Thanks for the great plugin.

**Comment by Shatur95** [comment]
I can reproduce this even with clear vimrc without plugins. `gj` displaces cursor position on softwrapped lines.

**Comment by Shatur95** [comment]
The issue does not exists in #307.

**Comment by lgsmith** [comment]
Are you saying PR #307  somehow fixed this issue as well? 

I wasn't getting this to happen consistently. Sometimes closing a window and reopening it would 'fix' it, or change the way in which it was working (like, if you were scrolling down through softwrapped text, it could sometimes change where the cursor got bounced back to if it got stuck in a loop). It always seemed to resurface at inconvenient times, though.

**Comment by Shatur95** [comment]
Yes. But I'm not sure that this fixed exactly be the PR (maybe it works on `master` branch too).

**Comment by toancaro** [comment]
I get this issue when the active file in VSCode has some fold regions. If I epand all folded regions, the editor works well.

**Comment by marconi** [comment]
> I get this issue when the active file in VSCode has some fold regions. If I epand all folded regions, the editor works well.

Same here, it suddenly started happening yesterday! :/
