### ISSUE TITLE
Make Yank etc. copy to clipboard

### ISSUE THREAD

**Issue by RAbraham** [asvetliakov/vscode-neovim#298]
Hi,
When I do yank in VS Code, it would be nice to copy it to the clipboard. If I directly use neovim on the command line, yank does copy it to the clipboard as I have the following setting.

```
set clipboard+=unnamedplus
```
In the vscode-neovim setting, I'm pointing it to the `init.vm` which has the above setting.

Is there some setting I'm missing? Please let me know.

**Comment by davidmathers** [comment]
I just set my clipboard to unnamedplus and it worked as expected. Try `:set clipboard?` to make sure yours is set correctly.

**Comment by c3-pennsu** [comment]
Seems to work for me once I add that line as well. However be aware of the files you put in, ~/.vimrc or ~/.nvimrc doesn't work anymore it has to be ~/.config/nvim/init.vim

**Comment by massaynus** [comment]
in yout init.vim you can add
```
set clipboard=unnamedplus
```

it worked perfectly for me after this

**Comment by mcrors** [comment]
Just to let you know, I was having this same issue. Thanks to @David-Else 's comment, I realized that I didn't have xclip installed. After installing this and restarting vscode, yanking to the system clipboard worked for me.

**Comment by choznerol** [comment]
> ... it has to be ~/.config/nvim/init.vim

also, for Neovim user using `init.lua` instead of `init.vim`, the Lua equvilent to that Vim script is:

```lua
-- In your ~/.config/nvim/init.lua
if vim.g.vscode then
    -- https://github.com/vscode-neovim/vscode-neovim/issues/298
    vim.opt.clipboard:append("unnamedplus")end
end
```

You can verify its effect in VSCode via `:set clipboard?`:

> ![image](https://github.com/vscode-neovim/vscode-neovim/assets/12410942/7244ee35-5300-427b-9e70-72142c465ce5)

... and check the output in bottom status bar:
> ![image](https://github.com/vscode-neovim/vscode-neovim/assets/12410942/01230c67-ff15-4064-bd15-209b8a84918e)

**Comment by abid-mujtaba** [comment]
If you are using WSL but are **not** using X, you can still use `clip.exe` to get yanked text into the Windows side system clipboard.

1. Make sure the DISPLAY env var is set
2. Create an executable `/usr/local/bin/xclip` and populate it with:

    ```bash
    #!/usr/bin/env bash
    clip.exe
    ```

And then append "unnamedplus" to the nvim clipboard as discussed above.

**Comment by shelper** [comment]
> ```shell
> #!/usr/bin/env bash
> clip.exe
> ```

but i already have xclip installed, how this gonna work then?
is there a way to set unnamedplus to this xclip which calls clip.exe when vscode is used?

**Comment by gaoqiangks** [comment]
> If you are using WSL but are **not** using X, you can still use `clip.exe` to get yanked text into the Windows side system clipboard.
> 
> 1. Make sure the DISPLAY env var is set
> 2. Create an executable `/usr/local/bin/xclip` and populate it with:
>    ```shell
>    #!/usr/bin/env bash
>    clip.exe
>    ```
> 
> And then append "unnamedplus" to the nvim clipboard as discussed above.

Could you be more specific?  What value should I assign to the var DISPLAY?

**Comment by willzhqiang** [comment]
It appears my configuration works on macOS and may be useful for your reference. With this config, you can decide when you need to copy contents to system's clipboard.
```shell
let mapleader = ","
" " Copy to clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
" We don't need the following line
" nnoremap  <leader>yy  "+yy

" " Paste from clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P
```
I don't remember where I copied it from.
