### ISSUE TITLE
gitgutter hunk-navigation-movements ]c [c dont work

### ISSUE THREAD

**Issue by astier** [asvetliakov/vscode-neovim#303]
Hallo. I would like to use the plugin gitgutter because of its hunk-navigation movements `[c` and `]c`. But they just don't work. Anybody got an idea what the issue might be?

**Comment by Shatur95** [comment]
I use the following:

```vim
nnoremap ]c <Cmd>call VSCodeNotify('workbench.action.editor.nextChange')<CR>
nnoremap [c <Cmd>call VSCodeNotify('workbench.action.editor.previousChange')<CR>
```

**Comment by astier** [comment]
Thank you.
