### ISSUE TITLE
Line desync on line deletions

### ISSUE THREAD

**Issue by Shatur95** [asvetliakov/vscode-neovim#312]
Sometimes I expected desync with `dd`.

**Steps to reproduce**

Tested on [this file](https://github.com/Shatur95/akd/blob/893cf5db597fba3565aad05c40f82164e41f719d/src/layout.cpp#L33) with clean config.

```vim
dd
gk
u
gk
dd
u
gj
dd
```

**Current behavior**

After the last `dd`, the line above the cursor will be deleted.

**Expected behavior**

After the last `dd`, the current line will be deleted.

**Comment by asvetliakov** [comment]
Not reproducible in refactor branch, so i guess this should be fixed
