### ISSUE TITLE
How to change completion list keybinding?

### ISSUE THREAD

**Issue by babygau** [asvetliakov/vscode-neovim#314]
At the moment, the default keybinding \<C-n>, \<C-p>, and \<Tab> are used for next, previous and enter. I'd want to change them to \<Tab>, \<S-Tab>, and \<CR> respectively. How could I achieve that?

**Comment by Shatur95** [comment]
This is not  related to the plugin, you can remap it in VSCode shortcuts.

**Comment by babygau** [comment]
@Shatur95 thank you!
