### ISSUE TITLE
remap `gt` and `gT` doesn't work on markdown files

### ISSUE THREAD

**Issue by babygau** [asvetliakov/vscode-neovim#315]
hi,
currently i'm using `<tab>` and `<s-tab>` instead of `gt` and `gT` to switch between tabs. however these rebinding keys have no effect on markdown files

```
" use <tab> and <s-tab> to switch between tabs
nmap <tab> gt
nmap <s-tab> gT
```

pls note that `gt` and `gT` work as expected.

**Comment by babygau** [comment]
@asvetliakov `"emmet.triggerExpansionOnTab": false` is set on default, `emmet` also exclude `markdown` as default. i also checked every keybindings related to `<tab>, <s-tab>`. i have no idea why this only happened to `markdown` file, other file types works as expected. moreover, `gt` and `gT` worked in `markdown`. i'm clueless if this is `neovim` bug or not.

**Comment by Shatur95** [comment]
Could you try `filetype plugin off` in your vimrc?

**Comment by babygau** [comment]
> Could you try `filetype plugin off` in your vimrc?

genius, it worked for me 👍 thank you @Shatur95

**Comment by Shatur95** [comment]
This option disables settings for specific file extensions. Most likely some plugin or your markdown settings were conflicting with this plugin. It is recommended to disable such stuff in VSCode.

**Comment by asvetliakov** [comment]
@Shatur95 nice catch

`filetype` is safe to use and can be useful to set per-type specific options/keys. Probably the markdown one, or some vim plugin overrides `<tab>/<s-tab>` bindings. Should be fixable by putting something like without disabling it:

`autocmd FileType markdown nmap <tab> gt`

See #115 

Also few vim plugins require filetype to work, see #114

**Comment by Shatur95** [comment]
> filetype is safe to use and can be useful to set per-type specific options/keys.

Of course! To be more clear: I recommended to disable Markdown specific settings or plugins that can conflict with VSCode Neovim plugin or just not needed in VSCode.

By the way, I have `filetype` disabled inside VSCode. But only because I am not using any file type specific settings in VSCode or plugins that need this feature.

**Comment by babygau** [comment]
> `autocmd FileType markdown nmap <tab> gt`
this doesn't fix the issue
