### ISSUE TITLE
Copying?

### ISSUE THREAD

**Issue by codic12** [asvetliakov/vscode-neovim#320]
In neovim, I have `<LEADER> y` (in my case `\y`) configured to copy text into the `+` register, and it works. However, it doesn't in VSCode with this plugin, nor does it with `\+y` 
:thinking: any ideas?

**Comment by asvetliakov** [comment]
Can you provide your exact keybinding in vim? Are you using WSL?

**Comment by codic12** [comment]
No, I'm on Linux. My keybinding in this case was configured by SpaceVim

**Comment by jdart** [comment]
Does `set clipboard=unnamedplus` help?

**Comment by codic12** [comment]
Ah yes, this does the trick; thanks!

**Comment by aesyondu** [comment]
> Does `set clipboard=unnamedplus` help?

Just for reference, based on this comment https://github.com/asvetliakov/vscode-neovim/issues/298#issuecomment-730634978, the directive should be placed in `~/.config/nvim/init.vim`, and I confirm it works.

```sh
mkdir -p ~/.config/nvim/
echo "set clipboard=unnamedplus" >> ~/.config/nvim/init.vim
```

macOS Catalina@10.15.7
NVIM@v0.5.0-dev+1122-g8f4b9b8b7
vscode@1.54.1
neovim@0.0.78
