### ISSUE TITLE
Statusbar continues to say --INSERT-- after leaving insert mode

### ISSUE THREAD

**Issue by David-Else** [asvetliakov/vscode-neovim#323]
In Neovim when you leave insert mode and go into normal mode then nothing is displayed on the status bar and the word `--INSERT--` is removed. In the extension, it keeps on saying `--INSERT--`. If you enter visual mode and leave it, then it correctly displays nothing.

v0.0.52 on Linux with Neovim 0.4.4

**Comment by asvetliakov** [comment]
Dup of #270
