### ISSUE TITLE
Specify in readme what config options should be disabled before using this extension

### ISSUE THREAD

**Issue by mkrptr** [asvetliakov/vscode-neovim#332]
I noticed that if I have `set relativenumber` in my vim config, the cursor acts strange in splits. It starts jumping two lines up/down when you press k/j instead of one and can completely freeze sometimes, but works fine if I disable this option and use built-in relative line numbers.
I'll also add that I did read the performance section of readme which says that relative line numbers might cause some lags, but that seemed like a different case, so I disregarded it initially. It doesn't really cause any jitters after all, but rather breaks cursor movements. I think it should be stated clearly in "Important" to remove that option from your config since it wasn't obvious for me that the cursor may be affected by it.

**Comment by asvetliakov** [comment]
New versions force critical options through autocmd event, so it doesn't matter that do you have in your init.vim:

https://github.com/asvetliakov/vscode-neovim/blob/8b978f46e9f1ff2561b18738bb95cad84a306bd6/vim/vscode-options.vim#L59-L77

However vim has much more options, so definitely something was missed here. In this cases PRs to update options are welcomed here

**Comment by awilkins** [comment]
Ahhh, this explains my bug

![image](https://user-images.githubusercontent.com/368399/93599963-df10b680-f9b6-11ea-8141-b21cd0af97a9.png)

All my search highlights are offset by the number of chars you need to render the numbered margin.

I had this set so that I get responsive hybrid numbering in terminal sessions.

```
set number relativenumber
autocmd InsertEnter * : set norelativenumber
autocmd InsertLeave * : set relativenumber
```

I've wrapped this section in `!exists('g:vscode')` and it's stopped happening.

**Comment by theol0403** [comment]
I'm going to close this issue, as there is a mention in the readme that you should not use vim line number, and this plugin mostly forces the config. 

If there is any vim config that breaks the plugin, and is not forced by the plugin, please open a new issue/pr.

However, #656 might interest you! It's smart relative numbers for vscode.
