### ISSUE TITLE
Visual mode send selected code to terminal

### ISSUE THREAD

**Issue by albert-ying** [asvetliakov/vscode-neovim#333]
Hi,

I just switch to VS-code from sublime. I use R and one common operation in my daily work is to select small crunk of code (not whole block) and hit cmd+enter to test run it in terminal/R. It works fine for neo-vim implementation in SM3, however, I can't do it in VS-code: it ignores my selection and sends the whole block.

I understand the selection in visual mode is not real selection, but still wondering is there any workaround for this so I don't need to use mouse ever time.

Thank you!

**Comment by albert-ying** [comment]
I added this to my init.vim, but doesn't work

function! s:openVSCodeCommandsInVisualMode()
    normal! gv
    let visualmode = visualmode()
    if visualmode == "V"
        let startLine = line("v")
        let endLine = line(".")
        call VSCodeNotifyRange("r.runSelection", startLine, endLine, 1)
    else
        let startPos = getpos("v")
        let endPos = getpos(".")
        call VSCodeNotifyRangePos("r.runSelection", startPos[1], endPos[1], startPos[2], endPos[2], 1)
    endif
endfunction

**Comment by albert-ying** [comment]
I found F1 did the job. However, it is still nicer if I can get the same behavior by hitting cmd+enter. Is there any easy way to do this? Simple change key bind seems not working...

**Comment by asvetliakov** [comment]
you need to pass `cmd-enter` key from vscode to neovim (by defining vscode keybinding - refer to readme how to do this). Then in neovim you can use `xnoremap` binding and call your function which triggers `VSCodeNotifyRange/Pos`
