### ISSUE TITLE
Visual mode and using VS Code commands

### ISSUE THREAD

**Issue by hffmnn** [asvetliakov/vscode-neovim#337]
The docs state, this:

> To round the corners, invoking VSCode command picker through the default hotkeys (f1/ctrl/cmd+shift+p) from visual mode converts vim selection to real vscode selection.

After selecting multiple lines in visual mode, I triggered the command picker (`cmd+shift+p`), and executed `Transform to Uppercase`. 
This is the result:

![Screenshot 2020-09-04 at 10 49 02](https://user-images.githubusercontent.com/352753/92220704-a80db180-ee9c-11ea-9528-d1958d540182.png)

Is there anything I misunderstood on how to apply this correctly? Anything I might have set up incorrectly?

**Comment by asvetliakov** [comment]
Try `F1`. For some reason included keybinding doesn't work on mac

**Comment by hffmnn** [comment]
Thanks a lot, that worked!
