### ISSUE TITLE
Buffer sync optimizations

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#34]

**Comment by asvetliakov** [comment]
Changes landed in b7d1b1d

Additional optimization may be performed by combining changes with neighbor ranges before sending to neovim

**Comment by Yukaii** [comment]
Find another issue that might be related: vim mode not work in new file (<kbd>Ctrl</kbd> + N), and after close that new tab, vim plugin stop working

**Comment by asvetliakov** [comment]
@Yukaii Can you provide full repro steps?

**Comment by Yukaii** [comment]
I can't reproduce this anymore 😅 I'll open a seperate issue if it happens again.
