### ISSUE TITLE
cursor  moving issue

### ISSUE THREAD

**Issue by jeffersonchen-tw** [asvetliakov/vscode-neovim#342]
When I pressed j,k it moved up or down 2 line. Beside, when I pressed h,l it stucked on several characters, since I had removed most my neovim plugins.

**Comment by asvetliakov** [comment]
Does it happen with `0.0.61` version ?

**Comment by atcol** [comment]
I don't know if this is the same issue, but using the latest version (0.0.61) on Windows and Remote SSH to a Linux box results in no cursor movement at all - I had to downgrade to 0.0.54.

**Comment by Shatur95** [comment]
@atcol, Can you check if the path to the Neovim executable file is correct?

**Comment by atcol** [comment]
It is for both Linux and Win32. As I implied: 0.0.54 is working.

**Comment by asvetliakov** [comment]
>I don't know if this is the same issue, but using the latest version (0.0.61) on Windows and Remote SSH to a Linux box results in no cursor movement at all - I had to downgrade to 0.0.54.

It looks like you have old neovim version. `neovim-0.5.0-nightly` is required now

**Comment by atcol** [comment]
Oof I didn't uprade because 0.4.x is the latest stable release. Is forcing people to nightly fair/safe?

**Comment by asvetliakov** [comment]
i wouldn't force people to upgrade to nightly version if it won't have been absolutely necessary. There was a popping in message for about 2 weeks starting from `0.0.52` release. Much enough time to upgrade in my opinion

**Comment by atcol** [comment]
Sure, but I presumed that'd mean a _stable_ release of Neo Vim. Nevermind.

**Comment by asvetliakov** [comment]
Unfortunately we can't wait another year for stable 0.5

**Comment by atcol** [comment]
Ok I'll upgrade and confirm it works with the latest version for me.

**Comment by jeffersonchen-tw** [comment]
> Does it happen with `0.0.61` version ? 

Yep! It's 0.0.61 version. 
BTW: Mine is Darwin machine with neovim 0.0.5

**Comment by confusingbits** [comment]
I had the same issue. Latest stable release on chocolatey was 4.4.

The command to upgrade on windows via choco: 

`choco upgrade neovim --pre `

**Comment by asvetliakov** [comment]
@jeffersonchen-tw do you have remapped `j` or `k` to `gj` or `gk` or using vscode's `cursorUp` / `cursorDown`? Can you enable logging and record a log somewhere and also record a video of an issue? It's hard to tell that's going on now.

@confusingbits 
Complains about pre-release version are here #353 . I'm not fan of using pre-release software byself, but please understand i didn't have any alternative. `Things were working before` statement is not really true here.

**Comment by jeffersonchen-tw** [comment]
> @jeffersonchen-tw do you have remapped `j` or `k` to `gj` or `gk` or using vscode's `cursorUp` / `cursorDown`? Can you enable logging and record a log somewhere and also record a video of an issue? It's hard to tell that's going on now.
> 
> 
> 
> @confusingbits 
> 
> Complains about pre-release version are here #353 . I'm not fan of using pre-release software byself, but please understand i didn't have any alternative. `Things were working before` statement is not really true here. 

I just rewrote my neovim config file, and it does trick. Everything is well done now.
