### ISSUE TITLE
Cursor move delay on change command

### ISSUE THREAD

**Issue by theol0403** [asvetliakov/vscode-neovim#344]
*Originally posted [here](https://github.com/asvetliakov/vscode-neovim/pull/334#issuecomment-687538718)*
> Sometimes, when I go into insert mode with something that modifies the buffer length (ie change commands) and start typing too fast, the cursor does not update fast enough and it inserts text in the wrong place. 
> For example, here I type `ciwadditional` but this happens:
> ![Peek 2020-09-04 20-14](https://user-images.githubusercontent.com/16546293/92296621-61937380-eeeb-11ea-929b-b596c611dd88.gif)
> I am on the latest commit of this branch.

This problem still happens with an empty init.vim and all vscode extensions disabled.
Here, you can see the first time it ignores the "j", and the second time it places "j" in the wrong spot after the cursor. I have slowed the gif down by 50%.

![ezgif-4-441c936d1ae6](https://user-images.githubusercontent.com/16546293/92334043-1db18300-f03f-11ea-8043-9cc442485cf9.gif)

Edit:
The more vscode plugins I have enabled, the worse the issue becomes. With all extensions disabled like above, the issue only happens 30% of the time, and usually with only one or two characters. With all extensions enabled, the issue becomes as bad as in the first screenshot.

**Comment by asvetliakov** [comment]
Something is listening for document on change event and delaying cursor update after ciw

**Comment by theol0403** [comment]
Just to make sure, I tried again by disabling all plugins (other than neovim), commenting out all settings and keymaps, and removing init.vim, but it does still happen.

**Comment by asvetliakov** [comment]
LSP server can possible kick in here. Just in case - does it happen in non C++ or small files without project context?

**Comment by theol0403** [comment]
Yes, after a few tries I was able to reproduce it in a one-line markdown file.
I did have all my plugins and init.vim enabled at the time, though most of them should not have been loaded due to the filetype, do you want me to try with everything disabled?

**Comment by asvetliakov** [comment]
If you don't mind 🤷‍♂️

**Comment by theol0403** [comment]
Reproduced in: disable all plugins -> comment all settings -> enable neovim plugin -> new window -> new untitled file

**Comment by asvetliakov** [comment]
it should work fast at least with untitled file. curious

Well, i have 2 possible solutions here. Won't mind to try both ? i'll compile two PRs soon

**Comment by theol0403** [comment]
Sure. I can easily compile myself as well if that saves you a step.
