### ISSUE TITLE
How to view :messages

### ISSUE THREAD

**Issue by HaleTom** [asvetliakov/vscode-neovim#347]
Issue "Make :messages work" #202 is now closed.

After typing `:messages`, where should I look to view them?

**Comment by asvetliakov** [comment]
multiline messages appear in vscode-neovim output channel:
![image](https://user-images.githubusercontent.com/8881674/92396564-7f4c1d00-f125-11ea-92d5-fa692378b349.png)

**Comment by HaleTom** [comment]
How do I enable / integrate this option?

![screenshot](https://i.imgur.com/2vxRCkK.png)

**Comment by Shatur95** [comment]
Should be available out of the box starting from 0.60.
