### ISSUE TITLE
"Z" key rebinding issue.

### ISSUE THREAD

**Issue by mbgl-git** [asvetliakov/vscode-neovim#348]
I have a custom binding for nvim and "Undo" is bound to "z" key, "Redo" to "Z", "z" key function is moved to "b". When I press "z" in vscode-neovim, editor waits for me to press another key and then makes "Undo" (same with "Z"). If I press "zz" it centers a screen, so "z" key function rebinding is not working.

My bindings for that in init.vim:
```
noremap b z
noremap <S-b> <S-z>
noremap z u
noremap <S-z> <C-r>
```

**Comment by asvetliakov** [comment]
Try to unmap `z` scrolling keybindings first:

https://github.com/asvetliakov/vscode-neovim/blob/6c248b6a915c2feac9346e0f612b626c20313ec5/vim/vscode-scrolling.vim#L8-L19

**Comment by mbgl-git** [comment]
Yep, it has worked. Thanks.
Hmm, so you also have vim configs in the plugin, interesting.
