### ISSUE TITLE
0.0.62 broken

### ISSUE THREAD

**Issue by chadkouse** [asvetliakov/vscode-neovim#355]
I can install 0.0.61 and it seems to work, but in 0.0.62 it's like the extension isn't even loading.

**Comment by asvetliakov** [comment]
There are no much changes between `0.0.61` and `0.0.62` and i don't see any of them that could lead to broken state. Can you enable logging in extension options and upload log somewhere?

**Comment by chadkouse** [comment]
Nevermind - in the process of trying to get debug logging enabled (I was ultimately unable to do that) - the extension started working :man_shrugging:

**Comment by asvetliakov** [comment]
Possible deadlock on startup ? Feel free to reopen if you encounter this again

**Comment by GetzMikalsen** [comment]
Same issue here, 0.0.62 broken, 0.0.61 works.
Using neovim 0.5 nightly and VSCode 1.49.0 on Windows 10 with WSL remote.
Will try producing a log later
