### ISSUE TITLE
H/M/L keys first move to head of a line before work

### ISSUE THREAD

**Issue by yorkz1994** [asvetliakov/vscode-neovim#367]
In the middle of one line, type shift-h or H, it will first go to line head like you type 0, then takes effect to go to the top.
M/L keys have similar behavior.

OS: win10
vscode: 1.48.2
neovim extension: v0.0.62
neovim: 0.5.0

**Comment by Shatur95** [comment]
BTW, this worked on 0.0.52.

**Comment by Shatur95** [comment]
Another interesting behavior: if you at the beginning of the line - this keys work.
