### ISSUE TITLE
On Startup, VSCode Throws "Unable to init vscode-neovim: command 'type' already exists" Error

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [asvetliakov/vscode-neovim#368]
On startup (Windows 10) I get the following message when trying to start up vscode-neovim for the first time
![image](https://user-images.githubusercontent.com/25948785/93545797-f6a05e80-f926-11ea-8c72-ac815e5a8ded.png)

**Context**
1. I installed the nvim nightly build and put it into C:\Users\dargo\AppData\Local\Programs\Neovim\bin
2. This is also where I set the target directory to in settings (picture below)
![image](https://user-images.githubusercontent.com/25948785/93545937-50088d80-f927-11ea-9200-663979be56aa.png)

Other than that, the installation is almost base vscode, with nothing but the base vim extension installed. 
- do I have to uninstall the vim extension to use this?

**Comment by v-iashin** [comment]
@ca-mantis-shrimp did you figure out what to do with the issue? Why did you close it?

**Comment by ca-mantis-shrimp** [comment]
I tried removing the normal vim plugin and it started working. Wasn't sure if I needed both extensions or just one.

Thanks for asking

**Comment by v-iashin** [comment]
OMG thanks! In the future, please do write how you worked around it. Someone like me would appreciate it.

**Comment by v-iashin** [comment]
@asvetliakov can we somehow reflect this in the doc/README? I am not sure if it is intuitive for all users.

**Comment by Shatur95** [comment]
@v-iashin, won't hurt. Could you send a PR to README that this plugin will conflict with other plugins that register `type` command, such as Vim extension or Overtype (see #380).
