### ISSUE TITLE
Recent files ui (Stock vscode Ctrl+R)

### ISSUE THREAD

**Issue by jdart** [asvetliakov/vscode-neovim#369]
I couldn't find a way to get the recent files dialog to open, so I removed the Ctrl-R keyboard shortcuts this plugin adds and now some strange things are happening. How can I restore those ctrl-r shortcuts? And is there a way to open the recent files ui? Thanks!

**Comment by Shatur95** [comment]
Just open `shortcuts.json` and find removed shortcuts. It will be with the minus sign.

**Comment by jdart** [comment]
I think I found them in `keybindings.json`. I ended up removing the default cmd+r mapping and assigning it to openRecent like below:

```json
    {
        "key": "cmd+r",
        "command": "-workbench.action.reloadWindow",
        "when": "isDevelopment"
    },
    {
        "key": "cmd+r",
        "command": "workbench.action.openRecent"
    },
    {
        "key": "ctrl+r",
        "command": "-workbench.action.openRecent"
    }
```
