### ISSUE TITLE
Can't input any letter

### ISSUE THREAD

**Issue by kdurant** [asvetliakov/vscode-neovim#37]
- [x] win10

Can't change mode and input any letter

**Comment by asvetliakov** [comment]
1) Did you configure path to neovim & restarted the editor?
2) try to create new untitled document and see if it works here
3) if you have any custom vim configuration - try to move it and see if it works without config

**Comment by kdurant** [comment]
1. set and restarted
```json
"vscode-neovim.neovimPath": "C:/Neovim/bin"
```
2. I create a new untitled document and it not works too.

3. I had remove my vim configuration

**Comment by asvetliakov** [comment]
You need to specify full path, e.g. "C:\Neovim\bin\nvim.exe"

**Comment by kdurant** [comment]
thanks

**Comment by muhajirdev** [comment]
I have similar problem with macOS, 

my path `  "vscode-neovim.neovimPath": "/usr/local/bin/nvim", `

still not working, what should I do?

**Comment by asvetliakov** [comment]
@muhajirdev 
Catalina? Installed from brew? Does it work outside of vscode? There is an upstream problem with brew nvim.

**Comment by dan-cooke** [comment]
@muhajirdev 
Same issue on macOs.

Installed neovim from source

Completely blocks any keyboard input - extension unusable

```
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

```

**Comment by asvetliakov** [comment]
@dan-cooke 
@muhajirdev 

Just tried, confirming that doesn't work on mac os. Will debug today

**Comment by asvetliakov** [comment]
Weird but it works if launched from extension debug

**Comment by asvetliakov** [comment]
The problem the *.vim files were packaged with crlf line-endings since i built on windows 😄 Sorry about that!

**Comment by asvetliakov** [comment]
deployed in v0.0.34
