### ISSUE TITLE
Easymotion incorrect jump to search

### ISSUE THREAD

**Issue by theol0403** [asvetliakov/vscode-neovim#372]
When using https://github.com/asvetliakov/vim-easymotion, and doing `<leader>/` for search, when I type the search then choose the target, it jumps to the first non-whitespace col in the line below the target instead of directly to the target.

![Peek 2020-09-20 11-04](https://user-images.githubusercontent.com/16546293/93718452-2d49c500-fb31-11ea-9d0f-43ce18da9ac5.gif)

**Comment by asvetliakov** [comment]
The problem here is the automatically accepting return prompt caused by easymotion. But for easymotion search it's "autoaccepted" already

**Comment by MarWeUMR** [comment]
Hi,
is it possible, that this bug is still persisting? I have the exact same problem that is showcased above.

**Comment by DominickVale** [comment]
I'm having the same issue as well.
