### ISSUE TITLE
NeoVim does not work in vscode 1.49

### ISSUE THREAD

**Issue by MrLukashem** [asvetliakov/vscode-neovim#375]
Hello,

I have an issue with neovim plugin in vscode.
Seems like NeoVim does not work at all and I can see such output:

![image](https://user-images.githubusercontent.com/9093345/93723495-32ddf400-fb9f-11ea-9229-ba93219de19a.png)

vscode version: 1.49
neovim on WSL: 0,5
neovimPlugin for vscode version: 0.62 and 0.61 does not work

Thank you in advance

**Comment by asvetliakov** [comment]
Check your neovim path in settings, try with empty init.vim

**Comment by DylanCulfogienis** [comment]
Tried with an empty path, getting the following on OSX:

<img width="467" alt="Screen Shot 2020-09-21 at 3 12 31 PM" src="https://user-images.githubusercontent.com/65580873/93811605-6ca20f80-fc1e-11ea-89d0-abaf3f0a0ff6.png">

**Comment by asvetliakov** [comment]
`ENOENT` means it can't find the requested path. Try with full path without  `~/` , e.g. `/Users/blah/.bin/...`

**Comment by MrLukashem** [comment]
I found the root cause of the issue.
I have two WSL distros: Ubuntu and Ubuntu-20.04. I am working on Ubuntu-20.04 but wsl.exe run Ubuntu by default. Ubuntu WSL does not have installed nvim.
I use wsl.exe -s Ubuntu-20.04 commend to set new default Linux distribution. Now it works fine because /usr/bin/nvim path exists in Ubuntu-20.04.

Thank you.
