### ISSUE TITLE
Conflicting behaviour with Overtype, and probably many others

### ISSUE THREAD

**Issue by GonziTaji** [asvetliakov/vscode-neovim#380]
Having the vscode extension [overtype](https://marketplace.visualstudio.com/items?itemName=adammaras.overtype) installed reproduces the same error as #368. 

With any othe case found about this error, I assumed the linked issue's resolution was to uninstall a vim extension, I have none installed, but had overtype. I disabled overtype, reloaded vscode and it worked fine

To some may be obvius that those two confict each other, but it would be nice to have a note in the readme about possible unexpected errors at startup with extensions that extend the editor, like overtype.

I could publish a pr in a couple of hours if that's allowed

Steps to reproduce:

* Install neo vim extension and set executable path
* Reload vscode, neo vim should work
* Install overtype, reload vscode
* Error is shown at neovim init.

**Comment by asvetliakov** [comment]
Nothing we can do here, vscode allows to register only single `type` command across all extensions

**Comment by ChaoXu1997** [comment]
I find nvim conflicts with the 'Indent To Bracket' extension

**Comment by awilkins** [comment]
Worth noting that the last release of vscode included  a native overtype mode ; perhaps this could remove some hackery from vscode-neovim as well as making Overtype obsolete.
