### ISSUE TITLE
error message re WSL - on linux

### ISSUE THREAD

**Issue by hholst80** [asvetliakov/vscode-neovim#381]
I got this error message but I am not sure how to fix it in a way that does not break my windows installation. I need to untick the "Use WSL" setting (vscode-neovim.useWSL) for it to work on Linux, but I need to tick it for it to work on Windows. This is a bit of a headache for me because I use cloud synchronization of my vscode settings.

    2020-09-21T21:27:28.189Z MainController: Neovim spawn error: spawn C:\Windows\system32\wsl.exe ENOENT

**Comment by asvetliakov** [comment]
I think we should just ignore `useWSL` flag on linux/mac
