### ISSUE TITLE
Cursor movement break jump stack of vscode

### ISSUE THREAD

**Issue by gngshn** [asvetliakov/vscode-neovim#384]
When I use j/k to move cursor in vim mode, then I use vs code Go Back(^- on Mac), cursor will back to the previous lines instead of the position where I use goto definition command.

**Comment by asvetliakov** [comment]
You need to use vim's jumplist `<C-o>/<C-i>/<Tab>` commands. They're not perfect and have bugs but vscode back/forward is not supported and won't be.
