### ISSUE TITLE
Navigate through previous commands on VIM Command Line

### ISSUE THREAD

**Issue by josecoelho** [asvetliakov/vscode-neovim#385]
I love how it opens the VIM Command-Line at the top when pressing `:`. It is far more readable than on the bottom status bar, at least in my opinion.

<img width="614" alt="Screen Shot 2020-09-24 at 9 59 32 AM" src="https://user-images.githubusercontent.com/1987013/94074126-c5ef8600-fe4c-11ea-872a-14a96b4d3008.png">

My only problem is that I'm used to navigating through previous commands by pressing up arrow/down arrow. This doesn't seem to be working on my version. Would this be a feature request or am I missing something?

I'm keen to contribute.

## Env
Neo Vim 0.0.62
Mac OS 10.15.16
VS Codium Version: 1.49.1

**Comment by asvetliakov** [comment]
VScode started to disallow to rebind up/down keybindings in quick edit. `Ctrl-n/Ctrl-p` navigates cmd history now. You can bind other keys too, except up/down. See #288
