### ISSUE TITLE
Unable to type into comment boxes when using GitHub PR extension

### ISSUE THREAD

**Issue by KidVizious** [asvetliakov/vscode-neovim#386]
When attempting to leave a pull request comment using the GitHub PR extension, the cursor jumps to the top of the file and prevents typing in the comment box.

## Steps to reproduce:
- Open a file from the GitHub PR extension.
- Click on one of the changed lines
- Click inside the comment box
- Start typing

## Expected Behavior
- Text is typed into the comment box

## Actual Behavior
- Cursor jumps to line 1 of the file

## Affected Versions
VSCode version 1.49.1
NeoVim extension version 0.0.63 (although this has been in the last several releases)

**Comment by asvetliakov** [comment]
I'm using github PR extension too and don't have such problem. Try with empty `init.vim` first

**Comment by ian-h-chamberlain** [comment]
I'm not sure if this is the same issue, but I have seen something similar using the Atlassian Bitbucket extension. I have been able to work around it by clicking in the file somewhere near the comment box, then the cursor jump is no longer an issue. I haven't done a ton of narrowing down to find the cause, but I will try and see if I can reproduce with empty `init.vim` etc.

**Comment by asvetliakov** [comment]
@KidVizious @ian-h-chamberlain  are you using side by side or inline diff editor?

**Comment by KidVizious** [comment]
I use the side by side diff editor.

**Comment by asvetliakov** [comment]
works for me with side-by-side too

**Comment by KidVizious** [comment]
I was previously not using a custom init.vim so I created an empty one and pointed the plugin to that file.  Same issue.

**Comment by Shatur95** [comment]
Could you also try to remove all plugins?

**Comment by KidVizious** [comment]
@Shatur95 Vim plugins? I'm not using any...just a vanilla neovim install.

**Comment by Shatur95** [comment]
Yes. Strange, we need to find the cause of the problem, because none of us can reproduce it...
Okay, maybe some VSCode settings causes the issue?

**Comment by ian-h-chamberlain** [comment]
I seem to see the issue when running in either side-by-side or unified diff mode, although unified exacerbates the problem since the cursor generally travels farther from the comment box.

I tried with empty `init.vim` and all extensions disabled except these:
```
redhat.vscode-yaml  asvetliakov.vscode-neovim atlassian.atlascode
```
(YAML extension is required by Atlassian extension)

The only seemingly related VSCode user or workspace settings I can find in my settings are:
```jsonc
{
    "diffEditor.ignoreTrimWhitespace": false,
    "diffEditor.renderSideBySide": true,
}
```
Although as I mentioned both values of `renderSideBySide` seem to have the same issue.

Some other environment info in case it is helpful:
Extension details:
```
Name: Neo Vim
Id: asvetliakov.vscode-neovim
Description: Real VIM in your Visual Studio Code
Version: 0.0.63
Publisher: Alexey Svetliakov
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim
```
neovim details:
```
$ nvim --version 
NVIM v0.5.0-nightly-81-gaa4557920
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200908-21341-1cp1gl/build/config -I/tmp/neovim-20200908-21341-1cp1gl/src -I/usr/local/include -I/tmp/neovim-20200908-21341-1cp1gl/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200908-21341-1cp1gl/build/src/nvim/auto -I/tmp/neovim-20200908-21341-1cp1gl/build/include
Compiled by ichamberlain@Ians-Macbook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-aa45579/share/nvim"

Run :checkhealth for more info
```
VSCode details:
```
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Let me know if there's anything else I can provide to help!

**Comment by asvetliakov** [comment]
I believe #461 fixes that
