### ISSUE TITLE
ctrl+v then shift + i, only selects one row not all

### ISSUE THREAD

**Issue by delolat** [asvetliakov/vscode-neovim#387]
steps:
1.ctrl + v arrows down or up to select rows
2.shift + i to enter edit mode

expected: insert into all rows

result: insert into only 1 row

**Comment by asvetliakov** [comment]
Your use case works for me. Although there is only single cursor visible, the text will be inserted into all rows you've selected before. That's 100% correct vim behavior

**Comment by delolat** [comment]
> Your use case works for me. Although there is only single cursor visible, the text will be inserted into all rows you've selected before. That's 100% correct vim behavior

Using Code OSS 1.48.2 on manjaro gnome distro. It's only inserting on the top row. 

Downloaded VSCode from AUR repository and same result. Only works in the vscode vim extension.

**Comment by asvetliakov** [comment]
try with empty `init.vim` if you have custom one

**Comment by Shatur95** [comment]
Tested, works for me too.

**Comment by delolat** [comment]
I found the issue. It appears to be something wrong in neovim-nightly build, so its not related to vscode =\. Thanks much!
