### ISSUE TITLE
Can't paste text from register / (Ctrl-r,/)

### ISSUE THREAD

**Issue by tynguyen2k1** [asvetliakov/vscode-neovim#388]
What is happening?
![Screenshot 2020-09-25 083813](https://user-images.githubusercontent.com/64082226/94216784-7e2f3400-ff0a-11ea-8d92-bca132ae2692.jpg)
 
my init.vim

    let mapleader = " "

    if exists('g:vscode')
        nnoremap <Leader>f <Cmd>call VSCodeNotify('editor.action.formatDocument')<CR>
        nnoremap <Leader>e <Cmd>call VSCodeNotify('workbench.action.toggleSidebarVisibility')<CR>
    else
    endif

    call plug#begin('~/.vim/plugged')

        Plug 'tpope/vim-surround'
        Plug 'tpope/vim-repeat'

        Plug 'asvetliakov/vim-easymotion'

    call plug#end()

    silent! call repeat#set("\<Plug>surround", v:count)

    let g:EasyMotion_do_mapping = 0 " Disable default mappings

    nmap <Leader>s <Plug>(easymotion-s2)
    nmap <Leader>t <Plug>(easymotion-t2)

    " Turn on case-insensitive feature
    let g:EasyMotion_smartcase = 1

    " JK motions: Line motions
    map <Leader>j <Plug>(easymotion-j)
    map <Leader>k <Plug>(easymotion-k)
    map <Leader>h <Plug>(easymotion-linebackward)
    map <Leader>l <Plug>(easymotion-lineforward)
    map <Leader>w <Plug>(easymotion-w)
    " map <Leader>e <Plug>(easymotion-iskeyword-e)
    map <Leader>b <Plug>(easymotion-iskeyword-b)

    " Gif config
    map  / <Plug>(easymotion-sn)
    omap / <Plug>(easymotion-tn)

    map  n <Plug>(easymotion-next)
    map  N <Plug>(easymotion-prev)

    " clipboard
    noremap <Leader>y "*y
    noremap <Leader>p "*p
    noremap <Leader>Y "+y
    noremap <Leader>P "+p

    xnoremap <Leader>y "*y
    xnoremap <Leader>p "*p
    xnoremap <Leader>Y "+y
    xnoremap <Leader>P "+p

    map <Leader>n :nohl<CR>

    " vim surround
    autocmd FileType php let b:surround_45 = "<?php \r ?>"

**Comment by asvetliakov** [comment]
That's not very informative issue description. What did you press, what happened, what should happen instead. Your init.vim content

**Comment by asvetliakov** [comment]
Sorry, i see now. There is no keybinding for pasting from register `/` in insert mode. And your screen is `:registers` message

**Comment by asvetliakov** [comment]
you can add this to your `keybindings.json` in meantime:

```json
            {
                "command": "vscode-neovim.paste-register",
                "key": "ctrl+r /",
                "when": "editorTextFocus && neovim.mode == insert && !neovim.recording && neovim.ctrlKeysInsert",
                "args": "/"
            }
```

**Comment by TyNguyen2k1** [comment]
> you can add this to your `keybindings.json` in meantime:
> 
> ```json
>             {
>                 "command": "vscode-neovim.paste-register",
>                 "key": "ctrl+r /",
>                 "when": "editorTextFocus && neovim.mode == insert && !neovim.recording && neovim.ctrlKeysInsert",
>                 "args": "/"
>             }
> ```

Thanks bro !!!

**Comment by asvetliakov** [comment]
Reopening to not forget to add missing keybinding by default

**Comment by rafaelpirolla** [comment]
I'm having another issue which is to use the unnamed " register in a keyboard layout that have the " key as a dead key.
That's a vscode problem actually and I could not find anyone having the same issue.

**Comment by MaximoMachado** [comment]
Is there a way to add this keybind to the command line as well?

**Comment by theol0403** [comment]
@rafaelpirolla If you are still having the problem, please open up a new issue.

@MaximoMachado I will look into adding C-r bindings to the commandline. If it is possible, it will be very useful.

**Comment by julior-ox** [comment]
I also would like to paste registers from command-line, like @MaximoMachado asked.

For example start search with `/`, then paste content from unnamed register by `<C-r>">`.

@theol0403 Did you find out anything about it?

**Comment by theol0403** [comment]
> @theol0403 Did you find out anything about it?

WIP: #657

**Comment by theol0403** [comment]
> @theol0403 Did you find out anything about it?

 #908 is a much better implementation!
