### ISSUE TITLE
Jump motion CTRL-O opens unsaved buffer instead of previously opened file

### ISSUE THREAD

**Issue by kurnev** [asvetliakov/vscode-neovim#392]
**Steps:**

1. Have Vetur installed (it also reproduces with other files, but with Vetur I could reproduce it constantly)
2. Make changes in `.vue` a file and don't save those.
3. Jump to any other file using VSCode file search.
4. Go back using default vim hotkey `CTRL-o`

**Expected:**
Previously opened `vue` file is focused again

**Actual:**
Buffer with no association with previously opened file is focused

![vscode-neovim-vetur](https://user-images.githubusercontent.com/14089913/94458216-536d0600-01be-11eb-88df-8d839c43556f.gif)

It doesn't happen with all `.vue` files, though. Only several are affected. I will try to dig into the code later and see why this is happening, but would also appreciate some guidance on where to look. 

Env:
```
VSCode: Version: 1.49.1
NVIM v0.5.0-dev
OS Fedora 32
```

init.vim:
```vimrc
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'posva/vim-vue'
call plug#end()

xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine

nnoremap <C-h> <Cmd>call VSCodeNotify('workbench.action.focusLeftGroup')<CR>
xnoremap <C-h> <Cmd>call VSCodeNotify('workbench.action.focusLeftGroup')<CR>
nnoremap <C-j> <Cmd>call VSCodeNotify('workbench.action.focusBelowGroup')<CR>
xnoremap <C-j> <Cmd>call VSCodeNotify('workbench.action.focusBelowGroup')<CR>
nnoremap <C-k> <Cmd>call VSCodeNotify('workbench.action.focusAboveGroup')<CR>
xnoremap <C-k> <Cmd>call VSCodeNotify('workbench.action.focusAboveGroup')<CR>
nnoremap <C-l> <Cmd>call VSCodeNotify('workbench.action.focusRightGroup')<CR>
xnoremap <C-l> <Cmd>call VSCodeNotify('workbench.action.focusRightGroup')<CR>
```

**Comment by Shatur95** [comment]
Yes, I also mentioned the same issue [here](https://github.com/asvetliakov/vscode-neovim/pull/356#issuecomment-691343256). I suggest you to currently use the following:

```json
    {
        "key": "ctrl+o",
        "command": "workbench.action.navigateBack",
        "when": "editorTextFocus && !neovim.recording && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+i",
        "command": "workbench.action.navigateForward",
        "when": "editorTextFocus && !neovim.recording && neovim.mode != 'insert'"
    },
```

You can map it inside Vim, but I mapped it inside VSCode to make it work for all windows.

**Comment by gabzim** [comment]
I run into this constantly to the point where I'm switching back to nvim for a while until this is fixed. I'd love to be able to help. It's kind of random in its occurrence so far.

**Comment by asvetliakov** [comment]
#461 solves it

**Comment by zhaoxuyll** [comment]
I've found that using the cursor to redo (cursorUndo) is more accurate than using the workspace navigation(workbench.action.navigateBack) to jump.
