### ISSUE TITLE
Neovim loses filetype when file is closed then reopened

### ISSUE THREAD

**Issue by jpear1** [asvetliakov/vscode-neovim#399]
Basically, when you close then reopen a file, `filetype` is not set. I have only tried this on WSL.

Reproduction steps:

1. Set up environment:
```
mkdir test
cd test
touch foo.py
code .
```
2. Click on `foo.py` in the project tree to open the file
3. Run `set ft?` and observe output `filetype=python`
4. Close the current tab you're using to view `foo.py`
5. Click on `foo.py` in the project tree to open the file again
6. Run `set ft?` and observe output `filetype=`

Expected behavior:
`set ft?` still outputs `filetype=python` after closing and reopening the file.

**Comment by systemctl603** [comment]
I can reproduce on native windows 10 `nvim` too.

**Comment by asvetliakov** [comment]
I believe this should be fixed here. Reopen if not

**Comment by jpear1** [comment]
@asvetliakov I'm not sure how to install from source, so I can't yet confirm whether this is fixed. However, I'd just like to thank you for all the time and effort you put into this project. It's radically improved my VSCode experience.

**Comment by asvetliakov** [comment]
@jpear1 you don't need to install from source. 0.0.76 is the latest master

**Comment by jpear1** [comment]
Oh I wasn't aware. Fixed on my machine!
