### ISSUE TITLE
Neovim was disconnected

### ISSUE THREAD

**Issue by Jeffrey04** [asvetliakov/vscode-neovim#406]
I can't get this extension running since it requires nvim 0.5

I am running

```
[I]  jeffrey04@NOBITA-UBUNTU ~  $ nvim --version
NVIM v0.5.0-654-g3acfefb63
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/config -I/build/nvim/parts/nvim/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include
Compiled by root@lgw01-amd64-012

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

And this is the log

```
2020-10-16T04:47:46.591Z MainController: Spawning nvim, path: /snap/bin/nvim, useWsl: false, args: ["-N","--embed","-c","source /home/jeffrey04/.vscode/extensions/asvetliakov.vscode-neovim-0.0.63/vim/vscode-options.vim","--cmd","source /home/jeffrey04/.vscode/extensions/asvetliakov.vscode-neovim-0.0.63/vim/vscode-neovim.vim","-u","/home/jeffrey04/.config/nvim/init.vim"]
2020-10-16T04:47:46.597Z MainController: Attaching to neovim
2020-10-16T04:47:46.599Z MainController: Init
2020-10-16T04:47:46.599Z MainController: Attaching to neovim notifications
2020-10-16T04:47:47.019Z MainController: Neovim was disconnected
2020-10-16T04:47:47.030Z MainController: Neovim exited with code: 0
```

The visual studio code that I am currently using is at version 1.50.1, and I am on Ubuntu 20.10 beta (didn't work in 20.04 either)

**Comment by Jeffrey04** [comment]
OK, got it working once I switched to an AppImage release, previously most likely due to snap confinement restriction i suppose

**Comment by citizen428** [comment]
I also haven't been able to get this to work for over a month now. Had no issues with macOS, but no luck with the Windows + WSL combo. Based on your last comment I switched from Snap to AppImage, but still no dice. Same with the unstable PPA.

From what I can see, everything should be in order, and `fvim --wsl` ([FVim](https://github.com/yatli/fvim)) works fine.

Relevant settings in VSCode:

```json
  "vscode-neovim.neovimExecutablePaths.linux": "/usr/bin/nvim",
  "vscode-neovim.neovimInitVimPaths.linux": " /home/johndoe/.config/nvim/init.vim",
  "vscode-neovim.useWSL": true,
```

Verify settings in WSL:

```sh
❯ nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: [snipped]

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
❯ which nvim
/usr/bin/nvim

❯ file /home/johndoe/src/nvim-config/init.vim
/home/johndoe/src/nvim-config/init.vim: UTF-8 Unicode text

❯ which wslpath
/usr/bin/wslpath
```

I only have a single WSL distro currently, so an issue with the default.

**Comment by asvetliakov** [comment]
WSL integration is shell aware. Doesn't work with non-bash like shells, like fish

**Comment by citizen428** [comment]
Well, that's the culprit then. Maybe this should be added to https://github.com/asvetliakov/vscode-neovim#wsl so other people don't spend time on figuring out what's wrong with their setups.

Also, would you mind elaborating a bit on why it's shell aware and what one could do to help change this?

**Comment by asvetliakov** [comment]
It should work in latest master: #428 , but it's not released yet. You can either build vsix from master or wait a little till new release.

**Comment by citizen428** [comment]
Thanks, @asvetliakov, I had found #428 in the meantime and just checked out master to install locally. 👍

**Comment by asvetliakov** [comment]
Should be fixed & released now

**Comment by Jeffrey04** [comment]
lol the ticket was original filed for nvim snap package
