### ISSUE TITLE
% tag match not working

### ISSUE THREAD

**Issue by userbal** [asvetliakov/vscode-neovim#407]
In neovim pressing % with the cursor on an html tag takes you to the opposite tag. This works out of the box. This is not working in vscode.

neovim version: 0.5.0
vscode-neovim version: 0.0.63

**Comment by chase** [comment]
@userbal It seems to work now!

In case it doesn't work for you still, try adding this to your `init.vim`:
`runtime macros/matchit.vim`

@asvetliakov This can probably be closed

**Comment by theol0403** [comment]
Yep, things like this are not handled by the extension, it's usually a vimrc issue. Also, check out https://github.com/andymass/vim-matchup, it's pretty sweet!

**Comment by vegerot** [comment]
I got this to work by adding `packadd matchit` to my `init.vim` https://github.com/vegerot/dotfiles/commit/709d6bd1d50fcc8a7099ddb0b88db1d2138ac10b
