### ISSUE TITLE
Mouse selection while in insert mode does not put you in visual mode

### ISSUE THREAD

**Issue by macintacos** [asvetliakov/vscode-neovim#408]
See summary. When I'm in insert mode, I assume that when I select text I'll be put into visual mode, but it doesn't do that (even with the option checked in the settings). Any ideas what might be the issue here?

**Comment by pangteypiyush** [comment]
"Mouse Selection Start Visual Mode" doesnt work either.

**Comment by asvetliakov** [comment]
Dup of #395
