### ISSUE TITLE
Better multi-cursor support (similar to VSCodeVim) to allow per-cursor motions

### ISSUE THREAD

**Issue by macintacos** [asvetliakov/vscode-neovim#409]
It'd be wonderful is this extension could treat each cursor that is generated as its own "context", and allow normal-mode to work with multiple cursors. I have no idea how complicated this would be to execute given the way that it is implemented, but let me explain.

Say I want to use VSCode's built-in functionality to add a cursor below the current line while in `normal` mode. This feels natural to me, and I use things like `cmd+d` to add cursors to the next occurrence of a given word all the time (for example). When I have added all the cursors I want, my first thought is "okay time to do a motion", so I execute something like `ciw`. In VSCodeVim, this behaves as I expect, but in vscode-neovim, it does not.

Here are some gifs that explain things visually a lot better than I can via text. Here's what happens in neovim:

![Screen Recording 2020-10-16 at 19 25 07](https://user-images.githubusercontent.com/8128941/96322570-a3820000-0fe7-11eb-9af2-8d95b9fe1a3f.gif)

And here's what happens in VSCodeVim:

![Screen Recording 2020-10-16 at 19 29 58](https://user-images.githubusercontent.com/8128941/96322521-66b60900-0fe7-11eb-9a4f-311c8b64eeb4.gif)

In order to get to what I think would be "good multi-cursor support", I think that the following would probably need to happen:

- Figure out a way to make it so that if you have multiple cursors, the first instance of `ESC` is interpreted as "go into normal mode".
- When in normal mode + multiple cursors, treat each cursor independently, and send motions/commands to those cursors specifically. If I hit `ciw` (like I did in the gifs about) each cursor should interpret its "context" to execute the motion on the text it has

Lastly, I'd just like to note that this issue is pretty much the only thing keeping me on VSCodeVim at this point. Aside from that, I really like this extension's implementation, and it has a ton of upsides in comparison to VSCodeVim's "emulation-focused" approach (which requires re-inventing the wheel, which feels like an uphill battle). If this extension got first-class multi-cursor support, there'd be nothing holding me back from singing this extension's praises and using it every single day.

Please let me know if you have any questions about the above details!

**Comment by muhajirdev** [comment]
Looking for similar things.
Found this https://medium.com/@schtoeffel/you-don-t-need-more-than-one-cursor-in-vim-2c44117d51db

Might be useful for you

**Comment by Shatur95** [comment]
A lot of things with multiply cursors just can be done faster. For vim / neovim there is awesome [vim-visual-multi](https://github.com/mg979/vim-visual-multi).

**Comment by macintacos** [comment]
I use vim-visual-multi, and while it (surprisingly) works when used with this extension, I don't think that it's that great when used in a VSCode context when VSCode already has such great multi-cursor support.

As far as arguments about whether or not one needs more than one cursor in vim, I get that some folks have been able to change their workflow to accommodate not having multiple cursors, I'm unfortunately not one of them - I love having multiple cursors, so I'd like to just have a way to make it work the best that it can with VSCode + vscode-neovim 🙂

**Comment by muhajirdev** [comment]
ooh cool, I haven't use vim-visual-multi yet.

is there any example where vim visual multi is way to user compared to traditional approach?
also curious why vim-visual-multi not working great with VSCode, what's missing?

**Comment by macintacos** [comment]
@muhajirdev vim-visual-multi is great, don't get me wrong - it just feels like it's not ad straightforward/integrated as using VSCodeVim's multi-cursor support (which uses VSCode's native multi-cursor support to get things done). The experience of using it feels like there were compromises made to add it, rather than something that feels native to the tool. It also has come odd issues where it will stop updating text in all of the places where there's a cursor until you hit `ESC`, which I mean is "fine", but it makes me feel like maybe I messed something up until I've actually "committed" my changes.

In general, just wish this extension would integrate with VSCode's cursors similar to how VSCodeVim does 🙂

**Comment by muhajirdev** [comment]
I just tried vim-visual-multi. For some reason it doesn't work on my VSCode but work on terminal

**Comment by macintacos** [comment]
vim-visual-multi works for me in vscode, just not well.

**Comment by asvetliakov** [comment]
Dup of #97

**Comment by trkoch** [comment]
For anyone who wants to give `vim-visual-multi` in VSCode a try, make sure to add this to your `keybindings.json`.
```
{
        "command": "vscode-neovim.send",
        "key": "ctrl+n",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<c-n>"
}
```

However, I agree `vim-visual-multi` does not work optimal in VSCode and feels like a hack. I can see adding true multi-cursor support is a challenge and lets hope @asvetliakov finds the time to give it a try.

**Comment by echaya** [comment]
Thanks trkoch, below is to replicate the functionality fully from 'vim-visual-multi' - in case anyone wants to copy and paste

''' 
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+n",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<c-n>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+up",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<c-up>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "shift+up",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<S-up>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "shift+down",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<S-down>"
    },
    {  
        "command": "vscode-neovim.send",
        "key": "shift+left",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<S-left>"
    }, 
    {
        "command": "vscode-neovim.send",
        "key": "shift+right",
        "when": "editorTextFocus && neovim.mode != insert",
        "args": "<S-right>"
    },
'''

**Comment by paramoNNNN** [comment]
somehow ctrl+n doesn't work for me and it just moves the cursor to next line.
btw it works fine when I tested it out in nvim itself.

**Comment by Doomwhite** [comment]
Same...

**Comment by Zundrium** [comment]
Thanks for the snippet @echaya, sadly there is no realtime feedback on all cursors like vim-multiple-cursors, any idea why?

**Comment by jackblackevo** [comment]
Hi, I found that when I press <kbd>I</kbd> key to start insert via [vim-visual-multi](https://github.com/mg979/vim-visual-multi), however the cursor go to start of line, not start of selection which I am expected.

**Comment by pencilcheck** [comment]
> Hi, I found that when I press I key to start insert via [vim-visual-multi](https://github.com/mg979/vim-visual-multi), however the cursor go to start of line, not start of selection which I am expected.

Same, but for me the multi-cursor works by pressing `⌘ + SHIFT + L` instead of `⌘ + SHIFT + I`

**Comment by FaeWulf** [comment]
> Thanks trkoch, below is to replicate the functionality fully from `vim-visual-multi` in case anyone wants to copy and paste
> 
> ```json
>     {
>         "command": "vscode-neovim.send",
>         "key": "ctrl+n",
>         "when": "editorTextFocus && neovim.mode != insert",
>         "args": "<c-n>"
>     },
>     {
>         "command": "vscode-neovim.send",
>         "key": "ctrl+up",
>         "when": "editorTextFocus && neovim.mode != insert",
>         "args": "<c-up>"
>     },
>     {
>         "command": "vscode-neovim.send",
>         "key": "shift+up",
>         "when": "editorTextFocus && neovim.mode != insert",
>         "args": "<S-up>"
>     },
>     {
>         "command": "vscode-neovim.send",
>         "key": "shift+down",
>         "when": "editorTextFocus && neovim.mode != insert",
>         "args": "<S-down>"
>     },
>     {  
>         "command": "vscode-neovim.send",
>         "key": "shift+left",
>         "when": "editorTextFocus && neovim.mode != insert",
>         "args": "<S-left>"
>     }, 
>     {
>         "command": "vscode-neovim.send",
>         "key": "shift+right",
>         "when": "editorTextFocus && neovim.mode != insert",
>         "args": "<S-right>"
>     },
> ```

For anyone come here for this solution. Unfortunately, it is broken after version 0.90.0
