### ISSUE TITLE
vscode neovim breaks CMD+c copy shortcut on macOS

### ISSUE THREAD

**Issue by benwbooth** [asvetliakov/vscode-neovim#410]
When using vim or neovim with e.g. the vimR GUI frontend on macOS, CMD+X C V for cut/copy/paste works as expected. It also works as expected in vscode when using the vscodevim extension. 

However, when using vscode-neovim extension, CMD+c does not copy the selected text, but instead copies the entire line of wherever the cursor is located. Also, the visual selection is not unselected when pressing CMD+c. Oddly, CMD+x and CMD+v work as expected to cut and paste, respectively.

**Comment by benwbooth** [comment]
Actually CMD+x has the same issue -- it has the same issue where it cuts the entire line instead of the selection. 

Is this because the neovim selection is not synced with the vscode selection? If I make a visual selection with neovim, then hit CMD+Shift+P, then hit Escape to close the palette window, then CMD+c to copy the selection, then hit Escape again to clear the visual selection, then CMD+v to paste, it works.

There really should be a way to keep the neovim and vscode selections synced to fix this problem.

**Comment by asvetliakov** [comment]
either 1) unbind `cmd+c/cmd-x/cmd-v/whatever` from vscode and don't send to neovim or 2) pass `cmd-c/cmd-x/cmd-v` to neovim and either call vscode copy/paste command or put/copy to `"*` register.

**Comment by benwbooth** [comment]
Can we make the above settings the default? Or provide instructions in the documentation to fix this? IMHO it's not acceptable to break universally expected Cut/Copy/Paste keybindings without any explanation in the documentation.

**Comment by andrewschreiber** [comment]
> either 1) unbind cmd+c/cmd-x/cmd-v/whatever from vscode and don't send to neovim or 2) pass cmd-c/cmd-x/cmd-v to neovim and either call vscode copy/paste command or put/copy to "* register.

(2) seems better, as I might want to copy things from non-editor regions in VSCode, so I don't think its a good idea to unbind CMD+C etc. 

I'm confused on what to to accomplish (2). Could anyone provide a clear example of how to restore Cmd+C copy functionality to visual mode?

![image](https://user-images.githubusercontent.com/1892071/106556074-a3910780-64d3-11eb-8ef4-0f5b38b45cb4.png)
For example, in the above situation for

>         <motion.div
>           style={{
> 

to be copied.

**Comment by andrewschreiber** [comment]
One approach I found was that you can add
`set clipboard+=unnamedplus` to the top of your `vim.init`

Now at least you can add visual selected text to your clipboard with 'y'

**Comment by pbassut** [comment]
+1 for adding that to the docs. At least in the troubleshooting section.

Came from VSCodeVim, noticed this right away. 
What @andrewschreiber provided is a workaround but I wanted the real thing.
