### ISSUE TITLE
Use kj as escape when insert mode

### ISSUE THREAD

**Issue by AYM1607** [asvetliakov/vscode-neovim#412]
Hi!

I've been using the extension recently and it has been working great. However, I have a small issue. I typically use kj to exit insert mode and got very used to it, it's muscle memory at this point. I saw that there's a way of using jj or jk for this purpose but I'd really like to use kj instead. Is there a way of doing so? I tried different key combinations for the vscode-neovim.compositeEscape1 and vscode-neovim.compositeEscape2 commands but they didn't seem to work.

Thanks in advance!

P.S. If someone could point me to where in the codebase this is done I could help with a PR.

**Comment by theol0403** [comment]
You just need to switch the letters:

```js
{
    "command": "vscode-neovim.compositeEscape1",
    "key": "k",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "k"
}
{
    "command": "vscode-neovim.compositeEscape2",
    "key": "j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "j"
}
```

**Comment by AYM1607** [comment]
I guess that's the combination I didn't try. Thanks for that!
