### ISSUE TITLE
Easymotion now only work in vscode, gives error in nvim

### ISSUE THREAD

**Issue by albert-ying** [asvetliakov/vscode-neovim#415]
Hi, I installed the fork of easymotion that works in VScode. However, I cannot use this function in Neovim anymore.

EasyMotion: Vim(call):E117: Unknown function: VSCodeSetTextDecorations

Is there way to make it work in both?

**Comment by Shatur95** [comment]
You should use upstream version inside Vim and fork inside VSCode.

**Comment by albert-ying** [comment]
> You should use upstream version inside Vim and fork inside VSCode.

Sorry, could you explain more? 

Is it like this in init.vim? :

if exists('g:vscode')
	call plug#begin('~/.config/nvim/plugged')
	Plug 'https://github.com/asvetliakov/vim-easymotion.git'
        call plug#end()
else
        call plug#begin('~/.config/nvim/plugged')
	Plug 'vim-easymotion/vim-easymotion'
        call plug#end()
endif

**Comment by Shatur95** [comment]
Yes, exactly. This is the only way.

**Comment by theol0403** [comment]
Two ways actually:

Lazy loading, my preferred way, as you can have both installable at once:
```vim
function! Cond(Cond, ...)
  let opts = get(a:000, 0, {})
  return a:Cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

Plug 'easymotion/vim-easymotion', Cond(!exists('g:vscode'))
Plug 'asvetliakov/vim-easymotion', Cond(exists('g:vscode'), { 'as': 'vsc-easymotion' })
```

Branching inside plug, simpler version of your above example, I like this worse because it makes installing confusing:
```vim
call plug#begin('/.config/nvim/plugged')
if exists('g:vscode')
Plug 'asvetliakov/vim-easymotion.git', { 'as': 'vsc-easymotion' }
else
Plug 'vim-easymotion/vim-easymotion'
endif
call plug#end()
```

**Comment by nhatquang0672** [comment]
Hi @theol0403 , although I setup liked you in init.vim, I'm still got the error. Can you help me to fix it?

![image](https://github.com/vscode-neovim/vscode-neovim/assets/31817153/a5519fd3-4bc2-406a-ac89-8e1a2f5e59f5)
![image](https://github.com/vscode-neovim/vscode-neovim/assets/31817153/08fec2ce-b6b6-47e7-a6e6-359c510c7eb9)

**Comment by theol0403** [comment]
Easymotion not supported anymore

**Comment by nhatquang0672** [comment]
So @theol0403 , do we have any other solution to use easymotion with vscode-neovim?
Without easymotion, changing the pointer position is terrible.

**Comment by theol0403** [comment]
Use many of the neovim-based alternatives.

**Comment by nhatquang0672** [comment]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/31817153/50297c6e-6541-4257-91fa-50a84057a983)
![image](https://github.com/vscode-neovim/vscode-neovim/assets/31817153/26d3a5f8-ddaa-4589-97fe-5c06f1c98b05)
@theol0403 , when I try to save file in vscode with mapping <leader>w, I got the error in the image. 
But when i'm using the terminal, I can save it normally. Can you help to solve this issue?

**Comment by theol0403** [comment]
@nhatquang0672 This is the wrong issue, and the issue tracker is not for support. The problem is clear if you look at the docs, or at the default bindings file in the `vim` folder.

**Comment by nhatquang0672** [comment]
I'm quite sure that I've read nvim-lua documentation and spend amout of time to research about this issue. It's just super basic config with mapping key to call vim function. 
Do you have any suggestion or I should re-read doc again @theol0403 ?
Thank you for your support.

**Comment by nhatquang0672** [comment]
Honestly, I think this issue is come from vscode-neovim. 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/31817153/c9ebb0d0-ff65-409c-bc19-61f32ea212ce)

When I try this command in my lua config `vim.keymap.set("n", "<leader>w", vim.cmd.Write)` ==> can save on vscode, but not in nvim terminal. 
With this command `vim.keymap.set("n", "<leader>w", vim.cmd.write)` ==> can save on terminal, but not working in vscode. 

The difference in vim.cmd.write vs vim.cmd.Write is quite confused.

Maybe, I should use `if vim.g.vscode then
    -- VSCode extension
else
    -- ordinary Neovim
end` in the doc of vscode-neovim, but I think we need some update to fix it?
Thank you for your support. @theol0403

**Comment by theol0403** [comment]
No, this is not an issue. This is the way the extension works. You can also try a recursive map.
