### ISSUE TITLE
Scroll history in VIM Command Line 

### ISSUE THREAD

**Issue by cirelli94** [asvetliakov/vscode-neovim#419]
It would be great to be able to scroll previous sent command in VIM Command Line.

Now:
- Press `:`
- Press arrow up
- Nothing happens

Proposed feature:
- Press `:`
- Press arrow up
- Scroll previous sent command

Example:
[![asciicast](https://asciinema.org/a/zhhkLQw0IKm8JFCMHS2LVuLD6.svg)](https://asciinema.org/a/zhhkLQw0IKm8JFCMHS2LVuLD6)

**Comment by Shatur95** [comment]
Duplicate of #385.
