### ISSUE TITLE
write command doesn't work when mapped

### ISSUE THREAD

**Issue by pvinis** [asvetliakov/vscode-neovim#420]
In my `init.vim` I have
```
nnoremap <Space> <Nop>
let mapleader="\<Space>"
nnoremap <leader>w :w<CR>
```
and in VSCode, everything else works great, but when I press `space`, nothing happens. Same with `space` `w`.

Do I need to do something special for the leader? Is there a way to debug and see what is going wrong?

**Comment by Shatur95** [comment]
Try `noremap <leader>w <Cmd>W<CR>`

**Comment by pvinis** [comment]
Nothing happens still.. :(

**Comment by pvinis** [comment]
To be clear, what the goal is, is for me to hit `space` `w` and have the file saved.

**Comment by Shatur95** [comment]
Could you also try with `let mapleader = '  '`?
Space as leader key works for me just fine. [Here](https://github.com/Shatur95/neovim-config) is my configuration.

**Comment by pvinis** [comment]
Hm, I just saw at the bottom, that apparently it is working, the leader. When I press `w` after, it gives `E382: Cannot write, 'buftype' option is set`. Hmm..

**Comment by pvinis** [comment]
Ok getting closer. I see that `nnoremap <leader>w :w` opens the little command window with `w` prefilled, and when I hit enter it saves the file. But when I add `<CR>` like `nnoremap <leader>w :w<CR>`, it suddenly gives me that E382 error.

**Comment by pvinis** [comment]
I found https://github.com/asvetliakov/vscode-neovim/issues/214#issuecomment-594886891 this and it works now with `nnoremap <leader>w :Write<CR>` but I still don't get why..

**Comment by Shatur95** [comment]
Oh, this is because normal `:w` command was replaced with VSCode one. Yes, you should use `:Write` for VSCode.

**Comment by pvinis** [comment]
But why? In my mind, the `:w` command from neovim would be mapped to the VSCode "save file" command? I guess I'm missing some context about how the two are connected.

**Comment by Shatur95** [comment]
This command is only replaced inside the VSCode cmdline if I understand correctly. In mappings you should commands like `:Write`.

**Comment by theol0403** [comment]
I don't think there is a way to override neovim's save file command, this plugin just has a mechanism to automatically correct :w to :Write. When you use <Cmd> you bypass that correction, thus calling neovim's save command - not the VSCode save command that normally :w usually gets diverted to.
