### ISSUE TITLE
-- INSERT -- indicator on status bar remains in nomarl mode

### ISSUE THREAD

**Issue by tlannaax** [asvetliakov/vscode-neovim#422]
Steps to reproduce: enter insert mode, type several characters and escape to normal mode. The "-- INSERT --" would remain on status bar.
Entering insert model and directly escape without typing gives the correct behavior: "-- INSERT --" disappears.

**Comment by myfoxit** [comment]
I have the same issue on my vscode : 

nvim version : v0.5.0-812-gd17e50879
vscode : 1.50.0

**Comment by guyguy2001** [comment]
I also have this issue, but only when using WSL.

NVIM v0.5.0-728-gf6ac37560
Build type: RelWithDebInfo
vscode; 1.51.1

**Comment by asvetliakov** [comment]
Duplicate of #270
