### ISSUE TITLE
Insert mode doesn't update until I go back to normal mode

### ISSUE THREAD

**Issue by muhajirdev** [asvetliakov/vscode-neovim#423]
So,

I was trying to use this plugin https://github.com/eraserhd/parinfer-rust. It works well within the terminal as we can see here https://www.loom.com/share/94bdecc05c5048bb8c9163741743c831?from_recorder=1

But it doesn't work on vscode, until I press `esc` to go back to normal

https://www.loom.com/share/d55f58d9e8934fde988a4ab2e6ca95e7

**Comment by guyguy2001** [comment]
According to the author, the extension doesn't do anything when you type in insert mode, and so the neovim server doesn't know you changed anything until the escape key.

![image](https://user-images.githubusercontent.com/6932278/100485666-a05f5100-3109-11eb-92d4-6d7290ed37ec.png)
(Taken from the bottom of the README)

The reason for that, as far as I understand, is that the vscode extension event queue is single-threaded, and so if any extension takes 20 ms to finish an action after you typed, that's 20ms you won't see the next character typed, as neovim needs to process it. You can read more of the discussion here - https://github.com/asvetliakov/vscode-neovim/issues/256

(Note - I haven't worked on this extension (yet), I am just sharing what I found while reading issues here, so I may be wrong about stuff)

**Comment by asvetliakov** [comment]
By design insert mode is vscode responsibility

**Comment by gdw2** [comment]
Release [0.0.91](https://github.com/vscode-neovim/vscode-neovim/blob/509aaed3ad818ddb485084fdb853be8fbe07bb7c/CHANGELOG.md?plain=1#L31) includes this:

> in insert mode, changes get sent immediately, instead of on exit

Therefore, parinfer-rust works... sort of.  After every keystroke it re-infers the parens.  If you try it out for a few minutes, you'll get what I'm saying.
