### ISSUE TITLE
Don't how to setup the plugin with wsl (Neovim exited with code 127)

### ISSUE THREAD

**Issue by RanyG961** [asvetliakov/vscode-neovim#424]
Hello guys,

I'm a really sorry to ask this question, I didn't find the answer and how to resolve it.
I don't know what do I have to put for the paths to use neovim with WSL, I tried it all and it doesn't work...

![image](https://user-images.githubusercontent.com/12932807/97925417-a27bfd00-1d61-11eb-8519-f1afe9d20cf4.png)

I have this error.

Thanks for your help

**Comment by ferreria23** [comment]
What nvim version do you have installed in WSL? (you need version 0.5+)

Are you setting `vscode-neovim.useWS` to `true` and `vscode-neovim.neovimExecutablePaths.linux` to the path of your nvim bin 
(you can use `which nvim` to find the path)

What is the output of `wslpath "c:\windows"`?

**Comment by jarethill** [comment]
I'm getting this same error when trying to use the plugin. useWSL is set to true. ExecutablePaths.linux is set to "/usr/bin/nvim" which is where the executable is located (appimage from releases page, v. 0.5) and wslpath output is "/mnt/c/windows". Any ideas what I could be doing wrong?

**Comment by RanyG961** [comment]
> What nvim version do you have installed in WSL? (you need version 0.5+)
> 
> Are you setting `vscode-neovim.useWS` to `true` and `vscode-neovim.neovimExecutablePaths.linux` to the path of your nvim bin
> (you can use `which nvim` to find the path)
> 
> What is the output of `wslpath "c:\windows"`?

Hey, first thank you for your reply ! I found the problem I installed on the wrong version of my wsl... 

I just didn't know that Ubuntu wasn't my version per default, thanks for the help anyway !

**Comment by RanyG961** [comment]
> I'm getting this same error when trying to use the plugin. useWSL is set to true. ExecutablePaths.linux is set to "/usr/bin/nvim" which is where the executable is located (appimage from releases page, v. 0.5) and wslpath output is "/mnt/c/windows". Any ideas what I could be doing wrong?
> 
> Edit: Path is set correctly too, running nvim from terminal works perfectly

Check your version per default on wsl mate, just did that and now it work perfectly !

**Comment by jarethill** [comment]
> 
> 
> > I'm getting this same error when trying to use the plugin. useWSL is set to true. ExecutablePaths.linux is set to "/usr/bin/nvim" which is where the executable is located (appimage from releases page, v. 0.5) and wslpath output is "/mnt/c/windows". Any ideas what I could be doing wrong?
> > Edit: Path is set correctly too, running nvim from terminal works perfectly
> 
> Check your version per default on wsl mate, just did that and now it work perfectly !

Thanks so much buddy, that did the trick. I installed Docker before I installed my Ubuntu distro in WSL and never changed the default but now it's working perfectly.

A suggestion then to the repo maintainer(s), could be helpful to add a warning about this in the readme now that the cause is known. I'm sure lots of developers install Docker Desktop; and then later a personal use distro without thinking to change over the default. Or even better, a VS Code setting pair that lets you choose which distro has neo vim installed. Thanks for your time!
