### ISSUE TITLE
BUG: Multi-line visual selection doesn't work

### ISSUE THREAD

**Issue by tw-space** [asvetliakov/vscode-neovim#425]
I don't think it's new as visual selection started really breaking in 0.0.43, but after almost a year, the builds are still bad enough that I feel I need to submit a formal complaint — I've been stuck using 0.0.42, the last build where visual selection behaviors pretty much work, because visual selection, and multi-line visual selection especially, is such a core necessity to my workflow that not having it is a dealbreaker. With all the amazing-sounding updates since then, now all the way up to 0.0.63 (nice work, team), I'm feeling serious FOMO and really want this fixed so I can jump back on the vscode-neovim bandwagon.

So what are the issues? I only tried 0.0.63 for a bit, after installing neovim-nightly-0.5.0 etc., but see the following:

1. Multi-line visual selection **only actually affects the last line** of the selection when invoking many commands
    1. Start with multiple lines of text
    2. `Shift-V` to select the current line
    3. Motion `j` or `k` to select more lines
    4. Invoke `Move Line Down`, default keyboard shortcut is `Alt-Down`
    5. **OBSERVE:** *Only the last line* moves down by a line. Earlier lines stay in place. 
    6. **EXPECTED:** All lines move down by a line.
    7. Invoke `Move Line Up` (`Alt-Up`)
    8. **OBSERVE:** *Only the last line* moves up by a line. Earlier lines stay in place.
    9. **EXPECTED:** All lines move up by a line.
    10. Invoke `Indent Lines`, default keyboard shortcut is `Cmd-]` on Mac
    11. **OBSERVE:** *Only the last line* indents. Earlier lines stay in place.

This first issue is really what kills me. I have custom commands that I invoke on multi-line selections regularly, and they all fail to affect any but the last line of selections. Actually this issue also sometimes reproes in 0.0.42, but much less severely.

Other, smaller, issues:

2. Visually, line selection **doesn't highlight the first character in the range**
    1. Start with multiple lines of text
    2. `Shift-V` to select the current line
    3. **OBSERVE:** *first character* in line is *not highlighted*
    4. Motion `j` to highlight the next line below
    5. **OBSERVE:** *both first characters* in both lines are *not highlighted*
    6. See how the first characters of each line aren't highlighted in this image:

![image](https://user-images.githubusercontent.com/56986410/97924720-f3b1cf80-1d14-11eb-82ab-6de54b4672d2.png)

3. Visually, line selection **doesn't highlight the next character after the cursor**
    1. Same steps as above, and spot in the earlier image how the `a` in `had` isn't highlighted

I really hope this issue gets fixed as, like I said, multi-line visual selection is a P1 feature for me. Thank you!

**Comment by asvetliakov** [comment]
Should be fixed for a while now
