### ISSUE TITLE
easymotion fork doesn't highlight target char

### ISSUE THREAD

**Issue by rilakkumars** [asvetliakov/vscode-neovim#426]
Hi, I'm trying to use the forked version of vim-easymotion, it can work, but the motion target char color is not highlighted.

**Comment by Shatur95** [comment]
You should provide more information if you want to get help. Which version of the VSCode plugin are you using? Have you tried disabling all other Vim / VSCode plugins?

**Comment by rilakkumars** [comment]
Sorry for the missing info:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

vscode-neovim  version:v0.0.63

Neovim versoin: NVIM v0.5.0-727-gc10c2fab5

all other vscode plugins disabled,
all other neovim plugins disabled, except for 'vim-plug'(I use it as my vim/neovim plugin manager) and forked 'vim-easymotion'

The issue is still there as shown in following picture that the target char is display at the very beginning of each line, and if I type it I can jump to specific location, but no highlight color for the target char
![image](https://user-images.githubusercontent.com/19197289/98085110-b42cd580-1e31-11eb-9634-9d43fcb99960.png)

**Comment by Shatur95** [comment]
Strange, it works for me with the latest Neovim. Have you tried with clean VSCode settings?

**Comment by theol0403** [comment]
What you are seeing is what the stock easymotion plugin looks like. Silly question, but did you install the plugin after adding it to your init.vim? Maybe your plugin manager is confused by the fork change and is still using the old plugin. Maybe try removing and uninstalling then install again.

**Comment by rilakkumars** [comment]
Fixed it, thank you for all of your helps guys. The root reason is due to one setting:
"vscode-neovim.highlightGroups.unknownHighlight": {} 

If it's {} then highlight won't work for target char. Simply delete it can resolve the issue.
