### ISSUE TITLE
setting matchpairs can not run

### ISSUE THREAD

**Issue by wodadehencou** [asvetliakov/vscode-neovim#436]
I write rust language, and I use delimiteMate as auto matchpairs plugin. I want to adding `<>` as matchpairs to rust lang.
So I set this in my *.vim files:
```vim
au FileType rust let b:delimitMate_matchpairs = "(:),[:],{:},<:>"
```

function good when I use nvim from terminal, but in vscode it seems no effect.

**Comment by Shatur95** [comment]
Insert mode controlled by VSCode. Please, read the README.
