### ISSUE TITLE
无法启动neovim

### ISSUE THREAD

**Issue by 95Jialinli** [asvetliakov/vscode-neovim#437]
![image](https://user-images.githubusercontent.com/46446884/100406534-1380ad00-30a1-11eb-961d-58c52e0d274d.png)
![image](https://user-images.githubusercontent.com/46446884/100406545-1a0f2480-30a1-11eb-9397-93f5e2ef399c.png)
![image](https://user-images.githubusercontent.com/46446884/100406559-21363280-30a1-11eb-873e-9874bfcedbfc.png)
![image](https://user-images.githubusercontent.com/46446884/100406598-37dc8980-30a1-11eb-9c8c-7256b8fdbe3e.png)

**Comment by Shatur95** [comment]
Use english, we do not understand Chinese.
