### ISSUE TITLE
CTRL + C won't copy on my Windows 10 machine.

### ISSUE THREAD

**Issue by JimmyMcBride** [asvetliakov/vscode-neovim#440]
I have the settings for using ctrl keys for insert and normal mode turned off. I have tried using it on WSL and windows installations of nvim. I've also tried it on VS Code and VSCodium and they all have the same results no matter what I do. Ctrl + d will highlight a word, Ctrl + V will paste and Ctrl + X will cut but all Ctrl + C does is exit insert mode. Is anyone else having the same issue?

**Comment by theol0403** [comment]
Not sure why this is, but do the following steps solve your problem?

![image](https://user-images.githubusercontent.com/16546293/100560622-424a7f00-326b-11eb-81d0-de4d598e5532.png)

**Comment by JimmyMcBride** [comment]
YES!!! That worked! Thank you so much! :fire:

**Comment by jackblk** [comment]
Oh god, been looking for this. This issue won't show up on Google and I need to search in this repo.

Just a note, adding this to `keybindings.json` would also work:
```json
    {
        "key": "ctrl+c",
        "command": "-vscode-neovim.escape",
        "when": "editorTextFocus && neovim.init"
    }
```

tags: disable ctrl + c in neovim vscode

**Comment by theol0403** [comment]
As of the latest commit, CTRL-C can now be disabled with `useCtrlKeysForInsertMode` 👍

**Comment by dharmaturtle** [comment]
For some reason, jackblk's comment didn't work for me. I can only disable it if I include the entire `when` from theol0403's screenshot, e.g.

```json
{
    "key": "ctrl+c",
    "command": "-vscode-neovim.escape",
    "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
}
```

However, if I state the command that I want, having a smaller `when` works:

```json
{
    "key": "ctrl+c",
    "command": "editor.action.clipboardCopyAction",
    "when": "editorTextFocus && neovim.init"
}
```
