### ISSUE TITLE
Ctrl-U / Ctrl-D scrolling in visual selection doesn't work at all

### ISSUE THREAD

**Issue by dahmc** [asvetliakov/vscode-neovim#443]
I see this comment on the readme:
> Scrolling is done by VSCode side. <C-d>/<C-u>/etc... are slighly different

The problem is, when I select a few lines after Ctrl-V, and then do Ctrl-D, it moves down, but the selection is not expanded at all, which makes it useless.

Also, when I'm on the last page, Ctrl-D doesn't jump at all anymore, even when my cursor is at the top of the last page.

Can this somehow be handled properly by neovim? It's kind of a big issue not having those jumps working with selection

**Comment by aisopous** [comment]
Ctrl-D/Ctrl-U don't update cursor position for me

**Comment by asvetliakov** [comment]
Duplicate of #293
