### ISSUE TITLE
Visual selection: Home/End keys move cursor without updating selection

### ISSUE THREAD

**Issue by heeen** [asvetliakov/vscode-neovim#448]
enter visual selection mode
use Home/End keys to select until end of line
expected result: selection updates the same as with ^ or $
actual result: selection stays same while only cursor moves

nvim:

NVIM v0.5.0-dev+927-g52e660e85
Build type: Debug
LuaJIT 2.1.0-beta3

vscode:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-31-lowlatency

**Comment by asvetliakov** [comment]
Looks like home/end keys are not being sent to nvim

**Comment by Arignir** [comment]
I'm a huge home/end addict, so really glad to see this issue finally addressed and merged o/

Do you have any idea when the new release will land? I'm quite impatient :D

**Comment by asvetliakov** [comment]
Today
