### ISSUE TITLE
MainController: Neovim exited with code: 2

### ISSUE THREAD

**Issue by zeljkofilipin** [asvetliakov/vscode-neovim#453]
VSCode+neovim work fine on my macOS 10.15.7 machine. I've just set up VSCode+neovim on a macOS 11.1. machine and I'm getting this error message: `MainController: Neovim exited with code: 2`. It appears when I try to edit a file.

![vscode](https://user-images.githubusercontent.com/23927/102391095-8b256600-3fd5-11eb-8d8f-e439937612f4.png)

My configuration file is at:

https://github.com/zeljkofilipin/dotfiles/blob/master/Library/Application%20Support/Code/User/settings.json

**Comment by jordansoltman** [comment]
Getting the exact same thing.

**Comment by adrianfranzese** [comment]
Try this workaround: https://github.com/neovim/neovim/issues/13529#issuecomment-747166985

**Comment by zeljkofilipin** [comment]
@adrianfranzese thanks! It works! I didn't even think to check if it's neovim or vscode-neovim issue. 🤦
