### ISSUE TITLE
Forward search is highlighted all the time after searching is done

### ISSUE THREAD

**Issue by andynameistaken** [asvetliakov/vscode-neovim#454]
## What happens:
- pressing `/` for forward search keeps highlighted matched text till next search
## What should happen:
- after jump to insert mode highlights should disappear

**Comment by theol0403** [comment]
This is standard vim behaviour.

https://vi.stackexchange.com/questions/8741/how-to-automatically-turn-off-hlsearch-after-im-done-searching
