### ISSUE TITLE
pressing <c-j> in normal mode behaves like <s-j> and joins lines.

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#462]
Basically, when I press ctrl+j in normal mode, it joins lines, instead of doing what I have it `nmap`ed to.

Any ideas why? No problem in plain Neovim.

**Comment by asvetliakov** [comment]
try to check in vscode keybindings if something eats `<c-j>` and unset it:
![image](https://user-images.githubusercontent.com/8881674/103255378-680d9580-4989-11eb-83e0-ed54a73d2725.png)

**Comment by trusktr** [comment]
Ah, thanks. :pray:   Indeed there's a default binding for that.
