### ISSUE TITLE
Where is gt and gT mapped?

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#464]
How does the extension know to go to next/prev VS Code tab?

**Comment by asvetliakov** [comment]
https://github.com/asvetliakov/vscode-neovim/blob/1bf106120170cf419a5755155eb7dcfa39c838ad/vim/vscode-tab-commands.vim#L37-L40

**Comment by trusktr** [comment]
Ah, thanks!

I had to change 

```viml
                noremap <c-left> gT
                noremap <c-right> gt
```

to

```viml
                nmap <c-left> gT
                nmap <c-right> gt
```

in my `init.vim`.
