### ISSUE TITLE
Should we avoid setting scrolloff?

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#465]
Regarding:

https://github.com/asvetliakov/vscode-neovim/blob/5832a73dd2a1363a03b37ff3fd3ad8c3b0bf1671/src/main_controller.ts#L54-L57

I currently have `set scrolloff=0` in my init.vim. Things seem to work.

**Comment by asvetliakov** [comment]
the ext overwrites few critical options here:
https://github.com/asvetliakov/vscode-neovim/blob/1bf106120170cf419a5755155eb7dcfa39c838ad/vim/vscode-options.vim#L16

and additionally here:
https://github.com/asvetliakov/vscode-neovim/blob/1bf106120170cf419a5755155eb7dcfa39c838ad/vim/vscode-options.vim#L61
