### ISSUE TITLE
Most motion commands stopped working after update

### ISSUE THREAD

**Issue by sombra-yevstakhii-krul** [asvetliakov/vscode-neovim#468]
yesterday everything worked perfectly so I assume the latest update broke something. When I use commands like `h`/`j`/`k`/`l` or even `gg` or `0` cursor moves in neovim but vscode shows it in its previous position. If I enter insert mode and then move cursor it updates correctly, search also works fine. Tried empty vimrc, didn't help.

Using macOS Big Sur 11.0.1 (Intel based)

neovim version:

![image](https://user-images.githubusercontent.com/50657402/103278188-90ba7d00-49d3-11eb-9844-70adc482d36b.png)

**Comment by David-Else** [comment]
I am a bit unclear about what you mean. You are saying NeoVim works fine with h/j/k/l but VS Code with the extension in normal mode does not? What does 'previous position' refer to? Are you running an actual instance of NeoVim as well as VS Code?

It works fine here with `NVIM v0.5.0-dev+975-ga58c5509d
` from a day or two ago and the latest NeoVim 0.0.72 extension on Linux.

**Comment by sombra-yevstakhii-krul** [comment]
I meant that it seems like cursor position doesn't update in vscode when it updates in neovim, hopefully a video will help:

https://user-images.githubusercontent.com/50657402/103282348-278c3700-49de-11eb-9347-a422c9c35f9b.mov

In the video I press `j`/`k` a bunch of times, then use insert mode, then press `x` in normal a few times. I'm using [quick-scope](https://github.com/unblevable/quick-scope) that highlights unique characters in each word on current line so that I can easily use `f`/`F` to jump there. As you can see quick scope (vim plugin) updates, but vscode doesn't until I go to insert mode and move cursor.

**Comment by sombra-yevstakhii-krul** [comment]
Update: tried installing different versions, 0.0.63 works, everything above it doesn't

**Comment by asvetliakov** [comment]
@sombra-yevstakhii-krul can you enable debug logs in ext settings and upload it somewhere?

Also can you check if the issue still happens with default vscode settings and optionally with all extensions disabled?

**Comment by sombra-yevstakhii-krul** [comment]
Sorry for not replying for so long, updating neovim required also updating xcode and then it took me some time to realize I also need to update luajit (with `--HEAD` flag in brew)

Anyway update solved the issue, thanks
