### ISSUE TITLE
Append at end of the line ($A in Visual block mode ) Stopped working after update from  0.0.63

### ISSUE THREAD

**Issue by nrdlab** [asvetliakov/vscode-neovim#470]
### Details 
- OS:  mac 
- NVIM v0.5.0-nightly-116-g8b2887bd5
- vscode Version: 1.52.1

### Expected behavior  

By pressing $A should insert at the end of the line 
-  in ( v 0.0.63 )  and before 

### Actual behavior 

By pressing $A switch to insert mode but the cursor remains where it was 
- in ( v 0.0.70 , v 0.0.71 , v 0.0.72 )

**Comment by asvetliakov** [comment]
#467
