### ISSUE TITLE
Would it be possible to merge neovim undo history with VS Code undo history?

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#475]
I imagine because VS Code's is not a tree, but just a stack, that the stack in VS Code would contain the history tree just as we would see inside vim/neovim using the `g-` and `g+` keys, in chronological order.

When undoing inside VS Code, the Neo Vim extension would need to figure out which history entry that corresponds to in Neovim's history tree.

Similarly, when undiong/redoing in neovim, we'd need to undo/redo in VS Code to get to the correct location chronologically.

If we go back in the neovim undo tree, then make a new history branch, this would effectively start adding new entries at the top of VS Code's stack

I'm not sure what APIs VS Code has to make this possible, if at all. F.e., can we populate VS Code's history stack arbitrarily? If not, then we may not be able to stick an existing (persistent) history tree into VS Code's stack, and it may only work if we start with a fresh neovim history every time VS Code starts with a new history stack (meaning we would have to avoid persistent_undo in neovim).

**Comment by asvetliakov** [comment]
No, not possible. VSCode doesn't have api to manipulate undo stack (neovim also doesn't have), and i don't think it would be introduced ever.

**Comment by trusktr** [comment]
If there's no API, it seems the only way (that probably we wouldn't want to waste time trying) would be to tell VS Code to undo or redo an N number of times to get to the target history point (and only with no persistent_undo feature from #474 if that is ever supported, because there's no way to populate VS Code's stack)

The result would be like holding the ctrl-z key down until VS Code finally lands at the target history item, which would take time while the text animates history on screen. Definitely wouldn't be ideal. If we ever did try that, we'd need to block user interaction for that whole time to prevent breaking the state from an edit during the transition.

A benefit would be, that then we could rely on VS Code's persistent undo (and [at some point they'll persist it across restarts](https://github.com/microsoft/vscode/issues/7536)).

But yeah, the UX of it sounds horrible (like waiting for five minutes to go to a far neovim history branch while VS Code's screen flashes repeatedly while text is continuously updated :laughing: ).

**Comment by trusktr** [comment]
I'm new to VS Code extensions, so I asked here if it is possible to (in any way) manipulate the stack: https://stackoverflow.com/questions/65500345/how-to-access-and-manipulate-vs-codes-internal-edit-stack

From skimming some VS Code source, I see they use TypeScript `private` for many things, so it may be possible that the stack is accessible somewhere in the object graph from some object that the extension API may return. Let's see...

**Comment by asvetliakov** [comment]
unfortunately in vscode the extension host is being run in isolated separated node process, so it doesn't matter that you've seen in vscode sources

**Comment by asvetliakov** [comment]
the way is to use vscode undo stack currently is only to bind `u` and `<C-r>` to vscode undo/revert actions

**Comment by trusktr** [comment]
> the way is to use vscode undo stack currently is only to bind u and <C-r> to vscode undo/revert actions

If I imagine what that does correctly, it will use see Neovim changes and put them on the stack as expected, while in Neovim if we undo in VS Code, it would just add history to Neovim's current branch, which I suppose is oooposite of the current (undo in Neovim causes new history in VS Code's stack)?

**Comment by asvetliakov** [comment]
Absolutely right. The only thing the vscode undo is different than neovim one in terms that should be reverted because vscode is not aware of insert mode and thinks differently. 

You can try though, it can be good compromise.

Also you can experiment locally with these flags:
https://github.com/asvetliakov/vscode-neovim/blob/d366766f397954078e5b9eeb01532913fb90b48f/src/document_change_manager.ts#L479

**Comment by trusktr** [comment]
Thanks for the tips! I'll stick to neovim's for now, but if VS Code eventually comes out with persistent undo after VS Code restart, it may be worth a shot!

**Comment by Shatur95** [comment]
Can be closed, I suppose.
