### ISSUE TITLE
scrolling with cursor makes page jump

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#477]
When I scroll with the cursor in VS Code (f.e. holding `j`), the page jumps like this:

https://user-images.githubusercontent.com/297678/103330141-127eca80-4a15-11eb-8a46-fec21f5f8eaf.mp4

But I would like it to be like in neovim with no jumping:

https://user-images.githubusercontent.com/297678/103330258-81f4ba00-4a15-11eb-97c8-6de79cfa482d.mp4

Is there any way to prevent the jumping?

**Comment by asvetliakov** [comment]
Your cursor is just too 🐎  🐎  🐎  🚗  

Here the behaviour at normal speed:

https://user-images.githubusercontent.com/8881674/103330427-bf7f3480-4a61-11eb-9c31-b73fbff06fa7.mp4

Changing this:
https://github.com/asvetliakov/vscode-neovim/blob/d366766f397954078e5b9eeb01532913fb90b48f/src/cursor_manager.ts#L422

to `TextEditorRevealType.Default` can help but will possibly degrade UX of over jumps

**Comment by asvetliakov** [comment]
I just compiled PR in #479 . Please try attached build to GHA check once them completed.

**Comment by trusktr** [comment]
> Your cursor is just too :racehorse: :racehorse:  :racehorse:  :car:

Oh, I see. :smile: 

> I just compiled PR in #479 .

I think it might be a good change. I also have mappings like this:

```js
nmap <c-j> 5j
nmap <c-k> 5k
```

and those trigger it on a single move, which makes sense based on what you described, but also not like Neovim:

VS Code:

![5-at-a-time-vscode](https://user-images.githubusercontent.com/297678/103330761-b4071b80-4a17-11eb-93ea-826d4bd2265f.gif)

Neovim:

![5-at-a-time-neovim](https://user-images.githubusercontent.com/297678/103330764-b8cbcf80-4a17-11eb-9aa2-c4f787dc46af.gif)

**Comment by trusktr** [comment]
> I just compiled PR in #479 . Please try attached build to GHA checks once they are completed.

Cool, it works exactly as expected! 

Also I tried VS Code's `Go to Definition` command on some things, and I don't experience any issues, it seems to work fine like before. What other other jumps should I test (and how specifically)?

**Comment by asvetliakov** [comment]
>Also I tried VS Code's Go to Definition command on some things, and I don't experience any issues

Is the screen centered after go to def?

>What other other jumps should I test (and how specifically)?

Various jumps from vscodee:
* go to def to same file
* to to def to another file
* open definition aside to same file (`<C-w>gd`)
* Open definition aside to another file
* Peek definition to same file
* Peek def to another file
* outline navigation
* search navigation
* navigation from search results editor

From vim side:
200j or k
jump to mark
search/incsearch jump

**Comment by asvetliakov** [comment]
hm, probably the PR can be improved by taking account into a jump line delta, if < 10 lines or so - use default revealing, otherwise use viewport centering

**Comment by trusktr** [comment]
> Is the screen centered after go to def?

Not quite, but totally not bothersome: it appears on screen, and VS Code highlights it for a brief moment so I know where on screen it is. This video show both go to def in current file, and other file:

https://user-images.githubusercontent.com/297678/103331790-5a552000-4a1c-11eb-9293-72dd15f67b73.mp4

As for the others:

- open definition aside to same file (<C-w>gd) - appears the same as go to def
- Open definition aside to another file - appears the same as go to def in other file
- Peek definition to same file - that was visible in the above video (looks fine)
- Peek def to another file - that was visible in the above video (looks fine)
- outline navigation - looks fine
- search navigation - just fine
- navigation from search results editor - just fine

I noticed if the jump is within the same view (no scroll needed) then the view doesn't adjust, but I think that's totally fine.

**Comment by trusktr** [comment]
Outline jump:


https://user-images.githubusercontent.com/297678/103331998-3e9e4980-4a1d-11eb-8266-73fec755154a.mp4

Search jump is just fine.

**Comment by trusktr** [comment]
`<c-w>gd` just stopped working, now it just does Go to Definition, no split. Will make a new issue.

**Comment by trusktr** [comment]
I think the jumps are working very well, and even if they aren't centered, the un-centering along with the expected cursor movement is much more desirable (at least for me). I can do both just fine now: go to definition (no centering is ok) and move the cursor same as vim, whereas before jumping may have had perfect centering but the cursor movement was unbearable.

**Comment by asvetliakov** [comment]
fixed in 0.0.73
