### ISSUE TITLE
sometimes VS Code matching highlight not updated, it seems

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#478]
For example, here I move onto an identifier with `hjkl` and VS Code highlights the matching occurrences. But when I press `*` and `n` to go to the next matches, VS Code stops showing matches, and finally if I move with `hjkl` again then VS Code shows matches again:

![no-match](https://user-images.githubusercontent.com/297678/103330543-cc2a6b00-4a16-11eb-80bb-0ecf9c770485.gif)

**Comment by asvetliakov** [comment]
this is limitation. till 0.0.70 the HL matching hasn't been working at all. From 0.0.70 cursor movement by +-1 line uses vscode cursor command which triggers HL, anything beyond that sets cursor directly which doesn't trigger HL

**Comment by trusktr** [comment]
Is that a limitation of VS Code? As in, VS Code cursor is in fact moving to a new place, just no HL?

**Comment by trusktr** [comment]
Oops, the title was totally wrong. Updated.

It is indeed a VS Code issue (tested without any extensions). Opened a new issue:

https://github.com/microsoft/vscode/issues/113603
