### ISSUE TITLE
"v k $" - returns cursor to the start of selection

### ISSUE THREAD

**Issue by oeeq** [asvetliakov/vscode-neovim#48]
The title I assume is descriptive. It doesn't matter how many lines are selected. The vertical direction does matter. I can select from top to bottom, but not the opposite.
The cursor needs to be in the middle of the line to reproduce this. If you hit "$" and then try to reproduce, everything will work fine.

**Comment by asvetliakov** [comment]
Thanks for reporting. Looks like only for upward selection, ```vj$``` is fine. should be easy to fix
