### ISSUE TITLE
vim-go extension could not run in vscode

### ISSUE THREAD

**Issue by chaimch** [asvetliakov/vscode-neovim#480]
When I use ctrl+] it will prompt 
![image](https://user-images.githubusercontent.com/12760278/103331746-4a801f00-4aa2-11eb-8317-19546b50194e.png)

Normal when used directly in neovim, see: [vim-go](https://github.com/fatih/vim-go)

**Comment by asvetliakov** [comment]
Using vim side LSP is not supported. Just setup go support in vscode
