### ISSUE TITLE
<c-w><c-c> not working.

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#483]
According to neovim docs,

```
|CTRL-W_CTRL-C|	CTRL-W CTRL-C	   same as "CTRL-W c"
```

so it should also close the window, but currently doesn't. It's a good thing to have because I can press `wcwcwc` a lot faster while my pinky holds `ctrl`. Pressing `ctrl+w c ctrl+w c ctrl+w c` is slower and error prone (easy to accidentally do `<c-w><c-c>`, which is probably why that map exists in neovim).

**Comment by trusktr** [comment]
So far I tried this:

```jsonc
        // Make ctrl+c also send <c-c> to neovim in normal mode. {
            // First modify Neo Vim's escape behavior to work only when not in normal mode, so everything works as expected.
            { "key": "ctrl+c", "command": "vscode-neovim.escape", "when": "editorTextFocus && neovim.init && neovim.mode != normal" },
            // Then, only send <c-c> in normal mode so that our normal mode <c-c> in init.vim works.
            { "key": "ctrl+c", "command": "vscode-neovim.send", "when": "editorTextFocus && neovim.init && neovim.mode == normal", "args": "<c-c>" },
        // }

        { "key": "ctrl+w ctrl+c", "command": "vscode-neovim.send", "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'", "args": "<c-w><c-c>" },
```

but with or without that line, when I press `<c-w><c-c>` the underlying neovim seems to exit (or get stuck), then switching to another tab and coming back fixes it.

**Comment by trusktr** [comment]
A workaround I found is to use these mappings:

```jsonc
            { "key": "ctrl+w ctrl+c", "command": "workbench.action.closeActiveEditor", "when": "editorTextFocus && neovim.init && neovim.mode == normal" },
            { "key": "ctrl+w c", "command": "workbench.action.closeActiveEditor", "when": "editorTextFocus && neovim.init && neovim.mode == normal" },
```

but this overrides the devault ctrl+w mapping, and means I have to add mappings for all the other ctrl+w mappings which no longer work.

**Comment by trusktr** [comment]
> when I press <c-w><c-c> the underlying neovim seems to exit (or get stuck), then switching to another tab and coming back fixes it.

Hmmmmm, regarding that, if I'm on the last window, first time I press `<c-w><c-c>` nothing _appears_ to happen in VS Code except normal becomes unresponsive. But when I press `<c-w><c-c>` again, I see the message `E444: Cannot close the last window` at the bottom of VS Code.

This indicates that Neovim is in fact receiving the key sequences, but perhaps the extension isn't doing the right thing to VS Code in this case.

**Comment by Shatur95** [comment]
Why are you sending this hotkey to Neovim?
```json
    {
        "key": "ctrl+w c",
        "command": "workbench.action.closeEditorsInGroup",
        "when": "!terminalFocus"
    },
```

**Comment by trusktr** [comment]
I'm learning! Adding this to `init.vim` worked:

```viml
nnoremap <C-w>c <Cmd>call VSCodeNotify('workbench.action.closeActiveEditor')<CR>
xnoremap <C-w>c <Cmd>call VSCodeNotify('workbench.action.closeActiveEditor')<CR>
```

Looks like we just need to lines at 

https://github.com/asvetliakov/vscode-neovim/blob/d366766f397954078e5b9eeb01532913fb90b48f/vim/vscode-window-commands.vim#L60-L62

**Comment by Shatur95** [comment]
I think that it would be more convenient to map such things inside VSCode since I see no reason to call the VSCode command through Neovim.
@asvetliakov, what do you think?

**Comment by trusktr** [comment]
Should the extension instead listen for (with autocmds?) when a buffer is closed, and then close the matching window, so it doesn't matter what neovim key combo the user has mapped for closing a window?

Similarly, could it listen for new tabs, and then make the new tab in VS Code, that way it doesn't matter how the user open a new tab (f.e. they might have functions can call `:tabnew`).

**Comment by asvetliakov** [comment]
>I think that it would be more convenient to map such things inside VSCode since I see no reason to call the VSCode command through Neovim.

Just defining any keybinding in vscode started by `ctrl+w` will block any `<C-w>` keybindings for neovim. Vscode just wouldn't pass the key to extension, unless it was explicitly defined

**Comment by Shatur95** [comment]
> Just defining any keybinding in vscode started by ctrl+w will block any <C-w> keybindings for neovim. Vscode just wouldn't pass the key to extension, unless it was explicitly defined

Got it!

**Comment by asvetliakov** [comment]
I think it doesn't work because of `ctrl+c` escape key bound in vscode. If you don't use it you can unbind it and set your mapping in neovim. It should work i think

**Comment by trusktr** [comment]
Yeah, I modified VS Code ctrl+c already, so it doesn't do Escape in Normal mode (see third comment above).

Then, after adding this to `init.vim` it works great:

```viml
nnoremap <c-w><c-c> <cmd>call VSCodeNotify('workbench.action.closeActiveEditor')<cr>
xnoremap <c-w><c-c> <cmd>call VSCodeNotify('workbench.action.closeActiveEditor')<cr>
```

Made a PR for it: https://github.com/asvetliakov/vscode-neovim/pull/494
