### ISSUE TITLE
What are all the values for neovim.mode?

### ISSUE THREAD

**Issue by trusktr** [asvetliakov/vscode-neovim#484]
in when expressions?

**Comment by theol0403** [comment]
https://github.com/asvetliakov/vscode-neovim/blob/d366766f397954078e5b9eeb01532913fb90b48f/src/mode_manager.ts#L34-L44

There are the obvious ones here, insert, visual, normal.
There is however the possibility for others like select and replace, depending if nvim sends them. 

You can reopen if your question was not answered.

**Comment by theol0403** [comment]
Oops, it looks like I gave you a completely wrong response. Will investigate further, sorry.

**Comment by theol0403** [comment]
The best I can find is `:help vim-modes`. It looks like the extension uses the mode directly sent from neovim, but I don't know where the reference for that api is.

I think I found a good reference here though:

https://github.com/asvetliakov/vscode-neovim/blob/d366766f397954078e5b9eeb01532913fb90b48f/src/test/utils.ts#L7-L26

**Comment by asvetliakov** [comment]
@theol0403 has provided completed list. Also i may be wrong but vim/neovim allows to define custom modes too
