### ISSUE TITLE
Intermittent problem with `o`

### ISSUE THREAD

**Issue by awilkins** [asvetliakov/vscode-neovim#485]
<kbd>o</kbd> is properly opening a new line beneath the current one, but on some occasions, the insert cursor is not moving to the new line.

When working properly, I can see the cursor enter insert mode, as if <kbd>i</kbd> had been pushed, and then moving.

ie, if I place the Normal cursor on the `s` of `items()`, the insert cursor briefly exists between `m` and `s` before moving to an opened line (with appropriate whitespace indent) below. However, occasionally, the cursor remains between `m` and `s` instead of moving onto the new line.

```python
    def expand_resources(self, stem) -> Generator[Tuple[str, Any]]:
        resources: OrderedDict[str, Any] = self.data['Resources']

        for name, resource in resources.items():
            yield f"{stem}{name}", resource
```

**Comment by asvetliakov** [comment]
Can you enable debug logging and upload it to somewhere with reproduced behaviour?

**Comment by dreamsmasher** [comment]
Faced the same problem just now (Arch linux), updating to newest version of `neovim-nightly-git` fixed it for me.

**Comment by gokulsoumya** [comment]
`A` also exhibits similar behavior. At times it behaves as though `i` was pressed and *occasionally* moves the cursor in insert mode to the end of the line as it should.

**Comment by asvetliakov** [comment]
>A also exhibits similar behavior. At times it behaves as though i was pressed.

#467

**Comment by asvetliakov** [comment]
@awilkins can you try with 0.0.74?

**Comment by gokulsoumya** [comment]
The problem still persists with v0.0.74 (tested with nvim v0.5.0-dev+990-g0efbab5f5 on Arch)

**Comment by asvetliakov** [comment]
@gokulsoumya Does it happen randomly? can you turn on debug logging and upload log somewhere?

**Comment by gokulsoumya** [comment]
@asvetliakov It seems to be fixed with v0.0.76; both `o` and `O` are working correctly and there are no indentation issues.

**Comment by awilkins** [comment]
Been using it for a day on nvim `0.5.0-dev+1000` and not noticed it happen yet ; don't know what changed in 0.0.76 but the whole setup in general feels snappier. Noticable lag on operations like e.g. `VSCodeCommentary` is much reduced.

**Comment by Dimfred** [comment]
I am experiencing the same problem again. With `o` and `O`. Error happens randomly.
`NVIM v0.5.0-dev+1123-g3fbff98cf`

**Comment by digitaltoad** [comment]
To anyone else that has this problem, I was able to fix it by turning off indent in my nvim config when inside vscode.

```vim
if exists('gvscode')
  filetype indent off
endif
```

**Comment by Dimfred** [comment]
That fixed it for me for `o` but `O` still sometimes fails.

**Comment by echaya** [comment]
I am experiencing the same problem. Pressing o or O enters the Insert mode at where the cursor was. 

Have disabled all other plug-in still experiences the same issue. 
i'm on NVIM v0.5.0-dev+1211-g6db3ba9df with vscode-neovim 0.0.78 on windows
