### ISSUE TITLE
"append" is treated as "insert" since 0.0.70 on some words

### ISSUE THREAD

**Issue by chinux23** [asvetliakov/vscode-neovim#487]
Given a C++ function:

```absl::Status ProblemWord::BlahBlahBlah(const SomeClass& object) const ```

Put VIM in command mode, move cursor to "ProblemWord" and press "e" to get to the end of the word "ProblemWord", press "a" will put the cursor in insert mode between 'r' and 'd', instead of expected position - after 'd'.

This happens since 0.0.70 and I assume it's related to recent changes. Last release 0.0.63 doesn't have this problem.

**Comment by asvetliakov** [comment]
#467 

tldr: install new neovim nightly
