### ISSUE TITLE
<a> and <A> are acting like <i>

### ISSUE THREAD

**Issue by SuperCoolFrog** [asvetliakov/vscode-neovim#490]
This started randomly happening yesterday.  I cannot figure out why it is only happening to be on my one machine I have even after reinstalling.  The ```<a>``` and ```<A>``` are acting like ```<i>```.  Seems like a small issue but it is actually annoying enough to make me switch back to vim until it's fixed.

---

![broken-a](https://user-images.githubusercontent.com/8396079/103384553-cd19d600-4ac4-11eb-9ae5-1ec56704d884.gif)

**Comment by Shatur95** [comment]
#467 

tldr: install new neovim nightly

**Comment by SuperCoolFrog** [comment]
Windows build is broken but when it is fixed I will try
