### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by mizagog** [asvetliakov/vscode-neovim#496]
https://github.com/asvetliakov/vscode-neovim/blob/e61832119988bb1e73b81df72956878819426ce2/vim/vscode-code-actions.vim#L42-L54

i would make a small change:
endPos[2] + 1

this will make so the cursor position itself will be included (this fills more vim like)

**Comment by Shatur95** [comment]
Agree! Could you send a PR for it?

**Comment by theol0403** [comment]
I was going to make a PR for this, but then I realized this has already been implemented. Let me know if this is not the case.
