### ISSUE TITLE
Vimtex's 'VimtexCompile' not working

### ISSUE THREAD

**Issue by lfoscari** [asvetliakov/vscode-neovim#497]
On terminal nvim I can run [vimtex](https://github.com/lervag/vimtex)'s `VimtexCompile` and the latex file is compiled continuously and the preview is updated. From VSCode using this extension nothing happens. Any suggestions?

Neovim version: `NVIM v0.5.0-dev`
VSCode version: `1.52.1`

Thanks

**Comment by asvetliakov** [comment]
use vscode latex extensions
