### ISSUE TITLE
Navigation with `j/k/h/l` breaks, when `lazyredraw` is set

### ISSUE THREAD

**Issue by henil** [asvetliakov/vscode-neovim#508]
Normal navigation does not work when I have `lazyredraw` set in my Neovim config file.

I normally don't use vscode, but currently due to my nightly build of Neovim lagging behind some plugins were breaking my Neovim. So I was using Vscodium (I have not tried on normal vscode, as I suppose they are mostly the same).

Can anyone else reproduce this?

EDIT: Tried on the latest neovim version, still the same issue.

Just for the record, I am on Linux and tested this on both `Vscodium` and `Vscode`.

**Comment by Shatur95** [comment]
> Normal navigation does not work when I have lazyredraw set in my Neovim config file.

What kind of navigation?

> I normally don't use vscode, but currently due to my nightly build of Neovim lagging behind some plugins were breaking my Neovim. So I was using Vscodium (I have not tried on normal vscode, as I suppose they are mostly the same).

You can just [check](https://github.com/asvetliakov/vscode-neovim#determining-if-running-in-vscode-in-your-initvim) for extension in your configuration.

**Comment by henil** [comment]
> What kind of navigation?

Navigations with `j/k/h/l` when in `Normal` Mode. The cursor just doesn't move.

**Comment by Shatur95** [comment]
No, can't reproduce.

**Comment by henil** [comment]
I tried on vscode too. And can still reproduce it :confused:

**Comment by Shatur95** [comment]
Try in clear environment. Maybe the issue in your plugins / settings.

**Comment by henil** [comment]
Clear the whole `init.vim`. Only thing left is:
> set lazyredraw

Still having the issue.

@Shatur95 which OS are you on?

**Comment by Shatur95** [comment]
> @Shatur95 which OS are you on?

Archlinux with latest neovim nightly.

**Comment by henil** [comment]
I am on Arch Linux too, I tried it on a different machine. With a fresh install of `neovim-nightly-bin` and `vscodium-bin` both from AUR. With no other extension/plugin in either vscodium/neovim.

I was able to reproduce it.

**Comment by asvetliakov** [comment]
Need to force `nolazyredraw` in options

**Comment by were** [comment]
I have a similar problem. I am on windows nvim. Let me try `nolazyredraw` first.
