### ISSUE TITLE
extensionPath needs to be escaped or wrapped in quotes

### ISSUE THREAD

**Issue by kyleflan** [asvetliakov/vscode-neovim#509]
https://github.com/asvetliakov/vscode-neovim/blob/9bf0183ac5c96fc8ee78cbec09e639d475f443c0/src/main_controller.ts#L103

If the extension path is not quoted (or escaped), paths with space in them cause the above to throw the error:

```
Unable to init vscode-neovim: Command failed:
C:\Windows\system32\wsl.exe wslpath c:\\Users\\My Name\\.vscode\\extensions\\asvetliakov.vscode-neovim-0.0.76 
wslpath: Invalid argument
```

This is due to the space in the path in 'My Name'.

Adding single quotes around `${extensionPath}` fixed the issue.

**Comment by asvetliakov** [comment]
PR welcome
