### ISSUE TITLE
Gundo not working

### ISSUE THREAD

**Issue by timoxley** [asvetliakov/vscode-neovim#511]
Perhaps there's something up with my config but [Gundo](https://docs.stevelosh.com/gundo.vim/) doesn't seem to work in VSCode with neovim. Just does nothing.

Perhaps this is because Gundo splits the window? Not sure but it'd be great to be able to use Gundo in VSCode.

**Comment by asvetliakov** [comment]
Same as in #459 . Let's track it here

**Comment by timoxley** [comment]
Correct, thanks
