### ISSUE TITLE
Buffer desync in insert mode

### ISSUE THREAD

**Issue by theol0403** [asvetliakov/vscode-neovim#512]
**Steps:**

- Open insert mode
- Type something
- Press backspace
- Everything typed is deleted, plus one character deleted behind where insert mode was started

![Peek 2021-01-04 20-31](https://user-images.githubusercontent.com/16546293/103606689-e4453300-4ecb-11eb-8251-9f59afe0989f.gif)

This is with empty init.vim. It does not happen when macro recording mode is enabled. Latest version of this plugin, nightly nvim appimage from a few days ago.

Not sure if this is directly related to this issue, but I've run into a few normal-mode buf desyncs while working with the above issue. 

Log: https://pastebin.com/YETgTAU3

Btw, I am currently working on keybindings and readme refactor :thumbsup:

**Comment by asvetliakov** [comment]
that doesn't seem correct. the extension disables self in insert mode, so there can't be any desyncs or problems. It must be some other extension or possibly your vscode keybindings? Try with both default

**Comment by theol0403** [comment]
Will do, but the problem goes away with `v0.0.74` and comes back with `v0.0.76`, both versions from the marketplace.

**Comment by asvetliakov** [comment]
so 0.0.75 is fine?

**Comment by theol0403** [comment]
Correct. It still happens with `v0.0.76`, with init.vim, settings (except for neovim path), and keybindings disabled.

**Comment by asvetliakov** [comment]
0.0.76 differs from 0.0.75 only in #504 . But again it shouldn't be applied in insert mode 🤔  . For some reason the backspace key is passed to neovim in insert mode (that's why everything is deleted *plus one character* (because neovim doesn't see your new text yet))

**Comment by asvetliakov** [comment]
>Btw, I am currently working on keybindings

Try to clean manually the extension from `~/.vscode/extensions` and reinstall 0.0.76

**Comment by asvetliakov** [comment]
>For some reason the backspace key is passed to neovim in insert mode

To confirm my guess try to `inoremap <BS> ...` in neovim

**Comment by theol0403** [comment]
Dang it, your guess was correct :flushed: . The mapping worked (and it shouldn't), and clearing the cache solved the problem. I have no idea why by local build caused that to happed however, I will look into it. Thanks for the help!
