### ISSUE TITLE
History in vim command line

### ISSUE THREAD

**Issue by newshowardz** [asvetliakov/vscode-neovim#514]
Could the plugin show and edit the history in vim command line?
Or is this feature already supported (and I miss something in the readme) ?
Thanks.

**Comment by asvetliakov** [comment]
history navigation: `<C-n>/<C-p>`

**Comment by newshowardz** [comment]
The navigation shortcuts work! Thank you, Alexey.

**Comment by guyguy2001** [comment]
Why aren't Up/Down also supported? It seems that neovim supports them by default, and they're the native vscode way of doing this.

**Comment by asvetliakov** [comment]
Because vscode doesn't allow to rebind the basic navigation keys in the quick picker. But feel free to open a PR if you'll be able to find a way around it.

**Comment by guyguy2001** [comment]
Thanks for the quick response, and a big too bad about that
