### ISSUE TITLE
shift+i and a are offset

### ISSUE THREAD

**Issue by lowgos** [asvetliakov/vscode-neovim#516]
Hi everyone,

Love the project and I use it everyday !

I've got a problem that occured the first time at least two weeks ago (I've been on holidays so I don't really know when was the update that broke everything).

# Bugs

- When using `a` in some lines the cursor moves forward
- When using `shift+i` in some lines the cursor doesn't go to the beginning of the line (first character that isn't a white space, as before the bug occured)

I've made a screencap to illustrate:

https://user-images.githubusercontent.com/22097902/103771059-554d2d80-5027-11eb-9752-aefd0bd13f27.mov

# Clues

I've not been able de to reproduce the bug accurately on every kind of line.

- It happens everytime I'm on a JSdoc line (maybe something with comments is broken)
- It doesn't happen on a line inside a JSdoc block if it isn't starting with a `*` (maybe JSdoc is handled with specific movements idk)
- It sometimes happens in code, but I've not been able to reproduce it for the screencap as it is intermittent.

# Details

- I'm on macOS 10.15.7
- I never see any error popping up
- I've tried more than one version of vscode-neovim
  - 0.0.76
  - 0.0.73
  - 0.0.65
- I've installed every version of neovim linked in issues of this repository having relation to `shift+i`, `shift+a`, `a`, and `i`.
  - neovim --HEAD (v0.4)
  - neovim nightly from tarball of the official repo
  - neovim nightly from `jason0x43/homebrew-neovim-nightly`
- I've killed VSCode everytime
- I've disabled every extension but vscode-neovim

**Comment by lowgos** [comment]
Yes and it definetely is related to the tab indentation feature !

At least for the `a`.

Here is a screencap with indentation on `tab` equivalent to `4 spaces`

https://user-images.githubusercontent.com/22097902/103781749-0909e980-5037-11eb-9cc4-8bccd33c2d90.mov

**Comment by asvetliakov** [comment]
Check this build: https://github.com/asvetliakov/vscode-neovim/suites/1778455707/artifacts/33977383

**Comment by lowgos** [comment]
I don't really understand why but I've uninstalled the extension and installed your build. It works like a charm.

I then uninstalled the extension again and replaced it with the one from the store and it still works fine...
Do you understand any of this ? 

Thanks for your time. I'll keep you posted in case the bug reappears but your investigation helped me mitigate the problem

**Comment by asvetliakov** [comment]
>I then uninstalled the extension again and replaced it with the one from the store and it still works fine...
>Do you understand any of this ?

Yes, sometimes vscode caches local version and won't replace it with new one from store if it has same version number
