### ISSUE TITLE
Remote SSH Install

### ISSUE THREAD

**Issue by sweetgiorni** [asvetliakov/vscode-neovim#518]
Not really a bug, but it should be noted in the installation documentation that if you're using VS Code's Remote SSH extension, neovim needs to be installed on the host machine, not the remote. It took me a minute to figure that out :)

**Comment by hgezim** [comment]
@sweetgiorni How did you install it with remote SSH?

**Comment by sweetgiorni** [comment]
I played around with this for a bit and I'm unable to recreate the issue. Maybe it was fixed somewhere, or maybe it was a figment of my imagination.

**Comment by hgezim** [comment]
@sweetgiorni Are you using it with remove NeoVIM or local?

**Comment by hgezim** [comment]
Looks like a remote nvim is not supported: https://github.com/asvetliakov/vscode-neovim/issues/225
