### ISSUE TITLE
[Question] Insert mode mappings

### ISSUE THREAD

**Issue by bogdan0083** [asvetliakov/vscode-neovim#52]
Hello! Thank you for such an awesome plugin! Absolutely love it! ❤️ 

I've been trying to set up a few keymappings for insert mode. Most of them are not of a big importance, but this one is an absolute must for me and it doesn't work:
```
imap jj <Esc> :call VSCodeNotify('vscode-neovim.escape')<CR>
```
It doesn't even trigger the chord on the first `j`, like no reaction whatsoever.

Am I doing something wrong? Thanks!

**Comment by bogdan0083** [comment]
Whoops, I just realized that insert mode is run completely by VSCode, so those kind of mappings probably won't work. I'll try to add the chords through vscode settings.

**Comment by bogdan0083** [comment]
Alright, I figured it out. Adding the keymap to vscode's `keybindings.json` with `neovim.mode == insert` works great!
```
    {
        "key": "j j",
        "command": "vscode-neovim.escape",
        "when": "editorTextFocus && neovim.mode == insert"
    }
```

It's probably a good idea to add a note on how to add key mappings for insert mode (with the above example). I'll send a PR tomorrow if you don't mind.

**Comment by bogdan0083** [comment]
I tested my solution and it doesn't work very well. It works fine but all key combinations with the first chord has become blocked `like jk, jd, js etc.` and you can't type them. It seems like this issue is more of VSCode problem, so I'm gonna close it for now.

**Comment by asvetliakov** [comment]
Yes, something like ```jj``` or ```jk``` for the escape key won't work. And i have no plans to listen to events in insert mode unless [this](https://github.com/microsoft/vscode/issues/75627) or [this](https://github.com/microsoft/vscode/issues/65876) will be fixed. Sorry for inconvience!

**Comment by AndyPro720** [comment]
For anyone looking for the solution this seems to work well

 {
    "command": "vscode-neovim.compositeEscape1",
    "key": "j",
    "when": "editorTextFocus && neovim.ctrlKeysInsert && neovim.init && neovim.mode == 'insert'",
    "args": "j"
  },

**Comment by guyguy2001** [comment]
It seems like vscode are working on fixing this issue: https://github.com/microsoft/vscode/issues/65876#issuecomment-1078827200
(Pinging @asvetliakov @theol0403 to make sure you don't miss this)

**Comment by Toavina23** [comment]
{
		"command": "vscode-neovim.escape",
		"key": "j k",
		"when": "editorTextFocus && neovim.ctrlKeysInsert && neovim.init && neovim.mode == 'insert'",
		"args": "jk"
	}

this work for me right now

**Comment by miozus** [comment]
> { "command": "vscode-neovim.escape", "key": "j k", "when": "editorTextFocus && neovim.ctrlKeysInsert && neovim.init && neovim.mode == 'insert'", "args": "jk" }
> 
> this work for me right now

you are genius! and love you ~

**Comment by nathanafranlin** [comment]
i used this and it worked for me:
`{
        "key": "j k",
        "command": "vscode-neovim.escape",
        "when": "editorTextFocus && neovim.mode == insert",
        "args": "jk"
    }`
