### ISSUE TITLE
Neovim Nightly

### ISSUE THREAD

**Issue by Qwerty-Space** [asvetliakov/vscode-neovim#524]
It seems that the neovim repo removed the nightly release and so it fails to install now

**Comment by asvetliakov** [comment]
Unfortunately i can't help here, it's not neovim repository and i'm not neovim maintainer

**Comment by Qwerty-Space** [comment]
I'm just pointing out that there's going to be problems.  Would it be possible to provide a binary with the extension, or stop relying on it?

**Comment by asvetliakov** [comment]
>Would it be possible to provide a binary with the extension
No. It's possible to download the binary automatically, but it won't solve the problem when it's not available

> or stop relying on it?
No
