### ISSUE TITLE
autocmd runs multiple times than expected

### ISSUE THREAD

**Issue by slbb** [asvetliakov/vscode-neovim#525]
I put autocmd in init.vim for input method selecting. It works well in neovim.
```
augroup im_select
    autocmd!
    autocmd InsertLeave * silent !c:\im-select.exe 1033
    autocmd InsertEnter * silent !c:\im-select.exe 2052
    autocmd BufRead * silent !c:\im-select.exe 1033
    autocmd CmdlineLeave * silent !c:\im-select.exe 1033
    autocmd CmdlineEnter * silent !c:\im-select.exe 2052
augroup END
```
 But in vscode-neovim it runs multiple time than expected. When I enter insert mode (now im switch to 2052), then insert multiple new lines via `<Enter>` or vscode command `editor.action.insertLineBefore` or `editor.action.insertLineAfter`, and then go back to normal mode the im-select not only switch to 1033 but runs extra times swiching bewteen 2052 and 1033 (one extra execution per new line I just insert), and the vim command panel recurs when it runs.
I remove `CmdlineLeave` and `CmdlineEnter` lines in augroup, vim command panel doesn't recurs anymore. But the extra execution problem still exists if there are still `InsertLeave` and `InsertEnter` autocmds.

**Comment by slbb** [comment]
I roughly read the code. Is that when I insert new lines in insert mode then back to normal mode, vscode-neovim syncs my inputs to nvim backend line by line, with entering and leaving insert mode per line?
The issue doesn't happen when I break a line in the middle to multiple lines (<CR> in the middle of line), or change multiple lines' contents. It only happens when I insert a conpletely empty new line ( <CR> at end of line or vscode insertLine commands ). I wonder why it behaves not the same as breaking lines.

**Comment by asvetliakov** [comment]
@slbb Does the problem still happen if you remove `BufRead` here ?

**Comment by slbb** [comment]
> @slbb Does the problem still happen if you remove `BufRead` here ?
> 
> Can you try with empty init.vim only with these `autocmd`s enabled?

Thank you for the reminding. I tried several times with commenting different lines in init.vim. finally located the problem.
```
fun! Exec(cmd)
	exe a:cmd
	return ''
endf
inoremap <NL> <C-r>=Exec("normal o")<CR>      " <C-Enter> to insert new line in insert mode
```
Maybe vscode-neovim recognizes `Enter` as `<NL>` and calls the function.
Anyway, vscode doesn't need this. I removed it and solved the problem.
