### ISSUE TITLE
Tabstop/shiftwidth settings ignored

### ISSUE THREAD

**Issue by jpear1** [asvetliakov/vscode-neovim#529]
## Summary
`:set ts=2 sw=2` has no effect

## Steps to reproduce
```
touch ~/test.txt
code ~/test.txt
:set ts=2 sw=2
```
Observe that tab inserts 4 spaces

## Other comments
VSCode's auto tab detection features work pretty well, I'm not sure if it's worth trying to bypass them. Maybe there could be a list of Neovim features that are knowingly not supported, in the wiki or readme. Or maybe this isn't an issue at all, in which feel free to close this.

**Comment by asvetliakov** [comment]
Tab related settings are controlled by vscode side
