### ISSUE TITLE
Doesn't work in diff editor view

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#53]
```viewColumn``` is undefined. Possible workaround is to create separate window for undefined view columns

**Comment by DanielPower** [comment]
Is there currently any workaround for this? It's the main thing that's keeping me using the other vim extension, since I use the diff editor extensively.

**Comment by asvetliakov** [comment]
Unfortunately there is no workaround here, but i'm working on supporting diff/other composite views right now.
