### ISSUE TITLE
vim-sandwich underlining not displaying

### ISSUE THREAD

**Issue by MaximoMachado** [asvetliakov/vscode-neovim#533]
In Neovim, [vim-sandwich](https://github.com/machakann/vim-sandwich) has a feature in which it underlines the text that you are about to surround. It also will highlight the background of the surrounding characters if you are attempting to change or delete them.

In VSCode, currently all that happens is the character your cursor is over gets underlined but nothing else will appear.

**Comment by Shatur95** [comment]
Yes, the additional highlighting is missing.

**Comment by MaximoMachado** [comment]
I think I was able to solve it using the same strategy that was used for the quickscope plugin. This doesn't fix the issue with the background highlighting when changing the surrounding not appearing though.

Here's an example of what you should put in your config file to get it working correctly. 

![image](https://user-images.githubusercontent.com/8076619/105328802-70c74500-5b9e-11eb-9573-1a5e4cdf020d.png)

**Comment by Shatur95** [comment]
Could you put it as a text?

**Comment by MaximoMachado** [comment]
Sure thing.

```
if exists('g:vscode')

    highlight OperatorSandwichBuns guifg='#edc41f' gui=underline ctermfg=172 cterm=underline 
    highlight OperatorSandwichAdd guifg='#b1fa87' gui=underline ctermfg=172 cterm=underline
    highlight OperatorSandwichDelete guifg='#b1fa87' gui=standout ctermfg=172 cterm=underline
    highlight OperatorSandwichChange guifg='#b1fa87' gui=standout ctermfg=172 cterm=underline
endif
```

**Comment by MaximoMachado** [comment]
So I was able to get the background colors working as well. However, on a different note, I've been having an issue where the cursor stays as an underline rather than a full block after using sandwich. Unfortunately, I can't reliably reproduce it, it seems to happen at random, but it's probably more likely that I can't figure out the pattern. Usually if I yank afterwords the cursor will return to a full block.

**Comment by samvv** [comment]
The solution of @MaximoMachado is now in the wiki: https://github.com/asvetliakov/vscode-neovim/wiki/sandwich.vim

I'm closing this issue for now. If other plugins are having the same problems then we probably should create a separate issue related to way we handle highlighting.
