### ISSUE TITLE
Escape does not close parameter hints or problems popup

### ISSUE THREAD

**Issue by Gelio** [asvetliakov/vscode-neovim#534]
Hey, 

Thanks for putting together this great extension. This is what got me into vim/neovim a few days ago, and I'm loving it.

I've noticed that I cannot close the popup with parameter hints or the problems popup, which is usually done using the Escape key.

For example:

Parameter hints (triggered using `gh`):
![image](https://user-images.githubusercontent.com/889383/105414357-a8ce9680-5c37-11eb-803c-c1b61f1467ff.png)

Problems popup (triggered using Alt + F8):
![image](https://user-images.githubusercontent.com/889383/105414491-d9aecb80-5c37-11eb-8902-bec3972643bb.png)

I assume this is because the neovim extension handles the Escape key itself and calls something along the lines of `preventDefault` on the event, which does not let VSCode handle it too.

I changed the `when` condition for the `Escape key` keybinding to:

```ts
editorTextFocus && neovim.init && !markersNavigationVisible && !parameterHintsVisible
```

(essentially, I added ` && !markersNavigationVisible && !parameterHintsVisible`)

and the Escape key started working after that.

I would happily contribute a fix to the extension if you're ok with that 🙂 I wanted to report it first and let you handle it yourself if you'd like

**Comment by jose-elias-alvarez** [comment]
Nice solution! This was driving me crazy, but your solution works perfectly. I'd love to see this integrated into the extension, since I'm sure we're not the only ones.

**Comment by thekarel** [comment]
I was very happy to find this solution, but after modifying the `when` condition leaving insert mode sometimes takes 2-3 `Esc` taps. Might be something with my setup?

**Comment by Gelio** [comment]
> I was very happy to find this solution, but after modifying the `when` condition leaving insert mode took 2-3 `Esc` taps sometimes, so now I'm back to `shift+Esc`. Might be something with my setup?

I didn't encounter such problems myself, so looks like something on your end may be capturing the Esc keys. You could try disabling all extensions aside from neovim and see if that helps, and then enable extensions one by one to see which one causes the problem

**Comment by thekarel** [comment]
> > I was very happy to find this solution, but after modifying the `when` condition leaving insert mode took 2-3 `Esc` taps sometimes, so now I'm back to `shift+Esc`. Might be something with my setup?
> 
> I didn't encounter such problems myself, so looks like something on your end may be capturing the Esc keys. You could try disabling all extensions aside from neovim and see if that helps, and then enable extensions one by one to see which one causes the problem

Haven't happened since, so the solution seems fine to me 👌🏻

**Comment by b1m1nd** [comment]
I edited mine so it would also work with diff windows. Thank you for this if you feel the same way update your PR and lets hope they merge it, this is a must :) 
				```"when": "inDiffEditor && editorTextFocus && neovim.init && !markersNavigationVisible && !parameterHintsVisible"```
