### ISSUE TITLE
Convert selection to VS Code selection for "find in project"

### ISSUE THREAD

**Issue by brandoncc** [asvetliakov/vscode-neovim#535]
First, thanks for this awesome extension, it works great.

I often like to select a range of text and then search for it. Would it be possible to make the selection turn into a real VS Code selection when I press `cmd+shift+f`? Any selection is auto-filled into the search input, and this would be very useful.

**Comment by yogeshdhamija** [comment]
I wrote a vim plugin that might be helpful to you: https://github.com/yogeshdhamija/find-in-dir-helper.vim

Copied from the readme:

> This plugin also works with the VSCode plugin, 'VSCode Neovim'. There, it performs the analagous action of opening the editor's search panel (with pre-populated text if applicable).

**Comment by mizagog** [comment]
take a look at [this](https://github.com/asvetliakov/vscode-neovim/blob/f7aad4c3205f9b59762c725243b56bfc2b6d129b/vim/vscode-code-actions.vim#L42) 
it is what i use.

**Comment by vlwkaos** [comment]
under vscode conditional config
```
command! FindInFileS call VSCodeNotify('workbench.action.findInFiles', {'query': @p})
xnoremap <silent> <Leader>f "py<Esc>:FindInFileS<CR>
```
what it does is, it copies your selection to 'p' register then use it as a query for the find in files command.

**Comment by yogeshdhamija** [comment]
Without overwriting the 'p' register:

```viml
function! FindSelectedTextInDir() abort
    normal! gv
    if(exists("g:vscode"))
        let startPos = getpos("v")
        let endPos = getpos(".")
        call VSCodeNotifyRangePos("workbench.action.findInFiles", startPos[1], endPos[1], startPos[2], endPos[2]+1, 1)
    endif
endfunction

xnoremap <Leader>f <Esc>:call FindSelectedTextInDir()<CR><Esc>
```

**Comment by vlwkaos** [comment]
> Without overwriting the 'p' register:
> 
> ```viml
> function! FindSelectedTextInDir() abort
>     normal! gv
>     if(exists("g:vscode"))
>         let startPos = getpos("v")
>         let endPos = getpos(".")
>         call VSCodeNotifyRangePos("workbench.action.findInFiles", startPos[1], endPos[1], startPos[2], endPos[2]+1, 1)
>     endif
> endfunction
> 
> xnoremap <Leader>f <Esc>:call FindSelectedTextInDir()<CR><Esc>
> ```

When I tried this, it did not properly select characters containing non-english characters, so if you only use US keyboard this would do, but otherwise using the register is the only option working as far as I know.

**Comment by yogeshdhamija** [comment]
> > Without overwriting the 'p' register:
> > ```viml
> > function! FindSelectedTextInDir() abort
> >     normal! gv
> >     if(exists("g:vscode"))
> >         let startPos = getpos("v")
> >         let endPos = getpos(".")
> >         call VSCodeNotifyRangePos("workbench.action.findInFiles", startPos[1], endPos[1], startPos[2], endPos[2]+1, 1)
> >     endif
> > endfunction
> > 
> > xnoremap <Leader>f <Esc>:call FindSelectedTextInDir()<CR><Esc>
> > ```
> 
> When I tried this, it did not properly select characters containing non-english characters, so if you only use US keyboard this would do, but otherwise using the register is the only option working as far as I know.

Oof. That's not ideal. Do you have some sample text I can use to diagnose this?

**Comment by theol0403** [comment]
> When I tried this, it did not properly select characters containing non-english characters, so if you only use US keyboard this would do, but otherwise using the register is the only option working as far as I know.

I don't know how to fix this, but I think it needs to be fixed somewhere else in this plugin, as there is ideally nothing wrong with @yogeshdhamija 's implementation (which was taken from code already used to transfer C-S-P). Unfortunately, I think a solution that does not require a register is better, even if it might not work in your case. You are welcome to keep your code in your init.vim.
