### ISSUE TITLE
Highlighting with QuickScope, Sandwich, and Easymotion stopped working

### ISSUE THREAD

**Issue by MaximoMachado** [asvetliakov/vscode-neovim#537]
I'm not exactly sure what caused this but suddenly quick-scope's highlighting stopped appearing in vscode. I still have the setting to set the highlighting in my init.vim so I'm not exactly sure what's causing the issue.

In the same vein, easymotion's search would darken all the text besides the keys to navigate to the results but now this isn't happening at all.

Sandwich as well isn't displaying any highlighting.

**Comment by asvetliakov** [comment]
try revert plugin HL settings (ignoreHighlights, etc) to default values

**Comment by MaximoMachado** [comment]
Thanks, I appreciate the help. I believe I was able to figure out the problem. I think TreeSitter's syntax highlighting was conflicting somehow with the highlighting in VSCode. Turning highlighting off solved the issue.
