### ISSUE TITLE
GNOME remapped keys not respected

### ISSUE THREAD

**Issue by jpear1** [asvetliakov/vscode-neovim#542]
GNOME escape and caps lock key swap isn't respected by VSCode-Neovim on Arch Linux.

## Steps to reproduce

* Swap caps lock and escape keys using gnome-tweaks (Keyboard and Mouse -> Additional Layout Options -> Caps Lock Behavior -> Swap Esc and Caps Lock).
* Open VSCode and open a file with VSCode-Neovim installed
* Press `Ctrl-Shift-P` to open prompt
* Close prompt by pressing `Caps Lock` (remapped to `Esc`)
(Observe that remap is working as expected in VSCode)
* Enter insert mode by pressing `i`
* Press `Caps Lock` (remapped to `Esc`)
(Observe that insert mode is not exited by what is supposed to be an `Esc` keypress)
* Press `Esc` (remapped to `Caps Lock`)
(Observe that insert mode is exited (unexpected behavior), AND caps lock is enabled (expected behavior))

This a pretty minor bug, and may not even be caused by VSCode-Neovim (could be a bug in the Neovim server, I don't know). I know this project is pretty pressed for maintainers, so no pressure to fix this. I'm leaving this issue here with the hope that I'll get around to fixing it at some point.

**Comment by timloudon** [comment]
Check out closed issue #2859 - https://github.com/VSCodeVim/Vim/issues/2859

Solved the problem for me

**Comment by jpear1** [comment]
Yep, this fixed it for me too. Thanks!
