### ISSUE TITLE
vscode-easymotion (fork) triggers linter

### ISSUE THREAD

**Issue by zSucrilhos** [asvetliakov/vscode-neovim#544]
Hi! First of all iId like to thank you for the amazing work! 
The problem is that when using easymotion, the linter gets triggered, as it actually changes the actual code as seen in the video below:

https://user-images.githubusercontent.com/37763819/106344848-41899580-627a-11eb-8dd6-5c8c9430355c.mp4

This is a similar issue to the vim version of easymotion: https://github.com/neoclide/coc.nvim/issues/110
On vim, since I'm using CoC, I managed to solve the issue thanks to ecogest, by disabling the linter once entering easymotion mode:
![image](https://user-images.githubusercontent.com/37763819/106344915-89102180-627a-11eb-8b1d-a14ac73257ac.png)

**Comment by asvetliakov** [comment]
https://github.com/asvetliakov/vscode-neovim#vim-easymotion

**Comment by zSucrilhos** [comment]
I'm already using the fork:
![image](https://user-images.githubusercontent.com/37763819/106367057-0cc71e00-630e-11eb-8136-2c5a7595ab75.png)
![image](https://user-images.githubusercontent.com/37763819/106367081-32ecbe00-630e-11eb-9341-41fb3e9e2fd4.png)

What  think might be happening is that vscode's neovim is using the original vim-easymotion that I have setup on my `init.vim`. For the vscode neovim, I'm using another file, that i named `vscode.vim`

**Comment by Dimfred** [comment]
I had the same issue. It is definetly triggered when both easymotion plugins are used along side. I tried to make a distinction `if g:vscode` in the plugin load part, but it didn't help. Removing the original `easymotion` completly and only loading the `vscode-easymotion` helped and everything now works.
