### ISSUE TITLE
How to hide the function tooltip?

### ISSUE THREAD

**Issue by CavalloneChen** [asvetliakov/vscode-neovim#549]
I wonder how to hide the function tooltip with keyboard shortcut. Pressing Esc doesn't do the trick.
![image](https://user-images.githubusercontent.com/28266566/107235334-8d4cf380-6a5f-11eb-8212-6122e7591efa.png)

**Comment by Shatur95** [comment]
`Shift` + `Esc` by default.

**Comment by CavalloneChen** [comment]
> `Shift` + `Esc` by default.

Thanks! That worked.
