### ISSUE TITLE
Does not work on macOs

### ISSUE THREAD

**Issue by dan-cooke** [asvetliakov/vscode-neovim#55]
### Description
When extension is enabled and loaded, I cannot input any characters or switch modes. No VIM like status bar is visible either (if thats a feature).

I am migrating from the Vim extension for vscode, and I had just uninstalled it before installing this extensions if that matters.

## Installed Extensions
code --install-extension aaron-bond.better-comments
code --install-extension ahmadawais.shades-of-purple
code --install-extension apollographql.vscode-apollo
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension azemoh.one-monokai
code --install-extension batisteo.vscode-django
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bungcip.better-toml
code --install-extension burkeholland.simple-react-snippets
code --install-extension chrmarti.regex
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension crazywolf.smali
code --install-extension dbaeumer.vscode-eslint
code --install-extension DengSir.template-generator-vscode
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eppz.eppz-code
code --install-extension Equinusocio.vsc-material-theme
code --install-extension eriklynd.json-tools
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension HookyQR.beautify
code --install-extension idleberg.hopscotch
code --install-extension jchannon.csharpextensions
code --install-extension johnpapa.winteriscoming
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension jprestidge.theme-material-theme
code --install-extension kosz78.nim
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension liviuschera.noctis
code --install-extension magicstack.MagicPython
code --install-extension mikestead.dotenv
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension oderwat.indent-rainbow
code --install-extension OfHumanBondage.react-proptypes-intellisense
code --install-extension PKief.material-icon-theme
code --install-extension rogalmic.bash-debug
code --install-extension rust-lang.rust
code --install-extension serayuzgur.crates
code --install-extension Shan.code-settings-sync
code --install-extension shanoor.vscode-nginx
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shinnn.stylelint
code --install-extension slevesque.shader
code --install-extension spywhere.guides
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension Unity.unity-debug
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension WallabyJs.quokka-vscode
code --install-extension wesbos.theme-cobalt2
code --install-extension wholroyd.jinja
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme

### Neovim Vim Version
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local
```

### System Info
OS: Mac OS Mojave 10.14.6
VSCode: 1.40.1

**Comment by asvetliakov** [comment]
What extension version? I believe i fixed it in 0.0.34

**Comment by dan-cooke** [comment]
> What extension version? I believe i fixed it in 0.0.34

😆 I literally just installed latest version there now and its working! Thanks!

**Comment by hugolundin** [comment]
I have the same issue with `0.0.34`.

**Comment by asvetliakov** [comment]
@hugolundin mac os too?
1. make sure you've specified the full path to neovim and restarted vscode
2. try to temporarly move/rename your init.vim and see if it works without config
3. make sure you're not affected by [this brew issue](https://github.com/neovim/neovim/issues/11411)

**Comment by hugolundin** [comment]
Apparently I was running neovim 0.3.8. When updating to the latest release it works. Thank you for a quick reply and sorry for bothering you 👍
