### ISSUE TITLE
Cursor in edit mode jumps back to where it was in the normal mode

### ISSUE THREAD

**Issue by saif97** [asvetliakov/vscode-neovim#554]
First of all, thank you for this awesome extension. I literally can't use VS code w/o it. 
I've an issue where the cursor in edit mode jumps back to where it was previously in the normal mode (see gif below). 
- This issue only happens on python projects. 
- It happens when I open a python file => try to edit the setting.json. However, if I try to edit setting.json from a dart / golang project it works just fine. 
- I've disabled all but neo vim extensions & commented all but the necessary setting (pic below) no luck. 
- tried it on both vs code version 1.53 & 1.51 
- tried extension v 0.0.5 & the latest. 

Note: I haven't posted that many github issues. please let me know if I'm missing sth. 

![Feb-13-2021 23-00-31](https://user-images.githubusercontent.com/13847797/107860604-2bbac980-6e51-11eb-80a7-2d3e1c8dc09c.gif)

![image](https://user-images.githubusercontent.com/13847797/107860474-91f31c80-6e50-11eb-8d91-2ad96ced7aec.png)

**Comment by jeffersonchen-tw** [comment]
Same issue

**Comment by saif97** [comment]
I can conform that deleting the Kite companion mac app seems to be the cause here even if you delete Kite extension as well. As soon as I install them,  everything went back to normal.

**Comment by jeffersonchen-tw** [comment]
@saif97 You are right!

**Comment by JohnFinn** [comment]
I have the same issue. Don't you think, that this extension shouldn't rely on Kite?
I believe this issue should be reopened and the bug properly fixed.

**Comment by JohnFinn** [comment]
Just found out that I had `.config/nvim/pack/kite`.
Removing `.config/pack` (I didn't have anything except kite there) have solved the problem.
