### ISSUE TITLE
Vim highlight search show wrong visual range

### ISSUE THREAD

**Issue by Yukaii** [asvetliakov/vscode-neovim#56]
![neovim-search-highlight](https://user-images.githubusercontent.com/4230968/69495486-7d043380-0f02-11ea-927b-8fd6e72a8357.gif)

**Comment by asvetliakov** [comment]
@Yukaii Thanks for reporting. What version of extension are you using? Did you do anything before in this file?

**Comment by asvetliakov** [comment]
![gif](http://g.recordit.co/FqyJpuit5C.gif)

**Comment by Yukaii** [comment]
NVIM v0.4.3
extension: 0.0.34

And maybe it's caused by my **lots of** vim plugins 😅  , I'll try to disable some of them and report it here.

**Comment by Yukaii** [comment]
Also the visual selection doesn't work as VSCode, it should only display active cursor at ends.

![Screen Shot 2019-11-25 at 7 35 25 AM](https://user-images.githubusercontent.com/4230968/69503591-2cb6c100-0f56-11ea-9a13-d2804118a21c.png)

**Comment by asvetliakov** [comment]
>Also the visual selection doesn't work as VSCode, it should only display active cursor at ends.
This is extension addition - visual line/block modes spawn multiple cursors. I may put it under a conf flag later

**Comment by Yukaii** [comment]
I found that it's `set number` config causing this.

**Comment by asvetliakov** [comment]
Thank you for your research. If you'll find anything else which breaks extension - don't hesitate to send a PR to reset the value [here](https://github.com/asvetliakov/vscode-neovim/blob/e3a05ed3f1d8801ee9f3c3f48a26f7e37bf1e388/vim/vscode-neovim.vim#L21)
