### ISSUE TITLE
filtering using external commands causes neovim plugin to become unresponsive

### ISSUE THREAD

**Issue by benwbooth** [asvetliakov/vscode-neovim#566]
Using VSCode 1.54.0, neovim  plugin version 0.0.78, NVIM v0.5.0-nightly, macOS Big Sur 11.2.2. 

To reproduce, enter the following in a blank vscode buffer:

10
9
8
7
6
5
4
3
2
1

Then select all 10 lines, and type ":" to enter ex mode, then enter:

'<,'>!sort

Now the neovim plugin is completely unresponsive, no key commands work at all. The user must run Reload Window to restore the plugin functionality.

I didn't see any errors in the developer console. What's the best way to debug errors with the neovim plugin? Is there a log file somewhere?

Thanks!

**Comment by trkoch** [comment]
I can't reproduce this. Did you try with vanilla `.vimrc`?

**Comment by benwbooth** [comment]
Things I've tried:

deleted ~/.vimrc
deleted ~/.config/nvim/init.vim
deleted ~/.vscode
deleted ~/Library/Application Support/Code

I'm still seeing the exact same problem. I'm using neovim 0.5.0-nightly from homebrew and the latest VSCode. I've tried the same on two different machines with the same result.

**Comment by benwbooth** [comment]
I figured out the problem. I had some network folders on my PATH. For some reason those were causing vscode-neovim to hang for a long time when running ! filter commands. This behavior didn't occur when running nvim or vim from the terminal. By removing the network paths from my PATH I can work around the problem.
