### ISSUE TITLE
How to add custom shortcut for visual block?

### ISSUE THREAD

**Issue by rohitkrishna094** [asvetliakov/vscode-neovim#567]
In my normal command line nvim(that is in my windows command prompt), I can enter **visual block** using `ctrl + q` or `ctrl + v`. Also since I am new to nvim, I would like to keep `ctrl + v` as paste and instead only use `ctrl + q` to enter **visual block mode**.

In my keybindings, I was able to disable ctrl+v and get back simple paste functionality like so.

```
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+v"
  },
```

In the same way, I would like to add a shortcut for `ctrl+q` which allows me to enter visual block mode.

I see that for ctrl+q, there is some stuff in keybindings.json already. 

```
  {
    "key": "ctrl+q",
    "command": "-workbench.action.quickOpenNavigateNextInViewPicker",
    "when": "inQuickOpen && inViewsPicker"
  },
  {
    "key": "ctrl+q",
    "command": "-workbench.action.quickOpenView"
  },
```

**Comment by samvv** [comment]
I'm not entirely sure, but I believe you can fix this by adding a keybinding on the Neovim side. Somewhere in your `init.vim`, alias `<C-q>` to map to `<Esc>v` or something similar. Just make sure there are no conflicting bindings in your VSCode.

Let me know if you're still having this issue and whether this solves it for you. In the mean time, I'm going to close this issue. You can always re-open it if there's a bug.
