### ISSUE TITLE
How to use vscode debugger?

### ISSUE THREAD

**Issue by lhk** [asvetliakov/vscode-neovim#568]
Hi,
this extension seems like a great way to start using modal editing :)
After working through some tutorials on how to use vim, I feel more or less comfortable with editing text.
Now I'd like to use this for actually developing something.

Is there a way to use the vscode debugging functionality?
How do I set a breakpoint, step, continue, run to cursor, jump to eval terminal, ... ?

Thanks for developing this amazing plugin :)

**Comment by dschuessler** [comment]
I'm not the developer. But debugging should work exactly like it does without the neovim extension. Every resource on debugging with VSCode should apply. Is this not the case with you?

**Comment by samvv** [comment]
A bit late, but here's a snippet that I use to control the debugger:

```vim
nnoremap <silent> <leader>R <Cmd>:call VSCodeNotify('workbench.action.debug.start')<CR>
nnoremap <silent> <leader>b <Cmd>:call VSCodeNotify('editor.debug.action.toggleBreakpoint')<CR>
nnoremap <silent> c <Cmd>:call VSCodeNotify('workbench.action.debug.continue')<CR>
nnoremap <silent> s <Cmd>:call VSCodeNotify('workbench.action.debug.stepOver')<CR>
```

 - `<leader>-Shift-r` start new debug session
 - `<leader>-b` toggle breakpoint
 - `c` continue execution
 - `s` step over the current instruction

Where `<leader>` is `,` in my Vim but I believe it is `\` by default. All of these commands only work in normal mode.

You get the idea. Feel free to edit it to suit your needs. There might be a way to use `c` and `s` for something else but it would require something more complex that checks whether there is a debug session running. Not sure if that is feasible with the current API.

**Comment by samvv** [comment]
Closing this issue. If something is not clear let me know.
