### ISSUE TITLE
Can't bind actual [Escape] key to neovim.escape. 

### ISSUE THREAD

**Issue by anhyeast** [asvetliakov/vscode-neovim#57]
I can't seem to bind the actual escape key to neovim.escape.  Is this intended?

**Comment by asvetliakov** [comment]
No. How do you bind it? I just tried by putting:
```json
    {
        "key": "Escape",
        "command": "vscode-neovim.escape"
    }
```
and it works fine

**Comment by anhyeast** [comment]
Wow, it is working for me.  Thanks alot.  Awesome extension so far

**Comment by rayzorben** [comment]
@asvetliakov Where do you put this? I am trying to put this in my user settings.json and it will not auto-complete "key" or "command"

**Comment by asvetliakov** [comment]
@rayzorben You need to put it in your vscode's ```keybindings.json```. Execute ```Preferences: Open Keyboard Shortcuts (JSON)``` from vscode command palette. Setting the key through vscode keybindings UI will also work.

**Comment by rayzorben** [comment]
Thanks, it was just hiding, I couldn't find it!
