### ISSUE TITLE
How can I get the scrolloff work?

### ISSUE THREAD

**Issue by cyt-codemaker** [asvetliakov/vscode-neovim#570]
I try to do it through setting scrolloff in init.vim and set setting it in vim command line, but it still don't work. Is this feature not currently supported?

**Comment by Shatur95** [comment]
Yes, [the option](https://github.com/asvetliakov/vscode-neovim/blob/6469c216f30c4bf29d5718f6d3fe99d517a33db0/vim/vscode-options.vim#L16) is hardcoded.

**Comment by cyt-codemaker** [comment]
> Yes, [the option](https://github.com/asvetliakov/vscode-neovim/blob/6469c216f30c4bf29d5718f6d3fe99d517a33db0/vim/vscode-options.vim#L16) is hardcoded.

If the scrolloff=100, shouldn't the current row be centered?

**Comment by wscnd** [comment]
See https://github.com/VSCodeVim/Vim/issues/1427#issuecomment-520499830
