### ISSUE TITLE
youAreAwesome

### ISSUE THREAD

**Issue by AstraWalker** [asvetliakov/vscode-neovim#574]

**Comment by AstraWalker** [comment]
Артем, 
вы просто Джокер!
Я использую Ваше extension  второй день и чувствую себя великолепно! 
позвольте заработать 100 тыс долларов и я перечислить Вам 10 тыс закат - мой налог!
Вы подняли уроверь VSCode на из каменного века на медный.
Я Ваш Деникинский человек. Умоляю не останавливаться! Бакыт

**Comment by samvv** [comment]
Closing this issue.
