### ISSUE TITLE
FYI <C-W>o not working since last vscode update (VSCode bug)

### ISSUE THREAD

**Issue by Nico-Guyon** [asvetliakov/vscode-neovim#575]
This is not an issue of vscode-neovim but a new bug introduced by the last vscode update.
I'm not sure if this is the right place to post this, but since I lost some time with this issue maybe I'm not the only one and this could be of use to someone ?

The command View: Join all editor groups is not working anymore on the lastest vscode version (1.54.1 March 2021)
vscode-neovim maps <C-W>o to this vscode command (workbench.action.joinAllGroups).

The issue is already taken care of and solved on the vscode repo (https://github.com/microsoft/vscode/issues/118268)
So we'll just have to wait for the next update.

Meanwhile if you're like me and use this command a lot you can still remap <C-W>o to another vscode command that don't join editors but close them instead.
It's not really the same nor ideal but better than nothing as we wait for the next vscode update.

Just add this key mapping to your .nvimrc file.

```
if exists('g:vscode')
    nnoremap <C-W>o <Cmd>call VSCodeNotify('workbench.action.closeEditorsInOtherGroups')<CR>
endif
```

**Comment by samvv** [comment]
Thanks for taking the time to post this! I've just noticed that a new version of VSCode was released today. I'm being optimistic here and assume that this bug was fixed with the latest release. Either way, it's not something we can fix. Anyone struggling with it should be able to search for this issue.
