### ISSUE TITLE
Add functionalities to stay in insert mode or temporarily disable vim mode 

### ISSUE THREAD

**Issue by peromage** [asvetliakov/vscode-neovim#579]
This is a great plugin to combine both advantages of neovim and vscode together. I really enjoy it.

I usually only use vim key bindings in normal mode. In insert mode, I disabled control key bindings for neovim and it's pretty much a "vscode" mode because sometimes it makes more sense to use mouse with vscode key bindings to do some vscode operations.

However, the insert mode is not persistent. If I change the focus it becomes normal again. Thus I have to regularly hit `i` to get into insert mode. Currently I bind `i` on `tab` which is easier for me to get into inert mode while my right hand is using mouse.

So back to the question. Is it possible to provide an option to stay in insert mode? or a function to temporarily neovim mode, which I can bind onto a key.

Thank you!

**Comment by asvetliakov** [comment]
Try startinsert vim command in OnWinEnter autocmd

**Comment by peromage** [comment]
Thanks! I didn't think about the vim way to do this. It works just fine for me.

I attached this piece of code in case someone is looking for the same stuff

```viml
let s:enabled_auto_insert_mode = 0

function! s:toggleAutoInsertMode()
    if s:enabled_auto_insert_mode
        augroup AutoInsertMode
            autocmd! 
        augroup END
        let s:enabled_auto_insert_mode = 0
    else
        augroup AutoInsertMode
            autocmd! 
            autocmd WinEnter * startinsert
        augroup END
        let s:enabled_auto_insert_mode = 1
    endif
endfunction

nmap <silent> <Tab> :call <SID>toggleAutoInsertMode()<CR>
```
