### ISSUE TITLE
When using o to open a new line, indentation is not respected

### ISSUE THREAD

**Issue by vdegenne** [asvetliakov/vscode-neovim#584]
Here's a video to demonstrate, but basically I use `o` to open a new line and insert some text. The problem is that it doesn't automatically indent, as you can see in the video the line open, the caret is moving to the new line but it goes at the start of the line.
I then have to press Tab to get the proper indentation and start typing, it's not so much of extra typing but it doesn't feel natural, plus it's none of the behavior of neovim and vsc, so I wonder if it's a bug.

https://user-images.githubusercontent.com/2827383/111926289-88428180-8aac-11eb-9efb-b47e3868a225.mp4

If it's not a bug and there is a way to fix that, sorry but I couldn't find anywhere how to, please let me know.

Thanks

**Comment by vlwkaos** [comment]
```
nnoremap o ox<BS>
nnoremap O Ox<BS>
```

**Comment by asvetliakov** [comment]
For `o`/`O` the indentation is being controlled by neovim side. Obviously for `Untitled` document there is no vim filetype info (which is based on a file extension)

**Comment by vdegenne** [comment]
@asvetliakov no sorry I should have mentioned that but the "Untitled document" was for the demo (the file is changed to JavaScript type). But even in my project files it is the same behavior.

**Comment by asvetliakov** [comment]
Check your init.vim / try with empty init.vim . Indentation must be working here so it's config error

**Comment by vdegenne** [comment]
@asvetliakov I am not sure what happened I created `init.vim` because it didn't exist and then it fixes the issue but even if I remove `init.vim` now and restart VSC it just works.
Anyways you showed me the way, thanks

**Comment by raffylopez** [comment]
`autoindent` might be getting set to disabled somehow, as was happening in my case, though for only certain file types

In init.vim:
```
" ------- vscode-neovim specific settings ----- "
" ...

" ------- Keep autoindent enabled for all filetypes all the time ----- "
autocmd BufEnter * silent! set autoindent

" ------- Stop vscode-neovim from loading remainder of file ----- "
if exists('g:vscode') 
   echo "VIM online."
   finish
endif

" ------- Rest of init.vim ----- "
" ...

```

**Comment by RhysFonville** [comment]
this coding is bad.
