### ISSUE TITLE
Line visual mode duplicates cursor

### ISSUE THREAD

**Issue by kroppt** [asvetliakov/vscode-neovim#59]
Press Shift+v, move up/down, notice that the cursor is duplicated on multiple lines. Pressing Shift+i inserts at each of the cursors.

Using extension version 0.0.34 on Windows 10 and VSCodium 1.40.1

**Comment by asvetliakov** [comment]
This actually is the feature 😄 . Well, definitely i should make a configuration option to disable that.

**Comment by kroppt** [comment]
I missed the part in the readme about that. It makes sense once I know about it.
