### ISSUE TITLE
doesn't handle remapped escape and caps lock key in linux

### ISSUE THREAD

**Issue by rosebeats** [asvetliakov/vscode-neovim#591]
Environment:

Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-24T18:27:15.725Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.10-arch1-1

Neo Vim Extension version: 0.0.78
Neo Vim version: v0.5.0-dev+1178-gf0ace6d41

Behavior:

I have the caps lock and escape keys swapped using the command `setxkbmap -option caps:swapescape`. The behavior works correctly in normal neovim, but neovim in the extension behaves like caps lock and escape were in their normal positions (except the escape key still toggles caps lock, but I believe that is handled by Xorg).

**Comment by samvv** [comment]
Hmm strange ... I suspect this is a bug in VSCode. Does the caps lock key trigger an escape in other parts of VSCode, e.g. in the files prompt when you type `<C-p>`?

**Comment by rosebeats** [comment]
Ah, yeah, looks like it is a bug with vscode (just is most evident in vscode-neovim). It does have the same behavior when typing in `<C-p>`

**Comment by rosebeats** [comment]
Looks like it's an open issue in VSCode https://github.com/microsoft/vscode/issues/23991 A workaround exists by setting `"keyboard.dispatch": "keyCode"`

**Comment by milesfrain** [comment]
Unfortunately, the `keyCode` workaround does not work for me.

For example, when trying to `ciw` and then pressing escape (via rebound capslock) vscode will either:
- Mess-up the cursor. Appears as insert mode (vertical bar) when actually in command mode (should be block).
- Adds a newline and prevents a proper undo. The text after the unwanted newline still remains after undoing with `u`.

https://user-images.githubusercontent.com/3578681/145667012-3cd529bf-07bf-4da1-9d66-a61f6a52469c.mov

I'm using a combination of `setxkbmap` and `xcape` (hold capslock for ctrl, tap capslock for escape):
```
setxkbmap -option ctrl:nocaps; xcape -e 'Control_L=Escape'
```

There are no issues if I press the actual escape key or use a keyboard with hardware remapping of capslock to ctrl/escape.
