### ISSUE TITLE
How to use VSCodeCall in vim?

### ISSUE THREAD

**Issue by tusqasi** [asvetliakov/vscode-neovim#592]
I can't figure out how to save file with my custom keybindings.

Check this out if something is needed.
These are my config files  for neovim.
[keybinding](https://github.com/tusqasi/my_all_dot_files/blob/master/.config/nvim/plugin/keymaps.vim#L7-L11)
~[modified vscode-neovim](https://github.com/tusqasi/my_all_dot_files/blob/master/.config/nvim/plugin/vscode-neovim.vim)~

**Comment by samvv** [comment]
Is there a reason you are defining `VSCodeCall`, `VSCodeCallRange`, etc yourself? They should already be there when you open VCode with this plugin.

**Comment by tusqasi** [comment]
I could find any documentation for calling VSCode functions from vim, which I could understand. So I started to do my stuff. 
Can you explain what is happening? 

I made it work now, but I don't have any idea why it works.
I updated my configs, check them out.

**Comment by guyguy2001** [comment]
You are right that VSCodeCall is already loaded - when this extension loads and runs your init.vim, it first defines `VSCodeCall`, `VSCodeNotify`, and other functions/maps; You can look at the files in the vim directory of this repo to see what exactly is defined.
It also defines g:vscode before loading your script - which means that when you put your code in an `if exists('g:vscode')` block, your code will only run if it's running from vscode.

As for documentations for this:
You have this section in the README: https://github.com/asvetliakov/vscode-neovim#invoking-vscode-actions-from-neovim
In particular, look at this example:
```
nnoremap <silent> <C-w>gd <Cmd>call VSCodeNotify('editor.action.revealDefinitionAside')<CR>
```
So in your case it would be:
```
if exists('g:vscode')
  nnoremap <silent><Leader>l <Cmd>call VSCodeCall("workbench.action.files.save")<CR>
endif
```

**Comment by tusqasi** [comment]
Thanks for the thorough explanation. It makes sense now.

I had implemented a crude version of your given mapping.

This solves my problem.
