### ISSUE TITLE
Add a command to enable/disable buffer synchronization

### ISSUE THREAD

**Issue by samvv** [asvetliakov/vscode-neovim#593]
Currently, we have to maintain a [fork][1] of EasyMotion in order to prevent VSCode's language server from throwing a lot of errors when navigating. It appears there might be a much simpler approach by using `EasyMotionPromptBegin`. If we define this auto-command to disable buffer synchronization and re-enable it on `EasyMotionPromptEnd`, we should be able to support the plugin as-is without any modification.

[1]: https://github.com/asvetliakov/vim-easymotion

**Comment by Shatur95** [comment]
I suggest you to take a look at [this](https://github.com/phaazon/hop.nvim) plugin. If you add support for it, you no longer need to maintain a plugin fork.

**Comment by samvv** [comment]
Cool I've never come across it, looks very interesting! Some users might still prefer to use `EasyMotion` because of other reasons though, so I think it would still be worthwhile to support both. It should not require a lot of changes, and we can ditch the fork in both cases.

**Comment by theol0403** [comment]
I don't know how this would work. You still need to synchronize something to know what the jump targets are. Easymotion replaces the text in the buffer with the jump labels, and then highlights them. If you were to disable the synchronization, you would only get the highlight, and not the label.

The fork works by sending editor decorations that contain the label, which is a vscode thing. I think the only way this can be possible without a fork is to use the extmark api to support hop.nvim: #363.

Please re-open the issue if you think there is another use for disabling buffer sync.
