### ISSUE TITLE
Add support for semantic highlighting so that syntax plugins work without any modification

### ISSUE THREAD

**Issue by samvv** [asvetliakov/vscode-neovim#594]
This is just an idea I had. I have no idea how feasible it is, or if it covers all cases.

The problem with a lot of highlighting plugins is that they do not work well with the syntax highlighter that is used by VSCode. In most cases, they are simply ignored and we have to modify the highlighting groups inside `init.vim` in order to force a certain terminal highlighting color.

I propose adding a [semantic highlighter][1] that receives the colors from Neovim and applies them to the VSCode editor. This will probably require wrapping existing VSCode highlighters and combining the results. I don't know whether VCode has an API that supports this, but it might be interesting to find out.

[1]: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by theol0403** [comment]
Why would this be good to have? I think it is better to use vscode's native/plugin syntax functionality, which is quite good, rather than trying to make a bridge from neovim's syntax hl. Would there be an advantage to this?

**Comment by samvv** [comment]
Support for more Neovim plugins that (ab)use the syntax highlighting would be the main use case. They would just work without any adjustments, which is in theory why this extension exists in the first place. However I agree that the benefits may not outweigh the costs in terms of development.

-------- Original Message --------
On 5 Jun 2021, 21:47, Theo Lemay < ***@***.***> wrote:
Why would this be good to have? I think it is better to use vscode's native/plugin syntax functionality, which is quite good, rather than trying to make a bridge from neovim's syntax hl. Would there be an advantage to this?
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/asvetliakov/vscode-neovim/issues/594#issuecomment-855287040">https://github.com/asvetliakov/vscode-neovim/issues/594#issuecomment-855287040", "url": "[https://github.com](<a href=)/asvetliakov/vscode-neovim/issues/594#issuecomment-855287040">https://github.com/asvetliakov/vscode-neovim/issues/594#issuecomment-855287040", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by asvetliakov** [comment]
for your use case you can enable specific vim highlight groups in the extension settings (and override standard blacklist). however, the way the VIM HL is working is through the vscode decorations which are very slow in big numbers. And no, it's not possible to implement this in the performance way

**Comment by theol0403** [comment]
@asvetliakov 

So are you saying that VIM HL through the semantic HL api instead of vscode decorations is not possible?I guess that makes sense, because highlights are different than simply reporting symbol types.

**Comment by asvetliakov** [comment]
vscode semantic api is pull model. however neovim HL is only push model and only for current neovim viewport. it's useless
