### ISSUE TITLE
Cursor being moved to start of line when entering Visual Mode

### ISSUE THREAD

**Issue by lucasvianav** [asvetliakov/vscode-neovim#596]
Hello! Hope you are well :)

Whenever I enter Visual Mode, the cursor is automatically moved to the start of the line, which is really not a problem for line-wise visual mode, but is quite frustrating when using character or block-wise visual mode.

Is there any way to make it stay in place (as it happens on terminal Neovim)? I tried searching for a solution before posting, but found none - maybe I'm not searching the right terms, idk. Anyway, thanks for the help!

In VSCode: 
![neovim-vscode](https://user-images.githubusercontent.com/23108450/113427975-5c78a300-93ac-11eb-9e22-ce35104224cf.gif)

In Neovim (terminal):
![neovim](https://user-images.githubusercontent.com/23108450/113427987-626e8400-93ac-11eb-8ee9-6bb8557c8b71.gif)

**Comment by asvetliakov** [comment]
Try with empty init.vim

**Comment by lucasvianav** [comment]
> Try with empty init.vim

Then it works, sorry about that... Do you have any idea what could be causing it - I mean, is there any usual setting that does this?

**Comment by lucasvianav** [comment]
Found it is an issue with the NeoVim Ui Modifier extension's configuration. Thanks for the help!

**Comment by vlrevolution** [comment]
Any fix?

**Comment by lucasvianav** [comment]
> Any fix? The plugin is really nice

I've opened [an issue](https://github.com/kensleDev/vscode-nvim-ui/issues/1) on the extension's repo, but got no response.
