### ISSUE TITLE
E484: Can't open file /share/nvim/syntax/syntax.vim

### ISSUE THREAD

**Issue by dschuessler** [asvetliakov/vscode-neovim#597]
The "Output" panel pops up every time I start VSCode and displays this message in the "vscode-neovim Messages" tab:

```
VSCode-Neovim:

Error detected while processing /Users/d/.vscode/extensions/asvetliakov.vscode-neovim-0.0.78/vim/vscode-options.vim:
line   38:
E484: Can't open file /share/nvim/syntax/syntax.vim
```

I'm on macOS 11.2.3. A `/share` directory does not exist. I appreciate help.

**Comment by thekarel** [comment]
What happens if you run neovim on the console?

**Comment by dschuessler** [comment]
For the record: Reinstalling neovim 0.5 from source made the error go away.

**Comment by ammkrn** [comment]
I'm getting this on MacOS as well (big sur 11.2.3).
```
vscode 1.56

NVIM v0.5.0-dev+1357-g192f89ea1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1622092495007.local
```

```
VSCode-Neovim:

E484: Can't open file /Users/machine/Downloads/nvim/nvim-osx64/share/nvim/runtime/syntax/syntax.vim
line   25:
E484: Can't open file /Users/machine/Downloads/nvim/nvim-osx64/share/nvim/runtime/syntax/syntax.vim
line   38:
E484: Can't open file /Users/machine/Downloads/nvim/nvim-osx64/share/nvim/runtime/syntax/syntax.vim
```

The file it's looking for does exist and is readable.

**Comment by EricHasegawa** [comment]
Is there a known solution to this? Having the same problem

**Comment by RyuzakiiL23** [comment]
> Is there a known solution to this? Having the same problem

withing your nvim-linux64 directory u can :
sudo cp -r share/nvim /usr/share 
Hope that helps

**Comment by etmorefish** [comment]
> > Is there a known solution to this? Having the same problem
> 
> withing your nvim-linux64 directory u can : sudo cp -r share/nvim /usr/share Hope that helps

Great, it's solved.

**Comment by RyuzakiiL23** [comment]
@juliangaal I dont remember lol try if it works that what we want Im just a user like u it fixed the problem for me so I shared that's all I dont even remeber what was the problem

**Comment by juliangaal** [comment]
It did work, thank you :+1:

**Comment by taherkk** [comment]
It is the runtime .vim files.
Even while we download the neovim using apt we get two packages neovim and neovim-runtime package.

**Comment by msbeigiai** [comment]
> > Is there a known solution to this? Having the same problem
> 
> withing your nvim-linux64 directory u can : sudo cp -r share/nvim /usr/share Hope that helps

Also in `/usr/local/share` id needed
