### ISSUE TITLE
[vim-easymotion] shows labels on the wrong characters

### ISSUE THREAD

**Issue by bogdan0083** [asvetliakov/vscode-neovim#60]
Neovim version: `NVIM v0.5.0-175-g525bb1b55`
Vscode version: 
```
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19030
```

Hi! I'm using your `vim-easymotion` fork and noticed that it shows labels on the wrong places quite often. Here an example:

Using the following mapping: `nmap <Leader>j <Plug>(easymotion-bd-f)`

Search for `o` char:
![image](https://user-images.githubusercontent.com/7077307/69693835-549a5600-1109-11ea-88da-acaf6aba73fd.png)

Search for `x` char:
![image](https://user-images.githubusercontent.com/7077307/69693875-74317e80-1109-11ea-8317-13c4835b7175.png)

Search for `n` char:
![image](https://user-images.githubusercontent.com/7077307/69693771-1f8e0380-1109-11ea-9544-c5f0c9cbd886.png)

Basically it works in some cases, but labels sometimes are completely off. I can't find any particular pattern when it fails.

Here's searching for `l` char with `let g:EasyMotion_smartcase = 1`:

![image](https://user-images.githubusercontent.com/7077307/69694644-1488a280-110c-11ea-8017-6c18b6d03a75.png)

Here you can see that it doesn't show labels on the `L` chars. Here's my init.vim you can use it (I used it as a showcase to reproduce the issue):
```
call plug#begin(stdpath('data') . '/plugged')
Plug 'junegunn/vim-easy-align'
Plug 'asvetliakov/vim-easymotion'
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'wellle/targets.vim'
call plug#end()

let mapleader='s'
set clipboard=unnamedplus
nmap j gj
nmap k gk
nmap e :call VSCodeNotify('workbench.action.quickOpenPreviousEditor')<CR>
nnoremap [t :Tabprevious<CR>
nnoremap ]t :Tabnext<CR>
nnoremap <Leader>r :call VSCodeNotify('workbench.action.reloadWindow')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('workbench.action.showCommands')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('editor.action.format')<CR>
nnoremap <Leader>/ :call VSCodeNotify('workbench.action.findInFiles')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('workbench.action.debug.selectandstart')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('workbench.action.debug.restart')<CR>
nnoremap <Leader>fe :call VSCodeNotify('workbench.action.openSettingsJson')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('workbench.action.quickOpenPreviousEditor')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('workbench.action.showCommands')<CR>
nnoremap <Leader><Space> :call VSCodeNotify('workbench.action.showCommands')<CR>
nnoremap <Leader>s :Write<CR>
nnoremap <Leader>q :Quit<CR>
nnoremap <Leader>Q :Qall<CR>

" Alisases to ]<Space> and [<Space>
nmap <Leader>[ [<Space>
nmap <Leader>] ]<Space>

nnoremap <Leader>q :Quit<CR>
nnoremap <Leader>Q :Qall<CR>

xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine

" shortcuts for textobj block
xmap b ib
omap b ib
xmap q iq
omap q iq
xmap c iw
omap c iw
xmap ; i;
omap ; i;

" Easymotion stuff
let g:EasyMotion_smartcase = 1
map <Leader>ZZ <Plug>(easymotion-prefix)

" <Leader>f{char} to move to {char}
nmap <Leader>j <Plug>(easymotion-bd-f)

" Extend
autocmd User targets#mappings#user call targets#mappings#extend({
    \ ';': {
    \     'pair':      [{'o':'(', 'c':')'}, {'o':'[', 'c':']'}, {'o':'{', 'c':'}'}, {'o':'<', 'c':'>'}],
    \     'quote':     [{'d':"'"}, {'d':'"'}, {'d':'`'}],
    \     },
    \ })

```

Thank you!

**Comment by asvetliakov** [comment]
Yes, this happens for me too. I'm not a power vimL user, but will look some time after fixing few extension issues. If you want look it too - here is the [link to code to add decorations](https://github.com/asvetliakov/vim-easymotion/blob/4706a1196130181500c161b799c4ec8cb8b451e6/autoload/EasyMotion.vim#L986-L1060). This possibly can be some easymotion algorithm which moves decorations to the end of the line

**Comment by bogdan0083** [comment]
I think I found the solution to the issue: [#1](https://github.com/asvetliakov/vim-easymotion/pull/1).
