### ISSUE TITLE
Visual block mode creates cursors in recesses

### ISSUE THREAD

**Issue by kroppt** [asvetliakov/vscode-neovim#61]
The behavior is different from neovim. Best shown with example.
Example text:
```
aoeu

htns
```
Steps to perform:
- Move cursor over the `o`
- Press `Ctrl+v`
- Press `2j`
- Press `Shift+i`
- Type `1`

Try it in Neovim.
The end result is the following:
```
a1oeu

h1tns
```

Now try the same thing in VS Code with this extension.
The end result is the following:
```
a1oeu
1
h1tns
```

The behavior for `Shift+a` is different, too. To summarize that one, neovim adds the values in the blank lines, along with adding whitespace to line them up, but the extension behaves as in the `Shift+i` case.

**Comment by asvetliakov** [comment]
Related to #59 . Same cause. Will do the option
