### ISSUE TITLE
plugin does not work if no file is opened

### ISSUE THREAD

**Issue by verajosemanuel** [asvetliakov/vscode-neovim#612]
Maybe my workflow is not right but I cannot use plugin if no file is opened. So I MUST open a file using mouse and then  the neovim is available.

**Comment by vlwkaos** [comment]
Try opening your file with quick open (which is normally done using keyboard shortcuts).

**Comment by theol0403** [comment]
Keybindings are not sent to nvim when the editor is not focused. You must use vscode keybindings or some of the ones provided by this plugin to navigate the vscode UI. `C-p` is an easy way to open a file.
