### ISSUE TITLE
Highlight Yank

### ISSUE THREAD

**Issue by vicecaycedo** [asvetliakov/vscode-neovim#618]
Is there any way to briefly highlight yanked text?

For example, the VSCodeVim extension provides a `vim.highlightedyank.enable` setting.
For Vim, plugins like https://github.com/machakann/vim-highlightedyank exist.
For Neovim, you can achieve the same functionality without any plugins by using Lua:
```
augroup highlight_yank
  autocmd!
  au TextYankPost * silent! lua vim.highlight.on_yank{higroup='IncSearch', timeout=200}
augroup END
```

Can something similar be done with vscode-neovim?

**Comment by vicecaycedo** [comment]
Apologies -- it seemed I just had a configuration issue.

Using the Lua autocommand works.

**Comment by bva99** [comment]
@vicecaycedo Could you please post how you fixed your issue? I can't seem to solve mine.  I added the exact same code snippet you provided in the OP to my init.vim file, but it is not working. I also added neovim commentary mappings, e.g. `nmap gcc <Plug>VSCodeCommentaryLine`, and they work.
