### ISSUE TITLE
Issue while typing (insert mode) - cursor is jumping to beginning of the line

### ISSUE THREAD

**Issue by L1szt** [asvetliakov/vscode-neovim#622]
During typing after some time my cursor randomly jumps to the beginning of the line while being in insert mode and typing. When removing the neovim extension everything works just fine.
I'm using the newest version of VSCode and the newest available version of the Neovim extension. I haven't installed any additional neovim extensions.

**Comment by Herasselbach** [comment]
I had the same issue when I gave the extension a try and this clearly caused me to not use it. Interestingly this doesn't happen when using the normal vim extension, but I can't figure out what is causing this problem.

**Comment by asvetliakov** [comment]
Nothing wrong with the extension, try with empty init.vim. Try to search for similar issues - some neovim plugins caused that.

**Comment by L1szt** [comment]
@asvetliakov the init file to which the path points I specified in the settings is empty, so that can't be the issue. Apparently another user also had this issue, so that is a weird coincidende.

**Comment by NethumL** [comment]
@L1szt I had this same issue a while back, intermittently, and recently it got much worse. I fixed it according to #554  
It seems that it's an issue with Kite, and removing the folder `<runtimepath>/pack/kite` fixes the issue. I think this is only if you have uninstalled the Kite companion app. Apparently, reinstalling Kite will fix the issue as well.
