### ISSUE TITLE
Access previous search queries and commands

### ISSUE THREAD

**Issue by tejasvi** [asvetliakov/vscode-neovim#623]
It has likely been asked before but I can't find it. How can I access previous searches and commands as done with `<C-p>, <C-n>` in vim?

**Comment by theol0403** [comment]
For the vim command line (commands, search, ect)? Those bindings should work by default, it's only \<Up> and \<Down> that does not work. Let me know if this is not the case for you.

**Comment by filchristou** [comment]
> For the vim command line (commands, search, ect)? Those bindings (C-p, C-n) should work by default
Hi. In my case VS-code 1.57.1 and NVIM v0.6.0-dev+12-gf515baedc this is still not working as intended.
With C-p I can only access the last command/search and not before. C-n is not working at all.
