### ISSUE TITLE
cannot map :wq<CR> or :q!<CR>, because it causes E382 error or freezes editor

### ISSUE THREAD

**Issue by Zyanite7** [asvetliakov/vscode-neovim#628]
trying to map e.g.:
`nnoremap Q :q!<CR>`
`nnoremap qq :wq<CR>`
result after 'qq': error appears in the status bar: E382: Cannot write, 'buftype' option is set
result after 'Q': editor freezes and a reload is needed. I suppose that it causes the actual nvim instance in backend to be closed instead of the current tab in vscode?

works fine:
`nnoremap Q :q!`
`nnoremap qq :wq`

Is there any workaround to this? <CR> works in other commands but not combined with saving or quitting.

**Comment by ACupofAir** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/213#issuecomment-594886110 This answer is helpful.

**Comment by theol0403** [comment]
Try to use `nmap` and not remap. This is because the plugin remaps those commands to send the action to vscode instead of nvim.
