### ISSUE TITLE
Sluggish cursor when used with nvim installed in wsl

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#63]
Doesn't happen with windows version of neovim
Extension explicitly defines kind as "ui" but using wsl's neovim is useful

If someone has this problem with linux (non wsl)/mac version - please report here.

**Comment by transtone** [comment]
because of the sluggish in vscodeVim and emVim, I found this project.
I tried use nvim with vscodeVim, the sluggish is still there.

but I can't use vscode-neovim, because `ESC` not work, I trapped in `Insert` mode and can't return `Normal`

**Comment by justinmk** [comment]
> I tried use nvim with vscodeVim, the sluggish is still there.

vscodeVim is a completely different project: https://github.com/VSCodeVim

@transtone are you sure you chose the right extension?

@asvetliakov btw this reminds me, would you consider a different name? "vscode-neovim" is a very generic name, and rather confusing for people looking through the VScode extensions list: it is too similar to (1) vscodevim and (2) https://github.com/Chillee/VSCodeNeovim.

**Comment by transtone** [comment]
> > I tried use nvim with vscodeVim, the sluggish is still there.
> 
> vscodeVim is a completely different project: https://github.com/VSCodeVim
> 
> @transtone are you sure you chose the right extension?
> 
> @asvetliakov btw this reminds me, would you consider a different name? "vscode-neovim" is a very generic name, and rather confusing for people looking through the VScode extensions list: it is too similar to (1) vscodevim and (2) https://github.com/Chillee/VSCodeNeovim.

I use it follow this guide: https://github.com/VSCodeVim/Vim#neovim-integration

**Comment by justinmk** [comment]
> I use it follow this guide: https://github.com/VSCodeVim/Vim#neovim-integration

Again, that is a completely different project than the one you're commenting in.

**Comment by transtone** [comment]
> > I use it follow this guide: https://github.com/VSCodeVim/Vim#neovim-integration
> 
> Again, that is a completely different project than the one you're commenting in.

Again, I don't want solve VSCoceVim's bug in vscode-neovim's issue.

I said this to let author know that other vscode vim extension have sluggish cursor problem too.
it maybe upstream bug from vscode itself.

**Comment by asvetliakov** [comment]
@transtone I'm aware of some performance problems, working on it
@justinmk 
 VSCodeNeovim is not released at all so it's not a problem. The extension is called "Neo Vim" in vscode marketplace. ```vscode-neovim``` is only for the git repo

**Comment by transtone** [comment]
I want use wsl's nvim, how can I set the path?

**Comment by asvetliakov** [comment]
@transtone 
This will be supported once 0.0.36 will be released (sometime soon)

**Comment by asvetliakov** [comment]
0.0.36 has "Use WSL" config flag. When enabled specify neovim path in WSL

Alternative approach it to mark ```extensionKind``` as workspace in local config, but not recommended since there will be 2 round trips ```neovim <-> remote extension host <-> vscode``` instead one

**Comment by transtone** [comment]
> 0.0.36 has "Use WSL" config flag. When enabled specify neovim path in WSL. Required `wsl.exe` and `wslpath` binaries
> 
> Alternative approach it to mark `extensionKind` as workspace in local config, but not recommended since there will be 2 round trips `neovim <-> remote extension host <-> vscode` instead one

Is there a settings example?

**Comment by asvetliakov** [comment]
@transtone 

for useWSL:
```json
"vscode-neovim.neovimPath": "/usr/sbin/nvim",
"vscode-neovim.useWSL": true
```

for extension kind:
```json
    "remote.extensionKind": {
        "vscode-neovim": "workspace"
    }
```

Warning: you might need to install additional software in WSL and configure neovim to allow windows <-> wsl system clipboard exchange. I haven't dig into it yet.
