### ISSUE TITLE
tab* commands in init.vim no effect

### ISSUE THREAD

**Issue by qwhcr** [asvetliakov/vscode-neovim#633]
Step to repo:

add `nnoremap tj :tabnext<CR>` in init.vim

open vscode with neovim extension

in normal mode, type tj, and no tab change observed.

**Comment by asvetliakov** [comment]
You need to use this instead: https://github.com/asvetliakov/vscode-neovim/blob/2b6e138da896ad12dd0f1bf49cae9366ca04812e/vim/vscode-tab-commands.vim#L37
