### ISSUE TITLE
VS Code creates hundreds of editors when using the git diff editor with the neovim extension

### ISSUE THREAD

**Issue by slrtbtfs** [asvetliakov/vscode-neovim#638]
Issue Type: <b>Bug</b>

* Use the neovim extension.
* Open a git repository and change some files.
* Go to the "SOURCE CONTROL" view and double click on one of the changed files.
* A diff view opens.

Expected Result: Nothing else happens.
Actual Result: Every second or so VS Code opens an addtional editor for an untitled file, with the same content as the file being diffed. Given enough time these can become hundreds of editors.

While there is no obvious relation between this bug and the neovim extension, an extension bisect yielded the result, that this only happens with the neovim extension enabled.

Extension version: 0.0.78
VS Code version: Code - Insiders 1.57.0-insider (37a12c9b0846167b2f68e9e1f276149d2d8b9b27, 2021-05-12T14:11:37.664Z)
OS version: Linux x64 5.11.18-300.fc34.x86_64+debug

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|23.22GB (1.47GB free)|
|Process Argv|--enable-features=UseOzonePlatform --ozone-platform=wayland . --disable-extensions --crash-reporter-id 411f56de-b555-40d6-a9be-5407c5120186|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehov:30301224
00j7a122:30294756

```

</details>

![image](https://user-images.githubusercontent.com/15368509/118056807-e09a4f00-b38a-11eb-806e-2bb17f040d05.png)

**Comment by asvetliakov** [comment]
#632
