### ISSUE TITLE
Automated copy creation of settings.json and keybindings.json

### ISSUE THREAD

**Issue by RocketSumit** [asvetliakov/vscode-neovim#639]
Whenever I try to edit settings.json or keybindings.json file with neovim extension enabled, the vscode suddenly start creating unstopabble copies of json files. It could only by stopped by disabling the neovim extension and shifting the editor focus to other files.
![Screenshot from 2021-05-14 10-54-41](https://user-images.githubusercontent.com/15028793/118225883-87720e80-b4a3-11eb-8a34-f2bcb132fa92.png)

**Comment by seandewar** [comment]
#632

**Comment by tadsn3w** [comment]
I confirm the same issue happen to as well.  
Windows 10.

**Comment by RocketSumit** [comment]
Copy of #632
