### ISSUE TITLE
System clipboard / undo hotkey?

### ISSUE THREAD

**Issue by kwonoj** [asvetliakov/vscode-neovim#64]
First of all, thx for plugin - I just started to use over existing vim plugin and feel much better.

Minor q around config:

- is there way to let use system clipboard?
- for some known hotkey (ctrl-z for undo for example), is there way to allow it?

Thanks again!

**Comment by bogdan0083** [comment]
> is there way to let use system clipboard?

Yep. Just add `set clipboard=unnamedplus` to your init.vim. Works for me just fine.

> for some known hotkey (ctrl-z for undo for example), is there way to allow it?

Open command palette > Preferences > Open Keyboard Shortcuts > Type the hotkey you want to get back (ctrl+d for example). > Right click on the `vscode-neovim` keybinding > Remove keybinding

If you want to remove all vscode-neovim keybindings for normal/insert mode please [check out this](https://github.com/asvetliakov/vscode-neovim#insert-mode-special-keys).

**Comment by asvetliakov** [comment]
@bogdan0083 Already answered the questions, thank you!

For clipboard you can also might want to check ```:help clipboard``` or ```:help 'clipboard'``` help sections (works even in vscode!)

For ctrl keys - you can unbind them from vscode (won't send to neovim in this case) or rebind key in neovim itself, e.g: ```nnoremap <C-z> u```

**Comment by kkorus** [comment]
@asvetliakov How to unbind them from vscode?
