### ISSUE TITLE
Going into insert mode using 'a' moves insert carat extra characters to the right when foldcolumn>0

### ISSUE THREAD

**Issue by WiggyWare** [asvetliakov/vscode-neovim#641]
Steps to reproduce
Set foldcolumn=1
Position text on C in string ABCDE. 
Hit a to go into insert mode after current cursor position.

Expected result: carat is positioned between C and D.
Actual result: carat is positioned between D and E.

The carat will move whatever number the foldcolumn is set to extra characters to the right. It will stop when it hits a brace or paren, though. For some reason it evaluates those characters differently. For example. position cursor on B in string ABCDEF, set foldcolumn=3. Hit 'a' to go into insert mode. Carat is positioned between E and F. Do the same on string ABC(DEF, carat is positioned between C and (

**Comment by asvetliakov** [comment]
foldcolumn and vim folding are not supported
