### ISSUE TITLE
Installing NeoVim causes files to recursively open until I hard reset my PC

### ISSUE THREAD

**Issue by mm04926412** [asvetliakov/vscode-neovim#648]
Hi after installing neovim sometimes when I open a new file VScode will keep opening replicas of the file numbered "untitled" names and will keep doing this until I reset my pc as it does it so fast I am locked out of the keyboard.

I have no idea how this is happening and I haven't seen any other instances of it online.

**Comment by theol0403** [comment]
Duplicate of #632.

**Comment by mm04926412** [comment]
That was astonishingly fast.

**Comment by theol0403** [comment]
Eh, I get email notifications for new issues and close if they are easy to deal with 👍
