### ISSUE TITLE
`:w` to save new file failed

### ISSUE THREAD

**Issue by TroyDanielFZ** [asvetliakov/vscode-neovim#651]
`:w` to save newly created file failed, butI cannot figure out why.
Searched but no related issues.

**Comment by theol0403** [comment]
Is this a one-time thing, or does it still happen when you reload vscode?

**Comment by TroyDanielFZ** [comment]
> Is this a one-time thing, or does it still happen when you reload vscode?

Still happen.
Actually, the problem is `:w filename` fails to save the file. But coincidently I find that by typing only `:w` and press `Enter`, the save dialog prompts, and I can type the filename in the dialog. An alternative to save newly created file.

**Comment by likern** [comment]
I can confirm that. I think the reason is the VS Code updates (new versions), at least before everything worked smoothly.
Not only `:w` doesn't work, but also `:wq`. And I think many more (but haven't tested).

My OS is Fedora 34.

**Comment by likern** [comment]
VS Code version is `1.59`. Also doesn't work on `1.60-insider` with different set of settings and plugins.

Deleting and installing vscode-neovim again didn't help.

**Comment by likern** [comment]
Deleting `NVIM v0.6.0-dev+130-gc479b9035` and installing `NVIM v0.5.0` **solved the problem**.
At least I can save with `:w` and save and quit with `:wq` 😄

**Comment by TroyDanielFZ** [comment]
> Deleting `NVIM v0.6.0-dev+130-gc479b9035` and installing `NVIM v0.5.0` **solved the problem**.
> At least I can save with `:w` and save and quit with `:wq` 😄

Do you mean `:w filename` works fine on this configuration, or just `:w` to save the current opened/modified file(whish already has a name)?

**Comment by likern** [comment]
> > Deleting `NVIM v0.6.0-dev+130-gc479b9035` and installing `NVIM v0.5.0` **solved the problem**.
> > At least I can save with `:w` and save and quit with `:wq` 😄
> 
> Do you mean `:w filename` works fine on this configuration, or just `:w` to save the current opened/modified file(whish already has a name)?

Sorry, I might misunderstood original bug. I had problems with saving current file (which have name) using `:w`, I didn't use or test `:w filename` (didn't use this combination).

But I think these combinations are related. Because `:wq` also didn't work. I expect other similar shortcuts didn't work too.

**Comment by tlc** [comment]
I had this today too and fixed it by pointing VSCode neovim at a 5.0 version of nvim.

I noticed on the bottom bar:
> E492 not an editor command write

This _may_ be why I lost some extensive meeting notes today.  (I'm not sure, and apparently I would've had to fumble an exit dialog, so...)

**Comment by mayankbpatel** [comment]
Same here.  I had to revert to building neovim `v0.5.0` to get `:w` to work properly.

I spent several hours tracking down the issue.  I am disappointed the NeoVim authors didn't create regression tests to catch such issues.

**Comment by justinmk** [comment]
Move/delete your config then try again.

> I spent several hours tracking down the issue. I am disappointed the NeoVim authors didn't create regression tests to catch such issues.

This extension is not maintained by Neovim.
