### ISSUE TITLE
vscode-neovim Messages - errors during startup in the Output Panel

### ISSUE THREAD

**Issue by srustamo** [asvetliakov/vscode-neovim#661]
extension version v0.0.8
macOS 10.14.6
NVIM v0.5.0-dev+1385-g93f15db5d

vscode-neovim is the only extension installed.

I get over 6000 lines of errors related to this ext-n in in the Output Panel during the start up. Here are the first few lines:
```
"<90>^D" 
E212: Can't open file for writing: permission denied
E492: Not an editor command: H<81><c1>@<ff><ff><ff>H<83><f9>=w%D<89><f1><ba>^A
E492: Not an editor command: H<ff><c2>H9<ca>r<eb><eb>^FA<be>^A
E492: Not an editor command: I<89>݄<c0>^O<85><be><fe><ff><ff>H<8b>E<d0>H<83><c4>^X[A\A]A^A_]<c3>UH<89><e5>SPH<89><fb>荎^D
line    1:
E688: More targets than List items
E121: Undefined variable: original_name
line   12:
E121: Undefined variable: original_name_tail
line   13:
E121: Undefined variable: original_name_tail
E116: Invalid arguments for function range
Error detected while processing /usr/local/bin/nvim:
```
Is this normal?

**Comment by theol0403** [comment]
Can you try with an empty init.vim?

**Comment by srustamo** [comment]
Commented out the whole init.vim file. Still the same issue. 

The attached screencast shows the start-up process and the error trace in the Output Panel.

https://user-images.githubusercontent.com/749813/121502060-3e0cd480-c9f9-11eb-8759-c700cfc8d06e.mov

**Comment by MenuItem207** [comment]
I had the same problem. Turns out, it was because I had written the wrong path for the init.vim file in the neovim extension settings.

**Comment by srustamo** [comment]
Thanks.

**Comment by m42martin** [comment]
I saw this error after installing NeoVimSync.  I already had vscode-neovim configured correctly.  The new extension also defines the path to nvim executable, which in my case wasn't the correct path.  Maybe it's due to the load order, but NeoVimSync must have been overriding the correct path.

**Comment by pokemonsta433** [comment]
Had this issue too, realized it was because my nvim executeable was configured to launch as administrator on windows. If you've arrived here post 2025, maybe check that!
