### ISSUE TITLE
Enter binding for list.select takes precedence over default Notebook: Edit Cells

### ISSUE THREAD

**Issue by jwpeddle** [asvetliakov/vscode-neovim#669]
I noticed today that `enter` stopped functioning to edit Jupyter cells. The shortcut troubleshooter told me it was firing list.select for vscode-neovim, introduced in 0.82. I'm not sure what use case the keybind is supposed to be handling, but I imagine all Jupyter users will quickly discover this. I've changed the When condition to `listFocus && !inputFocus && !notebookCellListFocused` to workaround the issue.

https://github.com/asvetliakov/vscode-neovim/commit/8ee0c96a0e42525b898f85c29c38639a44ecdfa5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R417-R419

**Comment by theol0403** [comment]
Apologies for this regression, and thanks for reporting!

Better integration for Jupyter cells is something I want to address. I thought that currently there were too many problems to be usable with this plugin.

Would you be willing to explain what you did to be able to use jupyter with this plugin, in such a way that the enter key was actually useful? How did you exit and navigate cells? How was the enter key usable before the change? 

The new list bindings are to navigate in the explorer tree and other lists.

Thanks

**Comment by jwpeddle** [comment]
I've only been using vscode for a few days (thanks to this extension!), and everything just worked automatically. If I'm in a cell, vscode-neovim seems to capture all the keypresses it would catch in a normal buffer, and if I'm not in a cell, Jupyter shortcuts work just fine (j/k to navigate, enter to edit cell, etc). The only gotcha I hit was getting _out_ of a cell, so I mapped escape to do that:
https://github.com/asvetliakov/vscode-neovim/issues/210#issuecomment-860145152

**Comment by theol0403** [comment]
I'll try to make a PR soon that not only addresses this but provides better integration with jupyter overall. Stuff like escaping properly (I'd probably implement it in package.json rather than vimscript) and cell navigation.

Also, did j/k to navigate work before 0.82? I would think that it would only be possible after the new list bindings.

**Comment by jwpeddle** [comment]
It did, yes. This is 0.81:

```
[2021-06-15 21:53:13.676] [renderer1] [info] [KeybindingService]: | Resolving J
[2021-06-15 21:53:13.676] [renderer1] [info] [KeybindingService]: \ From 2 keybinding entries, matched list.focusDown, when: config.jupyter.enableKeyboardShortcuts && notebookEditorFocused && !inputFocus && notebookType == 'jupyter-notebook', source: user extension ms-toolsai.jupyter.
```

**Comment by theol0403** [comment]
Thanks. I didn't know that the jupyter extension provided j/k shortcuts through `jupyter.enableKeyboardShortcuts`. It's basically the same as the new list shortcuts from this plugin, so we don't need to care about precedence.
