### ISSUE TITLE
input method settings

### ISSUE THREAD

**Issue by transtone** [asvetliakov/vscode-neovim#68]
Can you please add a settings to change input method like VSCodeVim?

https://github.com/VSCodeVim/Vim#input-method

**Comment by asvetliakov** [comment]
Does something like this work for you? (put into your init.vim, you need [im-select](https://github.com/daipeihust/im-select) binary)

```autocmd InsertEnter :!/usr/local/bin/im-select com.apple.keylayout.US```

**Comment by transtone** [comment]
> Does something like this work for you? (put into your init.vim, you need [im-select](https://github.com/daipeihust/im-select) binary if you're on win/mac)
> 
> `autocmd InsertEnter :!/usr/local/bin/im-select com.apple.keylayout.US`

I tried this in windows10, but not work.
`autocmd InsertEnter :!notepad`

**Comment by Jackiexiao** [comment]
when I leave insert mode, it will automatically jump to `neovim output pane` instead of staying in editor, how could i solve this problem? 
![image](https://user-images.githubusercontent.com/18050469/93477012-0d49b400-f92d-11ea-8eeb-b9275a0ce888.png)

**Comment by Shatur95** [comment]
@Jackiexiao, could you try it with clear Neovim config?

**Comment by asvetliakov** [comment]
Try
`autocmd InsertLeave * :silent !C:\\....`

**Comment by Jackiexiao** [comment]
> Try
> `autocmd InsertLeave * :silent !C:\\....`

Works! Thx!
