### ISSUE TITLE
macro breaks when applying macro in visual mode involving paste in insert mode

### ISSUE THREAD

**Issue by echaya** [asvetliakov/vscode-neovim#682]
when recording the macro on line 1( `abc`) with `yawA=^R+^[` and then highlight line 2,3,4 and apply the macro 

```
abc
bcd
cde
def
```
in nvim, it becomes:
```
abc=abc
bcd=bcd
cde=cde
def=def
```

in vscode, it becomes:
```
abc=abc
bcd=abc
cde=abc
def=abc
```

It is working fine in normal mode. just that the registry is not correctly read in the visual mode.

**Comment by echaya** [comment]
update: recorded another macro but ***doing paste in normal mode*** achieve what i wanted: `yawA=^[p`.

**Comment by theol0403** [comment]
I think this is because when you do ctrl+r, the plugin reads the register and then inserts the text as if it was typed. 

Instead, there needs to be some mechanism that tells neovim to refer to the register instead of raw text.

I might have an idea to add to #680

**Comment by echaya** [comment]
>I think this is because when you do ctrl+r, the plugin reads the register and then inserts the text as if it was typed.

thanks @theol0403 for your response. That's what i thought as well XD

But strangely it only affects running macro (`yawA=^R+^[`) in visual mode but not in normal mode unless they are handled differently when the plugin reads the register.

**Comment by theol0403** [comment]
Humm, interesting. I'll try to reproduce. Also, it turns out the idea I had was already implemented :smile:

**Comment by theol0403** [comment]
Why are you pasting from the + register? Do you have some clipboard config? When I paste from the default register `"` it seems to work fine to run `:norm @a` on a visual selection. Was there a different way you applied the macro?

**Comment by echaya** [comment]
i have `set clipboard=unnamed` per https://vim.fandom.com/wiki/Accessing_the_system_clipboard and have been using `<c-r>+` to access the last clipboard value (either from the internal clipboard or the system clipboard). 

I did another tested, in vscode `"` works in visual mode with the macro but not `+`. However, in nvim, both `"` and `+` works. 

It really looks like is a corner case in this sense XDDDD

**Comment by echaya** [comment]
On a side note, i usually apply macros in visual mode by directly typing out `@x` instead of going into `:norm @x` (saving me several strokes :D

The method used to apply macro isn't relevant to the 'bug' in this case

**Comment by echaya** [comment]
i'll close this one given how corner case it is.
