### ISSUE TITLE
Neovim disconnects and exits with error code 1

### ISSUE THREAD

**Issue by ThiagoLira** [asvetliakov/vscode-neovim#685]
I'm trying to use this extension on a fresh install of Pop OS! and it just doesn't work. I keep getting these errors. I'm using a neovim nightly appimage which works fine outside of VS Code. The paths are correct and I'm not using any extensions on neovim. VS Code logs doesn't show anything happening apart from loading the extension. 

![image](https://user-images.githubusercontent.com/11686042/123859577-34410780-d8fb-11eb-8f95-b20049413540.png)

**Comment by ThiagoLira** [comment]
Managed to fix it by installing VS Code from a .deb file and not via flatpak.

**Comment by VProfirov** [comment]
@ThiagoLira that is not a fix. 
The idea is for it to be able to work from flatpack installation and in fact as flatpak should be (from security and ease of use perspective) the preferable way.

Adding to the situation: the same problem has another message : MainController: spawn /usr/bin/nvim ENOENT

Granting all needed permissions using Flatseal doesn't fix it either.

It will be greatly appreciated if an example of settings.json configuration for the neovim extension is added with the mention of what minimal permissions are needed for the work of the extension with a custome init.vim in the /home/$USER/.config/nvim directory.
