### ISSUE TITLE
cursor jump

### ISSUE THREAD

**Issue by transtone** [asvetliakov/vscode-neovim#69]
text example:
```
测试微服务

没办法跳转到最后一个
 
"requied just funnuy

<FormItem label="客户端类型" required>
```

use `h`, `l` key move in this text, will jump from col1 to col4.

nvim.exe in cmd works fine.

**Comment by asvetliakov** [comment]
russian chars and probably others non latin chars are also affected

**Comment by asvetliakov** [comment]
```nvim_win_get_cursor()``` returns position relative to bytes not col position. Same in cmd nvim but looks like ui handles it.

**Comment by asvetliakov** [comment]
HL from ```grid_line``` events is byte col too, but actually takes 2 bytes instead 3 😕 

@justinmk do you have any clues what's going on here?
given the line:
```
没办法
```
```nvim_win_get_cursor(0)``` with cursor on 3rd char gives ```[1, 6]```

but trying to search for ```/法``` receives ```grid_line``` event from 4, i.e. it counts previous characters as 2 byte width. Is this a bug or intended behavior ?

![HL on 3 char](https://user-images.githubusercontent.com/8881674/70857187-2929b080-1eea-11ea-90b3-0e392f1fe4fd.png)
