### ISSUE TITLE
Function keys are not intercepted

### ISSUE THREAD

**Issue by luiz00martins** [asvetliakov/vscode-neovim#691]
How to reproduce
----
 - Create a mapping with a function key (e.g. `nmap <F1> :q`) in your `init.vim`
 - On a buffer, in the appropriate mode (normal mode in the example), press the keys on the mappnig (<kbd>F1</kbd> in this case).

What's expected to happen
---
vscode-neovim interceps the keystrokes and executes the mapping.

What happens
---
vscode-neovim does not intercept the function keys, and they are passed to VsCode (i.e. if there's a VsCode keybinding for that function key, it is executed, if not, the keystroke is ignored).

Thoughts
---
I'm not sure if this is a bug, or the intended default behaviour. If this is the intended default behaviour, then having a setting to change that would be great (as we have with <kbd>ctrl</kbd>), as some users might use those keys in their `init.vim`.

**Comment by theol0403** [comment]
This is intended behaviour. The plugin only intercepts mappings which are used by vim by default, and allows everything else to work regularly in vscode.

You must intercept the key yourself.

See https://github.com/asvetliakov/vscode-neovim#custom-keybindings
