### ISSUE TITLE
vim-airline implementation?

### ISSUE THREAD

**Issue by albert-ying** [asvetliakov/vscode-neovim#694]
I used this extension ever since I started using vscode, and I never tried vscode-vim until today. It seems that the vs-neovim beat it in anyway, but I noticed that the vscode-vim has an interesting implementation for vim-airline (they also showed it on their GitHub page). I'm wondering if it is possible to be implemented in vscode-neovim?

Of course, it is not a significant thing, but still nice to have!

**Comment by asvetliakov** [comment]
Does this extension work for you?
https://marketplace.visualstudio.com/items?itemName=JulianIaquinandi.nvim-ui-modifier

**Comment by albert-ying** [comment]
Thank you! 

I tried this extension. It's works for colors but messed up the cursor position, which make it unusable for me. But I'm still closing this issue as I found that I don't really need these color indicators.

**Comment by The-Compiler** [comment]
FWIW, you can probably get there to some degree with the [Customize UI extension](https://github.com/iocave/customize-ui), though it's quite a hack. Here is what I use to colorize the statusbar widget based on the current mode:

```json
    "customizeUI.stylesheet": {
        "#asvetliakov\\.vscode-neovim[aria-label=\"-- INSERT --\"]":
            "background-color: #98971a !important;",
        "#asvetliakov\\.vscode-neovim[aria-label=\"-- VISUAL --\"]":
            "background-color: #b16286 !important;",
    },
```

But with some more CSS magic, this probably could get much more fancy.
