### ISSUE TITLE
jk mapping doesn't work for escape key

### ISSUE THREAD

**Issue by pianocomposer321** [asvetliakov/vscode-neovim#70]
I want to use 'jk' to exit insert mode, but when I map that to escape in vscode settings, then I cant use j to move down anymore.

**Comment by asvetliakov** [comment]
see #52

**Comment by pianocomposer321** [comment]
That's really too bad! I am so used to the 'jk' mapping for leaving insert mode, I don't know if I'll be able to switch. Looks like I'll have to go back to regular vim until it's fixed.

**Comment by asvetliakov** [comment]
Due to vscode architecture and extension host delay this probably never will be fixed, sorry. I may accept PR though under an optional flag. May be someone will contribute later

**Comment by pianocomposer321** [comment]
In the other vim emulator for vscode, mappings like jj and jk work. Why does it work there but not in this extension?

**Comment by asvetliakov** [comment]
VSCodeVim is very laggy sometimes in insert mode, especially if you're working on big projects and something like big completion list appears. This is very frustruating for me and many others so i won't do anything that will potentially make insert mode laggy.

see [this](https://github.com/microsoft/vscode/issues/75627) and [this](https://github.com/microsoft/vscode/issues/65876) VScode issues for reference

**Comment by djamaile** [comment]
Is this still a problem?

**Comment by asvetliakov** [comment]
nope, you can map esc to `jj` or `jk` now

**Comment by djamaile** [comment]
Do you have a config example on how to do it? Because I can’t get it right.

**Comment by shawntax** [comment]
> Do you have a config example on how to do it? Because I can’t get it right.

There is an example [directly in the README](https://github.com/asvetliakov/vscode-neovim#enabling-jj-or-jk-as-escape-keys-from-the-insert-mode).

I also made a [comment in a related issue](https://github.com/asvetliakov/vscode-neovim/issues/245#issuecomment-699683072) on how to better understand the implementation, because it is hard to understand at first glance.

**Comment by gulliver-madrid** [comment]
Is it possible to create custom mappings to Escape?

**Comment by Amith-AG** [comment]
Adding the following code to `settings.json` worked for me:
```
{
    "vscode-neovim.compositeKeys": {
        "jk": {
            "command": "vscode-neovim.lua",
            "args": [
                [
                    "local code = require('vscode')",
                    "code.action('vscode-neovim.escape')",
                    "code.action('workbench.action.files.save')",
                ],
            ],
        },
    },
}
```
