### ISSUE TITLE
how to map alt + semicolon to linecomment?

### ISSUE THREAD

**Issue by untoreh** [asvetliakov/vscode-neovim#700]
Hello, I tried this in `init.vim`
```
xmap <M-;>  <Plug>VSCodeCommentary
nmap <M-;>  <Plug>VSCodeCommentary
omap <M-;>  <Plug>VSCodeCommentary
```
and also tried adding 
```json
	 	"key": "alt+;",
	 	"command": "vscode-neovim.send",
	 	"when": "neovim.mode == normal && editorTextFocus",
```
But it doesn't seem to work

**Comment by Dimfred** [comment]
{
        "key": "alt+;",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && neovim.mode == normal"
    },

dunno about the first, but this works.

**Comment by untoreh** [comment]
> 
> 
> ```
> {
>     "key": "alt+;",
>     "command": "editor.action.commentLine",
>     "when": "editorTextFocus && neovim.mode == normal"
> },
> ```
> 
> dunno about the first, but this works.

this does not work with multiline commenting

**Comment by Dimfred** [comment]
Thats interesting. You are right. However, the default `ctrl+/` command works, but when it is remapped to `alt+/` it breaks.

**Comment by untoreh** [comment]
vscode comment line function uses visual selection and according to this visual selection is not consistent between neovim and vscode: https://github.com/asvetliakov/vscode-neovim/issues/172

**Comment by suyby** [comment]
@untoreh Imitating your configuration solves the problem of selecting line comments. Excuse me, if you configure the selected block comments，Select how block comments should be configured?

**Comment by afonsocraposo** [comment]
I was struggling with this but got it to work.
I just added these lines to the neovim config file (nothing added to VSCode keybindings):
```vim
nnoremap <leader>cc <Cmd>call VSCodeNotify('editor.action.commentLine')<CR>
vnoremap <leader>cc <Cmd>call VSCodeNotifyVisual('editor.action.commentLine', 1)<CR>
```

**Comment by RoRep1ay** [comment]
@afonsocraposo , seems to be solved the problem for me. Quick question, is it possible to return to normal mode after commenting the line in visual mode? 
I've tried adding `<Esc>`  or replacing `<Cr>` with `Esc` after the line but it still does not return the normal mode.

**Comment by afonsocraposo** [comment]
@RoRep1ay The following works for me:
```vim
vnoremap <leader>cc <Cmd>call VSCodeNotifyVisual('editor.action.commentLine', 1)<CR><esc>
```
