### ISSUE TITLE
Use own neovim client

### ISSUE THREAD

**Issue by asvetliakov** [asvetliakov/vscode-neovim#71]
```neovim/node-client``` sometimes is delaying notfications? Also it's using very old msgpack library

**Comment by justinmk** [comment]
We would be eager to receive PRs there as well.

**Comment by kwonoj** [comment]
@asvetliakov fyi I created PR https://github.com/neovim/node-client/pull/136 to bump up msgpack to latest, in a hope this could improve some of notification delay issues. Maybe we can enforce to use experiment wasm binary to see if it performs better.

**Comment by asvetliakov** [comment]
Since @kwonoj fixed the problem in `neovim/node-client` it's not needed anymore. Thank you!
