### ISSUE TITLE
use jk (to ESC) does not update the 'Insert' status

### ISSUE THREAD

**Issue by echaya** [asvetliakov/vscode-neovim#710]
Hi, 

plz see the gif below. 

when using `jk` (or `jj`) binding to escape from insert mode, the MODE label is not updated properly (bottom left in my screenshot). Using `<ESC>` or `<C-c>` works fine on my end. 

![insert mode](https://user-images.githubusercontent.com/34254408/127152439-aacfbc95-7243-4e1e-8344-cf18f766eda5.gif)

I'm running the latest version of the plug-in on Windows. I think the issue has been here since I started to use vscode-neovim.

**Comment by Yusuf007R** [comment]
yea same issue here.

**Comment by adamfeldman** [comment]
See also #270, #422

**Comment by theol0403** [comment]
Fixed by #772
