### ISSUE TITLE
In macos visual selection is not happening when doing v <c-d> and <c-u>.

### ISSUE THREAD

**Issue by shekhars094** [asvetliakov/vscode-neovim#717]
https://user-images.githubusercontent.com/18016032/127732657-90ae81e1-3cde-49b6-81a4-ddd964e8e2d3.mp4

**Comment by introom** [comment]
@shekhars094 How did you resolve this?

**Comment by yunyuyuan** [comment]
Also occured in windows.

**Comment by theol0403** [comment]
Will be fixed soon. Fixes are in master but have a bug.
