### ISSUE TITLE
Issues with vscode jupyter notebooks

### ISSUE THREAD

**Issue by oponkork** [asvetliakov/vscode-neovim#720]
Anyone using vscode-neovim + vscode v1.59.0 with inbuilt support for jupyter notebooks? I am facing the following problems:

1. Not able to jump from one cell to another. `j,k` at bottom(top) don't do anything.
2. Sometimes normal mode commands get stuck. Only thing I can do is to enter the insert mode using `i` and edit. Everything else freezes.
3. Abrupt cursor jumps within the cell.

Any help is appreciated!

**Comment by kaisengit** [comment]
I can confirm these same issues

**Comment by 9523115** [comment]
tried unmapping "Esc" from escape command and using j-j instead but didnt work. have to  toggle neovim in notebook !!

**Comment by theol0403** [comment]
Duplicate of #210.
Check out #680 and see if it solves your problems. If it doesn't, please reopen this issue.
