### ISSUE TITLE
insertmode shortcut doesn't work

### ISSUE THREAD

**Issue by ZHHHH9980** [asvetliakov/vscode-neovim#739]
i wrote a simple shortcut in js for 'console.log();'
![image](https://user-images.githubusercontent.com/52886395/131257343-dec5a173-dc2f-4e74-a5be-0f9031ea2737.png)

which means transform to console.log('xx',xx) when typing xx.log
it works in my neovim but doesn't work in vscode with neovim extension

i search google and read the document,only get a similar question is 'jk' can't map to \<Esc>,so that's the same problem?

if so,is there any solution?

Or, i have to write console.log('xx', xx) by hand, it's painful.

**Comment by justinmk** [comment]
insert mode is controlled by vscode, not nvim. that is a key compromise of vscode-neovim.

todo: the readme should explain this more clearly.
