### ISSUE TITLE
Cursor moves 4 chars to the right after entering insert mode (using `i`)

### ISSUE THREAD

**Issue by hoijui** [asvetliakov/vscode-neovim#742]
It happens somewhat sporadically. It seems to happen always when switching the view to a file, and after moving around a bit, and entering and exiting insert mode a few times, it works as expected.

I am pretty sure this is somehow related to my specific setup, as I was not able to find an issue like this, and it is a very annoying bug. ;-)
Is there a way to debug such a thing?
I tried with the AppImage NeoVim and with a self compiled one. same outcome.

**Comment by justinmk** [comment]
You probably have a Nvim plugin or some other config doing something unexpected.

**Comment by hoijui** [comment]
I disabled all extensions, and re-enabled just neovim; reloaded VSCodium, and it still happens.
So.. seems unlikely, that other extensions are the culprint. :/

**Comment by asvetliakov** [comment]
@hoijui 
>So.. seems unlikely, that other extensions are the culprint. :/

>You probably have a Nvim plugin or some other config doing something unexpected.
not vscode. nvim

**Comment by hoijui** [comment]
ahhhh :D
indeed, that is what he wrote (and I misread); and that was it!

I used an empty *init.vim*, and the problem was gone. Now I have to bisect which Vim plugin causes the problem (or continue using the empty script).

Thank you two!

**Comment by hoijui** [comment]
Found the culprint:

```vim
" Better line numbers (relative to current line)
" see https://github.com/myusuf3/numbers.vim#usage
Plug 'myusuf3/numbers.vim'
```

https://github.com/myusuf3/numbers.vim
