### ISSUE TITLE
Insert mode The cursor always jumps to the position it was at when it first entered insert mode after entering characters

### ISSUE THREAD

**Issue by photkey** [asvetliakov/vscode-neovim#745]
Win10
Vscode: 1.60.0
NeoVim: v0.5.0 (64-bit)
init.vim: empty file

![vscode-neovim](https://user-images.githubusercontent.com/60434581/132978010-c06484be-bc82-4626-8eba-162855da4d8d.gif)
In insert mode, when entering characters, the cursor always jumps to the top, as if the HOME key was pressed.

![vscode-neovim2](https://user-images.githubusercontent.com/60434581/132978016-476f0cc6-a1aa-45e1-8184-65ee4a6926f7.gif)
If there is already a paragraph of characters in front of you and you enter insert mode again, the input character jumps to the position where it was when you first entered insert mode, instead of jumping to the beginning of the line as if the HOME key was pressed.

This is not a problem when the NeoVim plugin is disabled.

Translated with www.DeepL.com/Translator (free version)

**Comment by raulbethencourt** [comment]
Hi i have the same problem did you find a solution

**Comment by photkey** [comment]
> Hi i have the same problem did you find a solution

Did you install the plugin Kite and uninstall or deactivate it? If so just delete all the folders of Kite. You can use everything to search for the keyword "Kite"

**Comment by raulbethencourt** [comment]
yes i found the solution thans other post and i deleted the pack/kite thanks 😄
