### ISSUE TITLE
Pressing Esc doesn't cause editor to enter normal mode

### ISSUE THREAD

**Issue by navxio** [asvetliakov/vscode-neovim#747]
```
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-7614-generic
```
Using vscode-nvim v0.0.82
and neovim: 0.6.0dev

**Comment by justinmk** [comment]
do you have a mapping (in nvim _or_ vscode)? did you read https://github.com/asvetliakov/vscode-neovim#custom-escape-keys 

closing since those should have been part of this report

**Comment by navxio** [comment]
@justinmk don't have an existing mapping in vscode, and using an empty config file with nvim
![image](https://user-images.githubusercontent.com/9297865/136048236-a414a5af-bf90-421f-8d38-1f35a831c184.png)

Read the custom-escape-keys brief but my problem is not about mapping insert characters..
