### ISSUE TITLE
WSL visual yank to clipboard

### ISSUE THREAD

**Issue by codematsing** [asvetliakov/vscode-neovim#761]
Hi there!

Is there anyone that was successful to visual yank lines of text in VSCode with WSL set?

**Setup**
I have in my VSCode settings:
```
Vscode-neovim › Neovim Executable Paths: Linux
Full path to Neovim executable that should be used by the extension if running VS Code on Linux or WSL.
If useWSL setting is checked, vscode-neovim will look for this path in WSL
Path:
/path/to/home/.local/bin/nvim #my install of neovim nightly

Vscode-neovim › Neovim Init Vim Paths: Linux
Full path to custom neovim init.vim file on Linux/WSL, equals to startup option -u. If the useWSL setting is checked, this path will be used to find init.vim in Windows Subsystem for Linux. You can also use exists('g:vscode') in your init.vim to check if neovim is being run in vscode and share init file between neovim/vscode
/path/to/home/.config/nvim/init.vim
```

I have in my /path/to/WSLHome/.config/nvim/init.vim:
```vim
set clipboard=unnamedplus
```

**Scenarios**
- Running nvim from terminal:
    -  visual highlight lines of text and trigger yank `y` does register to my windows clipboard
- Running using vscode with plugin vscode-neovim:
    - **expected scenario:** visual highlight lines of text and trigger yank `y` should register to my clipboard
    - **actual scenario:** does nothing
    - **other tests:** visual highlight lines of text and key `ctrl+c` only copies line where my cursor ends

Been searching for closed issues but no clear fix on WSL scenario. Thanks!

**Comment by codematsing** [comment]
Nevermind, I found a workaround. Hope this helps others having the same issue as me:

**Place in /path/to/WSLhome/.config/nvim/init.vim**
```vim
" References:
" [1] https://github.com/asvetliakov/vscode-neovim/issues/103
" [2] https://github.com/Microsoft/WSL/issues/892

set clipboard=unnamedplus " default
if has('clipboard') || exists('g:vscode') " [1]
    let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path according to your mount point [2]
    if executable(s:clip)
        augroup WSLYank
            autocmd!
            autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
        augroup END
    endif
endif
```

Tested it out in both terminal and vscode and it works

**Comment by jsonMartin** [comment]
> 
> 
> Nevermind, I found a workaround. Hope this helps others having the same issue as me:
> 
> **Place in /path/to/WSLhome/.config/nvim/init.vim**
> 
> ```viml
> " References:
> " [1] https://github.com/asvetliakov/vscode-neovim/issues/103
> " [2] https://github.com/Microsoft/WSL/issues/892
> 
> set clipboard=unnamedplus " default
> if has('clipboard') || exists('g:vscode') " [1]
>     let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path according to your mount point [2]
>     if executable(s:clip)
>         augroup WSLYank
>             autocmd!
>             autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
>         augroup END
>     endif
> endif
> ```
> 
> Tested it out in both terminal and vscode and it works

Awesome, thanks for sharing! I have been encountering this issue for a while and just searched for a fix today, and this works great 👍

It would be nice if this could be handled as a plugin option within VSCode, but if that's not technically feasible having this info in the documentation would be a big help to others
