### ISSUE TITLE
ctrl-] instead of "gf" mapping

### ISSUE THREAD

**Issue by justinmk** [asvetliakov/vscode-neovim#77]
`gf` is mapped to what normally would be `ctrl-]` in Vim. At least `ctrl-]` should be mapped to vscode's go-to-definition by default. But I would also question mapping `gf` by default--normally it goes to a file, not a symbol (and on "import" statements it goes to the relevant module).

**Comment by asvetliakov** [comment]
There is no 'go to file under cursor' command in vscode, but yes, need to map ```ctrl-]``` as well

note: need to make sure it works for ```:help``` too

**Comment by justinmk** [comment]
> There is no 'go to file under cursor' command in vscode

Why not let Nvim handle it? In general, any buffer loaded by Nvim could be opened as a tab (I guess) in vscode:

    :autocmd BufEnter * call Vscode_visit_file(expand('<afile>'))

**Comment by asvetliakov** [comment]
because vscode can handle more source types than neovim - from WSL/SSH/docker remote workspaces for example. I doubt that neovim will be able to gf in such case

**Comment by justinmk** [comment]
> because vscode can handle more source types than neovim - from WSL/SSH/docker remote workspaces for example. I doubt that neovim will be able to gf in such case

I guess, but `gf` has nothing to do with `vscodeGoToDefinition`. It's misleading. `gf` is for navigating to filepaths or import statements. 

With the autocmd I gave above (or something like it), `gf` could use Nvim's go-to-filepath functionality, however flawed it may be, which is more useful than having a random alias to `ctrl-]`.

**Comment by asvetliakov** [comment]
>I guess, but gf has nothing to do with vscodeGoToDefinition. It's misleading. gf is for navigating to filepaths or import statements.

vscode is able to open file by go-to-def on the import/include statement path so it's not actually true. It's like a smart mix of ```gd```/```gf``` commands. So use case "go to file under cursor" should be supported given there is language server for your language in vscode

**Comment by asvetliakov** [comment]
Also `BufEnter` autocmd breaks editor switching/editor moving to other pane in vscode since both neovim/vscode are trying to control the focused editor and they both think differently 😄
