### ISSUE TITLE
Can't get NeoVim extension to load on M1 Pro MacBook Pro

### ISSUE THREAD

**Issue by chivalry** [asvetliakov/vscode-neovim#770]
Every time I try to enable the NeoVim extension I get these error messages. It was working fine on the previous machine, an M1 13" MacBook Pro.

![image](https://user-images.githubusercontent.com/600992/141536658-8ab4681d-db83-4f8d-b724-c692d2a18a7c.png)

Any suggestions on how I can fix this? I'm using the Vim extension in the meantime, but definitely prefer the NeoVim extension.

**Comment by ifplusor** [comment]
@chivalry I encountered the same issue, could you describe the way you solve it?
