### ISSUE TITLE
VSCodeNotify to send visual selection to interactive Python window

### ISSUE THREAD

**Issue by oli666** [asvetliakov/vscode-neovim#771]
Following the instructions / examples of the README, I tried to use the helper functions to deal with visual selections for the VSCode Python / Jupyter Plugin. Using VSCode keymaps, I can send a line to the interactive window without issues. Trying to get the same behavior for the current selection, I used the following in my init.vim: 

`nnoremap <A-Enter> <Cmd>call VSCodeNotify('jupyter.execSelectionInteractive')<CR>`

This does have no effect. Any hint what I might be doing wrong?

**Comment by theol0403** [comment]
1. `nnoremap` is for normal mode only
2. use `VSCodeNotifyVisual`

You want:
```vim
xnoremap <A-Enter> <Cmd>call VSCodeNotifyVisual('jupyter.execSelectionInteractive', 0)<CR>
```

Also, you might need to send `A-Enter` to neovim using keybindings.json

**Comment by vsantalov** [comment]
Using the standard keymap ```shift+enter``` for sending visual selection to interactive window does not work.
init.vim is empty except for this line:
```xnoremap <S-Enter> <Cmd>call VSCodeNotifyVisual('jupyter.execSelectionInteractive', 0)<CR>```

I also tried adding this to keybindings.json:

```
    {
        "command": "vscode-neovim.send",
        // the key sequence to activate the binding
        "key": "shift+enter",
        // don't activate during insert mode
        "when": "editorTextFocus && neovim.mode != insert",
        // the input to send to Neovim
        "args": "<S-Enter>"
    }
```
