### ISSUE TITLE
Bad mode switch responsiveness

### ISSUE THREAD

**Issue by PolarianDev** [asvetliakov/vscode-neovim#777]
Going into insert mode works fine the majority of the time, however when trying to switch back to normal mode, sometimes the responsiveness is 5 or so seconds behind, this is a major issue if you are trying to code and then all of a sudden you get a bunch of h's j's k's and l's where you have tried to move and then realise that the plugin never responded to you leaving insert mode. Sometimes it takes a good 5-6 attempts for it to finally switch.

Version: 0.0.82
code-oss: 1.62.0
OS: Arch Linux x86

**Comment by iwanb** [comment]
I also get similar problems, along with other unresponsive things. From what I gathered it's a general problem in VSCode because all extensions share the same process, so if one extension is slow/blocks, other extensions get impacted.

https://github.com/microsoft/vscode/issues/79782

**Comment by PolarianDev** [comment]
I guess then this should  be reported on the vscode repository as it is not an issue with the plugin...

Is there no work around for this issue?

**Comment by iwanb** [comment]
I think this issue is more relevant: https://github.com/microsoft/vscode/issues/75627

I guess the only workaround for now would be to disable other extensions.

**Comment by theol0403** [comment]
Yes, this is a fundamental issue with vscode.

However, such slowdown is not normal, and is likely a culprit of your neovim settings/plugins & vscode extensions. 

When you exit insert mode vscode updates neovim with everything that happened - if you have a lot going on inside neovim, this might slow things down.

Reopen the issue if you experience the same behaviour with no plugins.
