### ISSUE TITLE
Why change the choice of visual mode to a non-vscode choice?

### ISSUE THREAD

**Issue by KahnDepot** [asvetliakov/vscode-neovim#778]
I found that in the initial 0.8 version, the visual selection under neovim was the choice of vscode. I think I need it instead of pressing f1 or ctrl+shift+p to change the selection.
Does this cause any problems? If possible, can you add an option in the next version for users to choose?
I need the choice of vscode to do a lot of things. Translating the selected sentence is a very common function, but unfortunately I have to press the previous f1 every time.

**Comment by KahnDepot** [comment]
I am currently using the vscode-vim plugin, but it is too stuck! The above feature request is the only advantage of vscode-vim and vscode-nvim.

**Comment by KahnDepot** [comment]
@asvetliakov

**Comment by KahnDepot** [comment]
很高兴你能在忙碌的工作中回复。 你对这个问题有什么看法？ @asvetliakov

**Comment by asvetliakov** [comment]
Because neovim doesn't have API to get visual ranges across whole buffer, only for current visible viewport. Why does it matter? say you have 1000 lines function but your viewport is 100 lines:

```js
// line 100
function blah() {
  ...
  // your at line 500
  ...
}
// line 1000
```

Now you're typing something like `va{` inside. We're unable to get visual range for whole `blah()` function, producing incorrect selection only for 100 currently visible lines

There is no way to workaround this

**Comment by KahnDepot** [comment]
I have tried f1 or ctrl+shift+p on windows and linux, but they will bring up the command panel (I can't modify the key binding to change this situation, vscode will pop up the command panel anyway, and I can' t modify f1 Or the binding of ctrl+shift+p, it will be invalid after modification), I also tried it on the mac, but unfortunately it is invalid. @asvetliakov

**Comment by KahnDepot** [comment]
For those whose English is not their native language, if the choice of vscode-nvim is the choice of vscode, then they will get the translation results faster without having to repeatedly press f1 or ctrl+shift+p.

As mentioned above, this feature is supported in version 0.62, why can't it be opened again? @asvetliakov

**Comment by KahnDepot** [comment]
Whether it can be returned in the next version, I think a large number of people are very happy to see this feature.

This is the only flaw of vscode-nvim, other than that it is perfect, and its author is also perfect. @asvetliakov

**Comment by wenfangdu** [comment]
> Because neovim doesn't have API to get visual ranges across whole buffer, only for current visible viewport. Why does it matter? say you have 1000 lines function but your viewport is 100 lines:
> 
> ```js
> // line 100
> function blah() {
>   ...
>   // your at line 500
>   ...
> }
> // line 1000
> ```
> 
> Now you're typing something like `va{` inside. We're unable to get visual range for whole `blah()` function, producing incorrect selection only for 100 currently visible lines
> 
> There is no way to workaround this

@asvetliakov @theol0403 This really should be mentioned in the doc, it explained the selection issue very clearly.
