### ISSUE TITLE
Does :registers work?

### ISSUE THREAD

**Issue by ryanmeisters** [asvetliakov/vscode-neovim#78]
Thanks for the awesome plugin--it's way better than the others. 

Should `:registers` work? It doesn't seem to do anything for me.

**Comment by justinmk** [comment]
The nvim "pager" currently doesn't display. vscode-neovim could capture pager events via the `ext_messages` UI option (see `:help ui-messages`). Maybe it could be displayed in a vscode popup?

**Comment by asvetliakov** [comment]
Currently multiline messages for things like ```:registers```, ```:jumps``` or ```:changes``` are not captured yet. I planned to make a special tree-view in sidebar to display them.
Alternative approaches are a) display in quick pick (a la command line widget) b) output channel. 
Bubbles won't work for such things.
