### ISSUE TITLE
It is recommended to change the neovim selection to the vscode selection

### ISSUE THREAD

**Issue by KahnDepot** [asvetliakov/vscode-neovim#783]
Pressing f1 or ctrl+shift+p is very troublesome, we need simpler functions to make its experience more similar to neovim.

I have made this suggestion many times, but I have never received a response. I want to know what are you worrying about? The early 0.62 also supports this feature, why cancel it?

**Comment by asvetliakov** [comment]
Making multiple issues about same feature won't help to deliver them. Dup of #778
