### ISSUE TITLE
[vim-surround] Changing surroundings leaves an empty pair of the original after the group

### ISSUE THREAD

**Issue by ramblingenzyme** [asvetliakov/vscode-neovim#79]
That is, doing `cs"'` over `"x"` will end up as `'x'""` instead of `'x'`. I've tried disabling the auto close options but that doesn't help. Thanks for this awesome plugin btw, I'd gotten so tired of the typing lag with the official Vim plugin.

**Comment by asvetliakov** [comment]
curious, doesn't happen for me... anything more specific? may be related to some specific cursor position?
