### ISSUE TITLE
normal mode and insert mode confused

### ISSUE THREAD

**Issue by ploirliu** [asvetliakov/vscode-neovim#795]
vscode-neovim the version 0.0.83 , when I in normal mode , the button show that I am in insert mode

only visual mode works correct

by the way , NVIM v0.7.0

**Comment by ploirliu** [comment]
somehow, I found it has not normal mode show.....

**Comment by ploirliu** [comment]
https://user-images.githubusercontent.com/10735783/147763292-7c6fc0fd-9f70-478b-9987-c2275659d2c3.mp4

**Comment by echaya** [comment]
see https://github.com/asvetliakov/vscode-neovim/issues/710#issuecomment-927909137
related to issue [#270](https://github.com/asvetliakov/vscode-neovim/issues/270), [#422](https://github.com/asvetliakov/vscode-neovim/issues/422)

**Comment by theol0403** [comment]
Fixed by #772
