### ISSUE TITLE
Incorrect search highlight with tab indentation

### ISSUE THREAD

**Issue by schiffermtq** [asvetliakov/vscode-neovim#81]
When searching in a file indented with tabs, the highlight is shifted 7 columns too far to the right (when using 8 space tab width):

![Screenshot_2019-12-09_13-24-57](https://user-images.githubusercontent.com/39995065/70435518-52c87f00-1a87-11ea-98b5-25f5dce2b32f.png)

- VSCode 1.40.2
- Neo Vim extension 0.0.39
- Neo Vim 0.5.0+ubuntu1+git201912090017-76d1e93-00e710e-795de22~ubuntu18.04.1 (Unstable PPA)

**Comment by asvetliakov** [comment]
Does the problem goes away if you do ```:retab``` command?

**Comment by schiffermtq** [comment]
No, `:retab` doesn't seem to have any effect.

**Comment by asvetliakov** [comment]
Confirmed, thanks for the report. Looks like tab options are not propagated correctly to neovim

**Comment by schiffermtq** [comment]
I tried the latest master, and the behavior seems significantly worse now (searching for "port"):

![Screenshot_2019-12-16_12-44-29](https://user-images.githubusercontent.com/39995065/70904714-55d0eb80-2002-11ea-8afa-ba92ce54de10.png)

Many incorrect pieces of highlighting appear during entering the search string and don't disappear when more characters are typed; even `:noh` doesn't work.

I've also noticed another related issue: rectangular selections using Ctrl-V aren't rectangular at all when lines indented using a different number of tabs are involved.

**Comment by asvetliakov** [comment]
Thanks for trying, curious, it works for me (using tabs & tab size - 8). Is it a large file? Setting decorators may be really slow
![image](https://user-images.githubusercontent.com/8881674/70914100-971fc600-2017-11ea-8f8b-0eb187a9ea1c.png)

Also currently it breaks if you change tab size and convert tab2spaces or spaces2tab - need to reopen the file (retab also should help in this case)

**Comment by schiffermtq** [comment]
Not really large, < 2000 lines. Highlighting doesn't feel slow in any way.

My init.vim only contains `set number`.

**Comment by asvetliakov** [comment]
shouldn't matter since i'm overwriting it with ```set nonumber``` but try to remove it (you don't need it anyway)

**Comment by asvetliakov** [comment]
ah and since you're building vsx from master manually, try to remove old extension from ```~/.vscode/extensions/asvetliakov.vscode-neovim-0.0.39``` before installing master version

**Comment by schiffermtq** [comment]
- Removed my init.vim setting
- Removed the old extension directory

This didn't have any effect.

I can't tell at all what triggers the issue, it seems to work for some search strings, and break for others, with no clear pattern. Having a long file with lots of weird indentation (like block comments indented by one space instead of tabs, or mixed tab+space usage for alignment) might have something to do with it, but I'm not sure.

My example file is https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/drivers/tty/serial/mxs-auart.c - searching for `AUART` seems to work okay at the top of the file, but `ASM` will show the issue starting around line 135.

**Comment by asvetliakov** [comment]
well it's strange because this file works for me too
![image](https://user-images.githubusercontent.com/8881674/70917441-a0ac2c80-201d-11ea-9d80-77d811a48b37.png)

what is your settings for vscode's ```Editor: detect indentation```, ```Editor: insert spaces``` and ```Editor: tab size``` once again? and the detected tab size in vscode's status bar

**Comment by asvetliakov** [comment]
Upd: reproduced now, searching for BIT in this screen breaks

**Comment by asvetliakov** [comment]
spaces between BIT has different tab size

**Comment by asvetliakov** [comment]
Looks like the problem comes with recently added mutli-byte character support - the cursor position actually is wrong while processing ```grid_line``` events so a wrong line is being taken into account for calculating byte offsets 😭

**Comment by asvetliakov** [comment]
@schiffermtq Could you try with latest master again? Hope this finally fixes it. Thanks!

**Comment by schiffermtq** [comment]
Thanks, search is working correctly now.

Should I open a separate ticket for the rectangular selection issue with tab indentation?

**Comment by asvetliakov** [comment]
Yes, please
