### ISSUE TITLE
:w removes space in the beginning of the line

### ISSUE THREAD

**Issue by asolopovas** [asvetliakov/vscode-neovim#82]
Hi, when I press` :` and `w` one space in the beginning of the line gets removed. Do you know why is that?

**Comment by asolopovas** [comment]
![WsdhGwjncD](https://user-images.githubusercontent.com/6893216/70438057-e3ea2680-1a84-11ea-99cd-4e37ebe60207.gif)

**Comment by asvetliakov** [comment]
Does it happen if you save it through a vscode 'save file' command? seems an external formatter kicks in

**Comment by asolopovas** [comment]
No
