### ISSUE TITLE
Identify Neovim inside VSCode

### ISSUE THREAD

**Issue by adelarsq** [asvetliakov/vscode-neovim#83]
Would be nice to be possible to identify that the neovim instance is being used inside VSCode, so we can load plugins by demand.

Did try this config, but didn't work as expected:

```vim
if has('g:vscode_channel')
   let g:editor = 'vscode'
   ...
if g:editor !=# 'vscode'
    Plug 'https://github.com/nathanaelkane/vim-indent-guides'
endif
```

**Comment by asvetliakov** [comment]
@justinmk what is the correct way to set something before user config loads? Currently [i'm setting vscode_channel var](https://github.com/asvetliakov/vscode-neovim/blob/e57f84df949ad23c2bfd20e0a93be827f115d4ac/src/controller.ts#L424) before ```ui_attach``` api call, but it doesn't seem to work

**Comment by justinmk** [comment]
That should work. Make sure you aren't using `--headless`

**Comment by adelarsq** [comment]
I notice that after the start from VSCode the variable is available. But on the neovim config loading phase isn't.

**Comment by asvetliakov** [comment]
@justinmk Not using headless but using [```-c```](https://github.com/asvetliakov/vscode-neovim/blob/e57f84df949ad23c2bfd20e0a93be827f115d4ac/src/controller.ts#L382-L386) to load vim support files. May be because of this? Perhaps i can just add ```--cmd``` to set it

**Comment by justinmk** [comment]
`-c` runs after user config. See `:help -c` . Use `--cmd`

**Comment by asvetliakov** [comment]
Once 0.0.40 released you can check with following:
```
if exists('g:vscode')
    " VSCode extension
else
    " ordinary neovim
endif
```
