### ISSUE TITLE
How to install plugin to neovim? 

### ISSUE THREAD

**Issue by kkorus** [asvetliakov/vscode-neovim#93]
My init.vim looks like:
(Windows 10)
```
set clipboard=unnamedplus

call plug#begin()
Plug 'tpope/vim-surround'
call plug#end()
```

but nvim.exe tells me that `Unknown function: plug#begin`

**Comment by justinmk** [comment]
'runtimepath' must be wrong. Does it work in nvim itself? Read the doc for vim-plug .

**Comment by asvetliakov** [comment]
Also if you're using WSL config flag, you must have plug installed in WSL neovim, not windows (same for config)

**Comment by kkorus** [comment]
My bad, I needed to put `plug.vin` under autoload dir.

**Comment by asvetliakov** [comment]
great to hear! i'm closing the issue then
