### ISSUE TITLE
Multiline selection with mouse is buggy

### ISSUE THREAD

**Issue by romanlv** [asvetliakov/vscode-neovim#94]
## Steps to reproduce 

- select multiple lines with mouse 
- press `dd`  
- notice that only one line is deleted
- `expected`: to delete whole selection range

**Comment by asvetliakov** [comment]
Oh yes, despite the having a conf option the mouse selection is not working now.

**Comment by kkorus** [comment]
@asvetliakov Would be nice to have it 😉

**Comment by piaodbg** [comment]
It's not woking with my vscode again.

Neovim v0.0.63

Vscode Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by piaodbg** [comment]
> ## Steps to reproduce
> * select multiple lines with mouse
> * press `dd`
> * notice that only one line is deleted
> * `expected`: to delete whole selection range

It's not woking with my vscode again.

Neovim v0.0.63

Vscode Version: 1.49.1 (user setup)
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:27:51.792Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Shatur95** [comment]
Could you try with clean config?
