### ISSUE TITLE
Creating newline and escaping doesn't remove new indentation

### ISSUE THREAD

**Issue by kroppt** [asvetliakov/vscode-neovim#98]
The example would be:
```
abc {
    def;
}
```
1. Put cursor on `def;` line.
2. Press `o`.
3. Press escape.
4. Note that the indention created is removed, because the new line was never typed on.

Do the same thing with this extension, and the indentation doesn't get removed like it does in neovim.

**Comment by asvetliakov** [comment]
this is a thing to bear with & live in. neovim is delegating ```o/O``` to vscode since it's smarter in indenting.

Even without delegating to vscode triggering insert mode will make vscode to take a control anyway and send a newline to neovim which will insert newline.
