### ISSUE TITLE
g:vscode not recognized

### ISSUE THREAD

**Issue by MartyBeGood** [asvetliakov/vscode-neovim#99]
I can't get my init.vim to have vscode-specific behaviour.

my init.vim looks like this:
```
if exists('g:vscode')
    source ~/.config/nvim/init_vscode.vim
else
    echo "vscode not detected. loading fancy stuff as well"
    source ~/.config/nvim/init_regular.vim
endif
```

This also goes to the else-branch when neovim is launched by vscode. That is visible because the echo message is visible in vscodes status line and because i have a `set list` in my init_regular.vim which messes with vscode syntax highlighting.
I tried checking for existence of other variables that are set by this extension (`g:vscode_noeditor_buffer`, `g:vscode_channel`, `g:vscode_primary_win`) as well, but no luck.

VSCode version 1.40.2 (Code - OSS build) **EDIT:** Occurs on official build of 1.41.0 as well
nvim version 0.4.3 (node integration installed)

**Comment by asvetliakov** [comment]
This will be available in 0.0.40 which is not released yet (sometime soon, probably today)

**Comment by asvetliakov** [comment]
@MartyBeGood 0.0.40 is released just now

**Comment by MartyBeGood** [comment]
@asvetliakov Thank you so much! It works like a charm now!
